### ISSUE TITLE
Some questions of add watermark

### ISSUE THREAD

**Issue by skyleelove** [gographics/imagick#100]
Hi,

  When I add a watermark to a image,I find that the word of my watermrk(the type is svg) is green,but I add it to image to get a new image,the word of watermark change to black.
       Watermark.ReadImage(markPath)
       Watermark.SetImageArtifact("compose:args", "15")
       Watermark.ModulateImage(75, 0, 75) // 0 saturation
       Watermark.SetImageOpacity(.30)

I use the functions to add a watermrk.How can i solve this problem.

**Comment by justinfx** [comment]
Hi. How does this issue relate to your still open question,  #90 ? Like that other issue, these are general ImageMagick api questions. Not really issues with the Go bindings. 

But I see you are desaturating the image. That would make colors go black. Is that what you expected?

**Comment by skyleelove** [comment]
Hi,I expect the work of watermark is green,but it change to black.Which function and the parameter should I give?

**Comment by justinfx** [comment]
If you get rid of the Modulate image, does it work? I would say, if you don't want black text, don't desaturate it?

**Comment by skyleelove** [comment]
Hi,
  Sorry to answer late.I solve the problem by install rsvglib to imagemagick.Thank you very much

**Comment by justinfx** [comment]
OK good. Glad you found the cause.
