### ISSUE TITLE
Could not determine kind of name for C.LanczosRadiusFilter

### ISSUE THREAD

**Issue by wjlight** [gographics/imagick#104]
I use Red Hat 4.8.2
`$ convert -version`
`Version: ImageMagick 6.9.6-4 Q16 x86_64`

`$ go get gopkg.in/gographics/imagick.v2/imagick`
`# gopkg.in/gographics/imagick.v2/imagick`
`could not determine kind of name for C.LanczosRadiusFilter`
or change 
`$ convert -version`
`Version: ImageMagick 7.0.3-6 Q16 x86_64`

`$ go get gopkg.in/gographics/imagick.v3/imagick`
`./affine_matrix.go:8:35: fatal error: MagickWand/MagickWand.h: No such file or directory`
` #include <MagickWand/MagickWand.h>`
`                                   ^`
How can I solve these problem?

**Comment by rogierlommers** [comment]
Did you install the devel version of Imagemagick?

**Comment by justinfx** [comment]
Please paste the output from this command 

```
pkg-config --cflags --libs MagickWand
```

**Comment by wjlight** [comment]
@justinfx 
`pkg-config --cflags --libs MagickWand`
-fopenmp -I/usr/include/ImageMagick  -lMagickWand -lMagickCore ``

**Comment by justinfx** [comment]
Bases on those paths and your error messages, I am guessing that your are picking up and older system ImageMagick when you are building the bindings. You may need to set your PKG_CONFIG_PATH to the location that contains your ImageMagick ".pc" files. This will control which ImageMagick is picked up by your build. 

What is the output of the following 2 commands? 

```
which convert
ldd `which convert`
```

Can you try to locate the pc files for your ImageMagick build and point at those?

**Comment by wjlight** [comment]
@justinfx  thank you very much, I set my PKG_CONFIG_PATH that contains my ImageMagick ".pc" files , it's ok~
