### ISSUE TITLE
Put SetResourceLimit at package level

### ISSUE THREAD

**Issue by gaillard** [gographics/imagick#107]
Would be nicer to stick SetResourceLimit at the package level since its global underneath anyways, then it would have to be called every time a MagickWand is created.

**Comment by justinfx** [comment]
I agree that it doesn't make sense to live as a member of `MagickWand`. It should be added to the package level, and the method on the wand can be deprecated.

> then it would have to be called every time a MagickWand is created.

What do you mean by this?

**Comment by gaillard** [comment]
Just meant people might think they need to call SetResourceLimit after each NewMagickWand().

**Comment by justinfx** [comment]
Well I am not sure why people would think they would have to call that method after creating a new wand, as opposed to any other method that looks like it sets something. But I still agree with making it a package level function :-)
