### ISSUE TITLE
static linking

### ISSUE THREAD

**Issue by minaevmike** [gographics/imagick#110]
Hi there. I see this issue #24 . I am trying to same but i have an error: 
```
CGO_LDFLAGS=-lstdc++ -lXext -lX11 -Wl,-Bstatic     -lMagickWand-6.Q16 -lMagickCore-6.Q16      -lIlmImf -lImath -lHalf -lIlmThread -lIex    -ltiff     -ljpeg      -lfontconfig -lfreetype -lxml2 -lexpat -lpng12 -lbz2 -lfftw3 -lz -lm -Wl,-Bdynamic
CGO_CFLAGS=-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6
```
on `go install -tags no_pkgconfig -v gopkg.in/gographics/imagick.v2/imagick` i have:
```
gopkg.in/gographics/imagick.v2/imagick
# gopkg.in/gographics/imagick.v2/imagick
/usr/bin/ld: cannot find -lImath
/usr/bin/ld: cannot find -lHalf
/usr/bin/ld: cannot find -lIlmThread
/usr/bin/ld: cannot find -lIex
collect2: error: ld returned 1 exit status
```
i am using ubuntu 16.04 also a have installed libilmbase12

**Comment by justinfx** [comment]
I see that your `CGO_LDFLAGS` is not using any `-L` flags to define the path that contain the libs. Have you tried telling the linker where your libs actually live? 

```
-L/path/to/libs -lIlmImf -lImath -lHalf -lIlmThread -lIex 
```

**Comment by minaevmike** [comment]
@justinfx i found the problem, on my system i don't have static libraies of ilmbase, only shared

**Comment by justinfx** [comment]
Ah ok. Thanks for following up

**Comment by JackIngleton** [comment]
@justinfx @minaevmike I know this is a very old issue, but I'm having the same problem (but also with extra libraries) and wondered if you had any advice on how to add static libraries of `ilmbase`?
I am running on a github actions ubuntu runner have tried with the default installed ImageMagick (6.9) and by cloning the latest ImageMagick and installing using the following commands:
```
./configure
make
sudo make install
sudo ldconfig /usr/local/lib
```

My go build command:
```
export CGO_CFLAGS="`pkg-config --cflags MagickWand MagickCore`"
export CGO_LDFLAGS="\
-lstdc++ -lXext -lX11 \
-Wl,-Bstatic \
    `pkg-config --libs MagickWand MagickCore` \
    -lIlmImf -lImath -lHalf -lIlmThread -lIex -ljpeg -ltiff \
    -llcms -lfontconfig -lfreetype -lxml2 -lexpat -lfftw3 -lpng12 -lbz2 -lz -lm \
-Wl,-Bdynamic"
GOOS=linux CGO_ENABLED=1 go build -tags no_pkgconfig -trimpath -o renderer -mod=vendor
```

error received:
```
/usr/bin/ld: cannot find -lImath
/usr/bin/ld: cannot find -lHalf
/usr/bin/ld: cannot find -lIlmThread
/usr/bin/ld: cannot find -lIex
/usr/bin/ld: cannot find -llcms
/usr/bin/ld: cannot find -lfftw3
/usr/bin/ld: cannot find -lpng12
collect2: error: ld returned 1 exit status
```

(I'm actually only using the ImageMagick `convert` command to create a pdf from some jpeg files if that simplifies anything).

**Comment by justinfx** [comment]
@JackIngleton that would seem like it can't find static libraries in the standard location. Have you tried adding an explicit `-L<path to .a files>` to see if that fixes it?

**Comment by JackIngleton** [comment]
@justinfx thanks for the really quick response!
Do you know if there is an easy way to find the path to those static libraries? (I'm struggling a little at the moment).

Are they installed by default by ImageMagick?

**Comment by justinfx** [comment]
@JackIngleton no those are completely separate libraries from the ImageMagick project, likely used as delegate plugins. Some of them are from OpenEXR. You could try a `locate <name> ` command to find where they are installed. Are you sure you even installed them in the first place?
