### ISSUE TITLE
Load more cpu

### ISSUE THREAD

**Issue by skyleelove** [gographics/imagick#112]
Hi,
    Imagemagick version: 6.9.6
    Linux version 2.6.32-642.1.1.el6.x86_64
    When I use gographics/imagick to process picture，the same qps，using gographics/imagick take more cpu。But I use lua to call C API of ImageMagick,it take less cpu。
    I find that when golang call libMagickCore-6.Q16.so.2 of ImageMagick take more cpu.I do not know whether CGO cause this result。How can I do for this？

**Comment by justinfx** [comment]
I don't have any experience with lua, but if your profiling shows that gographics/imagick is spending most of its time making a lot of cgo calls, over and over, then it could be that lua has less expensive access to calling into C, than Go. What kind of operation are you doing? Do you have an example of the Go and lua code?

**Comment by skyleelove** [comment]
lua:
local magick = require "imagick"
local img = magick.open("input.jpg")
local logo = magick.open("logo.jpg")
img:set_compose( magick.composite_op["CopyCompositeOp"] )
img:composite(logo, 0, 0)
img:write("out.jpg")

go:
package main

import "gopkg.in/gographics/imagick.v2/imagick"

func main() {
    imagick.Initialize()
    defer imagick.Terminate()

    dest := imagick.NewMagickWand()
    dest.ReadImage("logo:")

    w := dest.GetImageWidth()
    h := dest.GetImageHeight()

    watermark := imagick.NewMagickWand()
    watermark.SetSize(w, h)
    watermark.ReadImage("plasma:white-black")
    watermark.ModulateImage(100, 0, 100) // 0 saturation
    watermark.SetImageOpacity(.33)

    dest.CompositeImage(watermark, imagick.COMPOSITE_OP_DISSOLVE, 0, 0)

    dest.WriteImage("out.jpg")
}

**Comment by justinfx** [comment]
But these two examples aren't doing the same thing. You are doing more work in the Go version, using a different approach. The lua version seems to be reading in two jpegs. As far as I know, jpeg doesn't support alpha channels, so is the over composite even doing any work? 

What kind of results are you seeing between the two? Have you ever tried doing the same thing in lua?

**Comment by justinfx** [comment]
Closing for lack of follow up information
