### ISSUE TITLE
How to replace transparent background to white?

### ISSUE THREAD

**Issue by stefanahman** [gographics/imagick#113]
I'm trying to add a white background and resize an image with transparent background. This is a small sample application to reproduce the problem:
```go
package main

import (
  "io/ioutil"
  "gopkg.in/gographics/imagick.v1/imagick"
)

func main() {
  pw := imagick.NewPixelWand()
  mvo := imagick.NewMagickWand()
  mvo.ReadImage("image.png")

  mw := mvo.Clone()
  mwb := mvo.Clone()
  pw.SetColor("white")
  mwb.SetImageBackgroundColor(pw)

  mwf := imagick.NewMagickWand()
  mwf.AddImage(mw)
  mwf.AddImage(mwb)

  mwf.ResizeImage(100, 100, imagick.FILTER_LANCZOS, 1)

  mw.Destroy()
  mwb.Destroy()

  ioutil.WriteFile("small-image-with-white-background.png", mwf.GetImageBlob(), 0644)
}
```

In the end, the file `small-image-with-white-background.png` has still a transparent background.

Can any help me figure out what I'm doing wrong?

**Comment by rogierlommers** [comment]
Are you able to do this by using the `convert` util itself on the CLI?

**Comment by stefanahman** [comment]
@rogierlommers No, unfortunately not. I will use this code in a lambda function on AWS.

**Comment by justinfx** [comment]
You should look at using the composite operators. In your case, it sounds like an "over" operation, where the alpha of you image is use to place it over a filled white background 

https://godoc.org/gopkg.in/gographics/imagick.v2/imagick#MagickWand.CompositeImage

**Comment by stefanahman** [comment]
@justinfx I'm trying to do that as well. I have looked into this example that should do exactly what I want: https://github.com/gographics/imagick/blob/v1.0.0/examples/floodfill/main.go
But the result is a wizard with a transparent background.

Did I mention I have to use version `6.7.8.9` of ImageMagick (v1) because of [Amazon AMI](https://aws.amazon.com/amazon-linux-ami/2016.09-packages/)? Is that a problem?

**Comment by justinfx** [comment]
It shouldn't matter which version you are using, as the composite operations should have been around for a while. 

https://godoc.org/gopkg.in/gographics/imagick.v1/imagick#MagickWand.CompositeImage

I would think you wouldn't be interested in the flood fill, but rather 

```go
 bg.CompositeImage(fg, imagick.COMPOSITE_OP_OVER, 0, 0)
```

Do you have an example of your attempt at using the composite operators, which you say isn't working?

**Comment by stefanahman** [comment]
I manage to fix the problem. It was right in front of me all the time:
```go
  mw := imagick.NewMagickWand()
  mw.ReadImageBlob(b)

  pw := imagick.NewPixelWand()
  pw.SetColor("white")

  mw.SetImageBackgroundColor(pw)
  mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_REMOVE)
```

Thanks!
