### ISSUE TITLE
MagickWand.GetImageAlphaChannel() missing in imagick.v3

### ISSUE THREAD

**Issue by ChengHuaUESTC** [gographics/imagick#114]
I want to deal with a picture with transparent, and i do it with bellow.
```
if b := mw.GetImageAlphaChannel(); b == true {
    mw.EvaluateImageChannel(imagick.CHANNEL_ALPHA, imagick.EVAL_OP_MULTIPLY, 0.8)
} else {
    mw.EvaluateImage(imagick.EVAL_OP_MULTIPLY, 0.8)
}
```
In imagick.v3, there is no getimagealphaChannel(). If i want to deal with a picture with alpha channel, how could i do it?  Calling EvaluateImage() no matter there is an alpha channel?

**Comment by justinfx** [comment]
That must be an oversight in the IM7 support. Because I see the function is still available in the ImageMagick 7.0.4 docs:
http://www.imagemagick.org/api/MagickWand/magick-image_8c.html#ad3eeb92ad69507e947906e24f7d27225

So it is just a matter of adding that missing function.

**Comment by ChengHuaUESTC** [comment]
Thanks.
In IM6, Go::GetImageAlphaChannel() is calling MagickGetImageAlphaChannel(), and Go::EvaluateImageChannel() is calling MagickEvaluateImageChannel().

However, in IM7, there is no MagickEvaluateImageChannel() and do not found some other similar function.

**Comment by justinfx** [comment]
Here is the information about what changed in IM7:
https://www.imagemagick.org/script/porting.php#channels

> Previously MagickCore methods had channel analogs, for example, NegateImage() and NegateImageChannels(). The channel analog methods are no longer necessary because the pixel channel traits specify whether to act on a particular pixel channel or whether to blend with the alpha mask. For example, instead of 
> ```c
> NegateImageChannel(image,channel);`
> ```
> we use:
> ```c
> channel_mask=SetImageChannelMask(image,channel);
> NegateImage(image,exception);
> (void) SetImageChannelMask(image,channel_mask);
> ```

So they got rid of all the `###Channel` operations and instead made a way to set the context of which channel is affected by any of the normal operations. What we seem to be missing is `SetImageChannelMask()`. If we added that, then you would be able to set the channel mask to the desired type, do your normal `MagickEvaluateImage()` call, and then set it back to the previous value which gets returned in your call to `SetImageChannelMask()`

So the scope of this ticket is to add:
* `GetImageAlphaChannel()`
* `SetImageChannelMask()`

**Comment by justinfx** [comment]
Do you want to give the `114_missing_image_methods ` branch a try and confirm that it includes enough of the missing API to solve your problem?

**Comment by ChengHuaUESTC** [comment]
Yeah, I would test it to confirm which could solve my problem in next day.

**Comment by ChengHuaUESTC** [comment]
Sorry, I still do not know how to make a picture transparent with an alpha channel with your answer.

In imagick.v2, I make a picture transparent with alpha channel using mw.EvaluateImageChannel(imagick.CHANNEL_ALPHA, imagick.EVAL_OP_MULTIPLY, 0.8), and using mw.EvaluateImage(imagick.EVAL_OP_MULTIPLY, 0.8) if picture has no alpha channel.

**Comment by justinfx** [comment]
According to the changes in the ImageMagick 7 API, the equivalent of your approach would probably be:

```go
mw := imagick.NewMagickWand()
//...

var channel imagick.ChannelType
hasAlpha := mw.GetImageAlphaChannel()

if hasAlpha {
	channel = mw.SetImageChannelMask(imagick.CHANNEL_ALPHA)	
}

mw.EvaluateImage(imagick.EVAL_OP_MULTIPLY, 0.8) 

if hasAlpha {
	mw.SetImageChannelMask(channel)
}
```

You set the image channel mask to the desired channels, and then the image operations will only affect those channels. Afterwards, you can set it back to the previous value (if needed). Can you confirm that this works as you expect?

**Comment by ChengHuaUESTC** [comment]
It works not as my expect. 

`mw := imagick.NewMagickWand()
//...
/*****mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_ACTIVATE)****/

var channel imagick.ChannelType
hasAlpha := mw.GetImageAlphaChannel()

if hasAlpha {
        log.Infof("picture has an alpha channel")
	channel = mw.SetImageChannelMask(imagick.CHANNEL_ALPHA)	
}

var float64 degree
degree = 0.8
mw.EvaluateImage(imagick.EVAL_OP_MULTIPLY, degree) 

if hasAlpha {
	mw.SetImageChannelMask(channel)
}`

I add "mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_ACTIVATE)" as upper. In ImageMagick 6  it works well with the different argv degree, but it don't works in ImageMagick 7. 
And, if add mw.SetImageAlphaChannel(), hasAlpha will be as true.

**Comment by justinfx** [comment]
To be honest, I am not an expert in all of the ImageMagick API, so I am not sure what to suggest without testing the process myself. But I am happy to add any missing ImageMagick 7.x API methods that you find.

**Comment by ChengHuaUESTC** [comment]
Thanks. If I find some right and effective solutions, I would paste it here.

**Comment by justinfx** [comment]
Closing for now since there doesn't seem to be anything I can do without more information. Please ask for this to be reopened if we can help further with the issue
