### ISSUE TITLE
no decode delegate for this image format `WEBP' 

### ISSUE THREAD

**Issue by palaiyacw** [gographics/imagick#116]
The following code gives the error while reading the ImageBlob, due to original image was in `WEBP` format. So, how to build `imagick` with `WEBP` support    
  
**Code:**  
       
        mw := imagick.NewMagickWand()
	err = mw.ReadImageBlob(img)
	if err != nil {
		log.Printf(" Couldn't read the blob of key :", err)
		return nil
	}

**Error:**
`Couldn't read the blob of key : ERROR_MISSING_DELEGATE: no decode delegate for this image format WEBP @ error/blob.c/BlobToImage/355`

**Comment by justinfx** [comment]
This is usually not an issue at the level of the Imagick bindings. Can you even handle webp format through the "convert" tool on the command line. Did you build from source using the proper flags to enable webp?

**Comment by palaiyacw** [comment]
@justinfx Ok. I rebuilt the ImageMagick Library again after installing the `sudo apt-get install libwebp-dev`. And it worked. Before this i installed 7.x version of ImageMagick. So, my existing code did break. And it says `too many arguments in call to mw.ResizeImage
too many arguments in call to mw.ResizeImage
not enough arguments in call to mw.CompositeImage
not enough arguments in call to mw.CompositeImage
mw.TransformImage undefined (type *imagick.MagickWand has no field or method TransformImage)`. Did you change these functions in for the 7.x binding.

**Comment by justinfx** [comment]
I changed these functions to adjust for the changes in the ImageMagick 7.x API. For instance, they removed the blur setting from `ResizeImage()` and removed `TransformImage()` because it was a convenience method for calling `ResizeImage` and `CropImage`
