### ISSUE TITLE
Segmentation faults when using one or more goroutines?

### ISSUE THREAD

**Issue by ssttevee** [gographics/imagick#118]
When I try to read them as a blob in a goroutine while the main thread is doing something, I get a segfault.

```
package main

import (
	"gopkg.in/gographics/imagick.v2/imagick"
	"os"
	"bytes"
	"crypto/md5"
	"log"
	"time"
	"math/rand"
)

var images = []string{
	"image1.png",
	"image2.jpg",
	"image3.jpg",
	"image4.png",
}

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	go func() {
		for {
			in, err := os.Open(images[rand.Intn(len(images))])
			if err != nil {
				log.Println(err)
				return
			}

			var buf bytes.Buffer
			buf.ReadFrom(in)

			in.Close()

			log.Printf("%x\n", md5.Sum(buf.Bytes()))

			mw := imagick.NewMagickWand()

			if err := mw.ReadImageBlob(buf.Bytes()); err != nil {
				log.Println(err)
			}

			mw.Destroy()
		}
	}()

	for {
		time.Sleep(1 * time.Second)
		log.Println("do something")
	}

	select {}
}
```
Same thing happens the when the sleeper loop is in the goroutine and the imagick stuff is in the main thread

Doesn't happen if I comment out the sleeper loop

The weird thing is, only with the first image, it doesn't crash. The others crash right away.

Also, I did run this in a docker:
```
FROM golang:1.7.4-alpine3.5

RUN apk add --update alpine-sdk imagemagick imagemagick-dev

RUN go get gopkg.in/gographics/imagick.v2/imagick

ADD test.go /usr/src/imagick_test/main.go

RUN go build -o /test_exec /usr/src/imagick_test/main.go

ENTRYPOINT ["/test_exec"]
```

Here are the images:
[image1.png](https://cloud.githubusercontent.com/assets/434125/22265668/dd22ecb2-e231-11e6-8565-0e8a1f92a529.png)
[image2.jpg](https://cloud.githubusercontent.com/assets/434125/22265670/dd250704-e231-11e6-923e-86c5ba0b3329.jpg)
[image3.jpg](https://cloud.githubusercontent.com/assets/434125/22265669/dd243356-e231-11e6-8813-0f5ec7cea1ef.jpg)
[image4.png](https://cloud.githubusercontent.com/assets/434125/22265667/dd224f28-e231-11e6-9910-db5e8abad5b4.png)

**Comment by justinfx** [comment]
What version of ImageMagick and libjpeg/libpng end up being used in your docker image. I have seen other issues reported which ended up being only reproducible in the docker image because of older libs.

When you comment out the sleeper loop, wouldn't it just exit immediately? 

Your example only shows you using a single goroutine and doing a single process of an image in sequence. Is that right?

**Comment by ssttevee** [comment]
running `convert --version` returns
```
Version: ImageMagick 6.9.6-8 Q16 x86_64 2016-12-17 http://www.imagemagick.org
Copyright: Copyright 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher Modules
Delegates (built-in): fontconfig freetype gslib jng jpeg lcms ltdl png ps tiff webp xml zlib
```
not sure how to check libjpeg/libpng version but there are `libjpeg.so.8.1.2` and `libpng16.so.16.25.0` in `/usr/lib`

The `select {}` will wait until all goroutines finish.

My example shows one goroutine running a instance of imagick at a time and the main goroutine running a sleeper loop.  No difference compared to if I ran sleeper in another goroutine.

**Comment by ssttevee** [comment]
hm... I just noticed that's newer than what the readme says it supports

**Comment by justinfx** [comment]
The imagemagick version should be fine as long as its a recent 6.x
As for the libjepg/libpng, are you able to reproduce this crash on a non-container setup? If you dont see the problem, can you compare the libjpeg/png versions? The thing is, the Imagick bindings aren't doing anything at the layer of those libraries. The call just goes into Imagemagick, and then from there its in C and ends up going into the delegate plugins.

**Comment by ssttevee** [comment]
Unfortunately, I could not get it working properly on windows, my host machine.

However, I tried it using an ubuntu base and it seems to be working just fine.

It might be something musl vs glibc problem

**Comment by justinfx** [comment]
Thanks for confirming. yea in the past when people have reported seg faults from the delegate plugins, it usually ends up being the environment and combination of the version of delegates.
