### ISSUE TITLE
unable to load module '/usr/lib64/ImageMagick-7.0.4//modules-Q16HDRI/coders/png.la'

### ISSUE THREAD

**Issue by ChengHuaUESTC** [gographics/imagick#119]
When I call mw.SetImageFormat("png"), there is following error.
```
ERROR_MODULE: unable to load module '/usr/lib64/ImageMagick-7.0.4//modules-Q16HDRI/coders/png.la': file not found @ error/module.c/OpenModule/1279
```

And there is the file in server.
```
[san@yf-mos-corp-store-image01 ~]$ ll /usr/lib64/ImageMagick-7.0.4//modules-Q16HDRI/coders/png.la
-rwxr-xr-x 1 root root 1087 1月   8 02:04 /usr/lib64/ImageMagick-7.0.4//modules-Q16HDRI/coders/png.la
```

And mw.ScaleImage() is works well. Convert command is works well.

Does the problem cased by "//" between ImageMagick-7.0.4 and modules-Q16?

**Comment by justinfx** [comment]
I don't think the "//" is the issue since that is still a valid path (just not normalized). What I would guess is that maybe your libjpeg or libpng needs to be rebuilt, or something is wrong with your ImageMagick build. 

Similar issue listed here:
https://github.com/Homebrew/legacy-homebrew/issues/30846

I highly doubtful that this is a problem with imagick bindings

**Comment by justinfx** [comment]
Also, are you able to successfully use the `convert` command (ensuring its the same ImageMagick 7.0.4 convert) on a png?

**Comment by ChengHuaUESTC** [comment]
Convert command works well as follows.
[san@yf-mos-corp-store-image01 workspace]$ convert lena.jpg -resize 50% lena.png
[san@yf-mos-corp-store-image01 workspace]$ ll
-rw-rw-r-- 1 sankuai sankuai 68261 1月  18 2016 lena.jpg
-rw-rw-r-- 1 sankuai sankuai 19783 2月  13 14:27 lena.png

I would try with [Homebrew/legacy-homebrew#30846.](https://github.com/Homebrew/legacy-homebrew/issues/30846)

**Comment by ChengHuaUESTC** [comment]
I tested in a new environment.
Linux version 3.10.0-229.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Fri Mar 6 11:36:42 UTC 2015

Still having the problem, and other processes are OK.
And convert command is also OK.

```
[san@yf-mos-corp-store-image02 workspace]$ convert --version
Version: ImageMagick 7.0.4-3 Q16 x86_64 2017-01-07 http://www.imagemagick.org
```

**Comment by ChengHuaUESTC** [comment]
"libjpeg or libpng needs to be rebuilt" is right. 
The libpng version is not right and should replace 
"libpng-1.2.49-2.el6_7.x86_64, libpng-devel-1.2.49-2.el6_7.x86_64"
with
"libpng-1.5.13-7.el7_2.x86_64, libpng-devel-1.5.13-7.el7_2.x86_64"  .
