### ISSUE TITLE
Histograms?

### ISSUE THREAD

**Issue by Michael-Zinn** [gographics/imagick#12]
Could you make it more clear how to get the histogram of an image? Or is this not supported yet?

**Comment by sylnsr** [comment]
Pardon my ignorance, but in what sense is it a "naive" binding?  (naive, defined as "showing a lack of experience, wisdom, or judgment")

**Comment by justinfx** [comment]
It means that this Imagick library is a very thin binding on top of the ImageMagick C api. It isn't an original pure Go library and didn't invent the logic. It only thinly wraps the calls to ImageMagick and does type conversion and memory management. 

The reason for making that statement is that the Imagick project will receive questions on how to use ImageMagick features. But many times this is beyond the scope of our support. It tends to fall into a general usage of ImageMagick api itself regardless of the language (C, C++, Go, Python,  Perl, PHP,...) and can best be addressed on an ImageMagick forum with expert users.
