### ISSUE TITLE
How to create optimised and progressive Images (JPG, PNG)

### ISSUE THREAD

**Issue by palaiyacw** [gographics/imagick#125]
I am using the following code in go lang to resize my images in JPEG and PNG format. Could you please tell how do I convert them to progressive and optimized using Imagick library.
           
I am saying optimized reason being I used the following command to test whether image size gets reduced or not. But, it increases the output file size.  

`convert -strip -interlace Plane input-file.jpg output-file.jpg `

```
size = fmt.Sprintf("%dx%d^+0+0", w, h)
		tx := mw.TransformImage("", size)
		tx.SetImageGravity(imagick.GRAVITY_CENTER)
		offsetX := -(int(w) - int(tx.GetImageWidth())) / 2
		offsetY := -(int(h) - int(tx.GetImageHeight())) / 2
		err := tx.ExtentImage(w, h, offsetX, offsetY)
```

**Comment by justinfx** [comment]
I'm not totally sure on this but have you tried setting interlace to plane, as the ImageMagick convert docs recommend to result in progressive? 

https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.SetImageInterlaceScheme

**Comment by palaiyacw** [comment]
I did `mw.SetImageInterlaceScheme(imagick.INTERLACE_PLANE)`. But it doesn't make any difference in terms of size of resized image and their loading time in browser

**Comment by palaiyacw** [comment]
Does setting `ImageInterlaceScheme` be plane would make all the images to be progressive?

**Comment by justinfx** [comment]
On Sat, Mar 18, 2017, 2:06 AM Naresh Palaiya <notifications@github.com>
wrote:

> Does setting ImageInterlaceScheme be plane would make all the images to
> be progressive?
>

According to the docs, it suggested setting the wand to use interlace plane
would result in progressive images.

**Comment by palaiyacw** [comment]
@justinfx I tested the code after setting `ImageInterlaceScheme` to be `plane`. But in the browser, it still doesn't show in progressive manner after throttling the bandwidth.

**Comment by palaiyacw** [comment]
@justinfx Any other suggestions. I tried that but it's not working.

**Comment by justinfx** [comment]
Is this relevant? 

http://www.imagemagick.org/discourse-server/viewtopic.php?t=10556

Looks like more missing API in the bindings, to be able to set image options :

https://www.imagemagick.org/include/api/option.php

**Comment by palaiyacw** [comment]
@justinfx  I tried setting the `mw.SetImageInterlaceScheme(imagick.INTERLACE_PLANE)` and then checked using  `fmt.Println(mw.GetImageInterlaceScheme())` it printed value to be `3`.  So, in the code interlace value was set correct. Now, I send the response to browser and save the images on local disk. Now, I use `identify -verbose IMAGE_NAME` to check the value of Interlace which comes out to be `none`. Why is it so? I haven't changed anything after setting the Interlace in the code

**Comment by justinfx** [comment]
I don't know. It must only be setting MagickWand parameters and not
actually having an effect on the coder which writes the image.

**Comment by palaiyacw** [comment]
@justinfx I think there is something wrong with the go wrapper of image magick. I tried to set the interlace to be plane using command-line tool and it was done succesfully. Same thing I tried to do using go wrapper. Now to verify it i saved image before setting the interlace and after. In both the images i found interlace value to be `none`. Could you please look into it.

**Comment by justinfx** [comment]
I haven't had time to test anything, but look how small the Imagick Go layer is over this operation:
https://github.com/gographics/imagick/blob/v3.0.0/imagick/magick_wand_image.go#L2091

```go
func (mw *MagickWand) SetImageInterlaceScheme(interlace InterlaceType) error {
	ok := C.MagickSetImageInterlaceScheme(mw.mw, C.InterlaceType(interlace))
	return mw.getLastErrorIfFailed(ok)
}
```

**Comment by palaiyacw** [comment]
@justinfx I tried to debug further so I have realized that. I download the image from Amazon S3 before doing some manipulation using go wrapper. So, I saved the two files on local disk before creating the image magick object and after creating the object (`mw.ReadImageBlob()`). Now, I again tried to fetch the metadata and it shows after creating the object it loses the interlace property and it become `None` from `JPEG`. Could you please figure out now, why is it so?

**Comment by justinfx** [comment]
I've just tested this and everything seems to be working fine:

```go
package main

import (
	"fmt"

	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()

	if err := mw.ReadImage("logo:"); err != nil {
		panic(err)
	}

	mw.ResizeImage(640, 480, 0)

	mw.SetInterlaceScheme(imagick.INTERLACE_PLANE)

	if err := mw.WriteImage("/tmp/out.jpg"); err != nil {
		panic(err)
	}

	if err := mw.ReadImage("/tmp/out.jpg"); err != nil {
		panic(err)
	}

	if mw.GetInterlaceScheme() != imagick.INTERLACE_PLANE {
		panic(fmt.Sprintf("Expected interlace scheme %v, got %v",
			imagick.INTERLACE_PLANE, mw.GetInterlaceScheme()))
	}
	fmt.Printf("Interlace: %v\n", mw.GetInterlaceScheme())
}
```

This properly sets the interlace mode to "JPEG" (progressive) and also retains the `INTERLACE_PLANE` value when reading the image back in. Can you please provide an example of runnable code where you are not getting the right results?

**Comment by justinfx** [comment]
Nevermind. I forgot to `mw.Clear()` between the read and the write. The image reads back in with `INTERLACE_NO`. But the image was properly written out progressive.  I am not sure why its read back in with a different value. Maybe it only controls the write mode. Or maybe its a bug in ImageMagick.

**Comment by justinfx** [comment]
> Looks like more missing API in the bindings, to be able to set image options

Also, I overlooked this but we seem to have the appropriate API support for options:
https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.SetOption

And according to the docs, if I understand correctly, optimise is the default behaviour and has to be disabled explicitly.

**Comment by palaiyacw** [comment]
>  The image reads back in with INTERLACE_NO. But the image was properly written out progressive.
How did your check whether the image was properly written out to be progessive? 

> According to the docs, if I understand correctly, optimize is the default behavior and has to be disabled explicitly.
 So, how do I disable it and keep the interlace value to be same to serve the images to be in progressive manner, Any idea?

**Comment by palaiyacw** [comment]
> The image reads back in with INTERLACE_NO. But the image was properly written out progressive.

How did your check whether the image was properly written out to be progessive?

> According tto the docs, if I understand correctly, optimize is the default behavior and has to be disabled explicitly.

So, how do I disable it and keep the interlace value to be same to serve the images to be in progressive manner, Any idea?

**Comment by justinfx** [comment]
I checked that the values of "Interlace" was "JPEG" using the `identity -v image.jpg` command. It showed to be written as progressive when I set the scheme option and None when I didn't. 

As for how to read in the image with the preserved interlace scheme, I don't know the answer yet. Maybe there is some other place it can be read from.

**Comment by justinfx** [comment]
Based on the information you received from your post on [the ImageMagick ticket](https://github.com/ImageMagick/ImageMagick/issues/411#issuecomment-290632452), this approach works the way you want:

```go
package main

import (
	"fmt"

	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()

	if err := mw.ReadImage("logo:"); err != nil {
		panic(err)
	}

	mw.ResizeImage(640, 480, 0)

	mw.SetInterlaceScheme(imagick.INTERLACE_PLANE)

	if err := mw.WriteImage("/tmp/out.jpg"); err != nil {
		panic(err)
	}
	mw.Clear()

	if err := mw.ReadImage("/tmp/out.jpg"); err != nil {
		panic(err)
	}

	scheme := mw.GetImageInterlaceScheme()

	if scheme != imagick.INTERLACE_JPEG {
		panic(fmt.Sprintf("Expected interlace scheme %v, got %v",
			imagick.INTERLACE_JPEG, scheme))
	}
	fmt.Printf("Interlace: %v\n", scheme)
}
```

`GetImageInterlaceScheme()` gets the interlace format that was read from the image.

`SetInterlaceScheme()` sets the format the image should use when it is written.

**Comment by magiclen** [comment]
Hey you can change your code like this:

    func (mw *MagickWand) SetImageInterlaceScheme(interlace InterlaceType) error {
    	ok := C.MagickSetInterlaceScheme(mw.mw, C.InterlaceType(interlace))
    	return mw.getLastErrorIfFailed(ok)
    }

Instead of,

    func (mw *MagickWand) SetImageInterlaceScheme(interlace InterlaceType) error {
    	ok := C.MagickSetImageInterlaceScheme(mw.mw, C.InterlaceType(interlace))
    	return mw.getLastErrorIfFailed(ok)
    }

**Comment by justinfx** [comment]
We aren't going to be changing the public api to call different underling ImageMagick C Api. It's a binding over ImageMagick so we would want the binding to work the way the API does
