### ISSUE TITLE
How to create an imagick.AffineMatrix?

### ISSUE THREAD

**Issue by nilptr** [gographics/imagick#126]
The [document](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick) has listed type `AffineMatrix` which is used in `func (dw *DrawingWand) Affine(affine *AffineMatrix)`, but how to create it is not mentioned.

**Comment by justinfx** [comment]
Looks like an opaque pointer on the Imagick side which was never fully defined:

http://www.imagemagick.org/api/MagickCore/struct__AffineMatrix.html

There is also a related function which would reset an AffineMatrix back to the identity 

https://www.imagemagick.org/api/draw.php#GetAffineMatrix

**Comment by justinfx** [comment]
Can you check the latest commit? I've added the getter/setter api for `AffineMatrix`

**Comment by justinfx** [comment]
I've tagged this as v3.1.0 to make it available via gopkg.in

**Comment by justinfx** [comment]
Also tagged v2.4.0

**Comment by nilptr** [comment]
It works. Thank you for adding these api! :-)

**Comment by justinfx** [comment]
My pleasure!
