### ISSUE TITLE
Memory leak when working with Blobs

### ISSUE THREAD

**Issue by brainfucker** [gographics/imagick#129]
Looks like there are a memory leak inside ReadImageBlob

Here is my code, and memory constantly leaking, about 2 mb per run

```
img := imagick.NewMagickWand()
defer img.Destroy()
img.SetImageFormat("SVG")
if err := img.ReadImageBlob([]byte(svgBody)); err != nil {
	return nil, err
}
img.SetImageFormat("PNG")
pngBlob := img.GetImageBlob()
```

**Comment by justinfx** [comment]
What version of ImageMagick and Imagick are you using? I feel it's u likely
we are leaking in the bindings here because this has been looked at before
and also the binding code is minimal.

It could be related to your version of the plugin delegates. What platform
are you running?

Also, can you explain the findings you are seeing leading you to conclude
there is a leak?

**Comment by justinfx** [comment]
Also one more thing. Can you reproduce this issue using another source format other than svg? If the issues you are seeing only occur with a particular format then it would be related to the ImageMagick delegate.

**Comment by brainfucker** [comment]
I am using v2, I'll try other versions. And, yes, it's likely that problem is in svg. I'll write back more information later.

**Comment by brainfucker** [comment]
In v3 I've faced new issue, error:
'''
ERROR_FILE_OPEN: unable to open file '/tmp/magick-234E4DqzRNTn84W': No such file or directory @ error/constitute.c/ReadImage/549
'''
while code is same

**Comment by brainfucker** [comment]
After switching to v3 and to the latest version of ImageMagick – memory still leaking but about 50kb per run instead of 2mb, so problem definately in ImageMagick.

**Comment by justinfx** [comment]
I had figured as much. Thanks for doing this testing between versions. 
A quick search earlier had shown a few bugs in the ImageMagick 6.9.x range so I was hoping it would have gotten better in a newer 6.9.x or the 7.x stream.

**Comment by tynia** [comment]
@justinfx 

my program is working with ImgaeMagick 7.0.7 and the imagick is v3.
i faced the problem, did it fixed or the v3 should work with some specified version of ImageMagick?

**Comment by justinfx** [comment]
V3 bindings is for ImageMagick 7.x as stated in the README.

**Comment by bithavoc** [comment]
Solved `ERROR_FILE_OPEN: unable to open file ` by installing RSVG as @brainfucker said + `--with-xml=yes` (apt's `libxml2-dev`)
