### ISSUE TITLE
CMYK color

### ISSUE THREAD

**Issue by akzhou** [gographics/imagick#131]
How can I export image with CMYK color to printer?

`mw := imagick.NewMagickWand()
	//mw.SetResolution(300, 300)
	mw.ReadImage(`shopitem.jpg`)
	mw.SetImageResolution(300, 300)

	fi, err := os.Open(`ISOcoated_v2_300_eci.icc`)
	if err != nil {
		panic(err)
	}
	defer fi.Close()
	fd, err := ioutil.ReadAll(fi)
	mw.SetImageProfile("CMYK", fd)
	mw.WriteImage(`shopitem_cmyk_300.jpg`)`
`aks-MacBook-Air:Desktop ak$ identify -verbose /Users/ak/Desktop/test_magick/src/shopitem_cmyk_300.jpg 

Image: /Users/ak/Desktop/test_magick/src/shopitem_cmyk_300.jpg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 960x983+0+0
  Resolution: 300x300
  Print size: 3.2x3.27667
  Units: PixelsPerInch
  Type: TrueColor
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:`

**Comment by justinfx** [comment]
Have you tried using `ProfileImage()` method instead? 

The docs suggest `SetImageProfile` only sets the association but does not do any pixel transformations. 

https://www.imagemagick.org/api/profile.php#ProfileImage

**Comment by akzhou** [comment]
@justinfx  thank you! it works

**Comment by justinfx** [comment]
Yay!
