### ISSUE TITLE
request to join gographics organization 

### ISSUE THREAD

**Issue by gosp** [gographics/imagick#135]
@justinfx 
Could I join `gographics` organization to add `gmagick` repo which is for GraphicsMagick golang binding?
Because your organization name is pefect 👍 
For web server, resizing image and cropping image are frequently-used, so  GraphicsMagick is enough for many scenarios.
Pros: GraphicsMagick is less dependencies than MagicImagek. and GraphicsMagick is a little faster than MagicImagek.

### GraphicsMagick golang binding:
+ elapsed time:
```
real    0m4.198s
user    0m7.113s
sys     0m0.063s
```
+ compress ratio: 19M -> 3M

### ImageMagick7.x golang binding:
+ elapsed time:
```
real    0m5.291s
user    0m7.725s
sys     0m0.316s
```
+ compress ratio: 19M -> 8M

**Comment by justinfx** [comment]
I've added you to the organisation.

**Comment by hgfischer** [comment]
Welcome aboard :)

**Comment by gosp** [comment]
it seems I have no sufficient permission to create new repository.

**Comment by justinfx** [comment]
Oh it is not an existing repo that you want to move? What do you want the repository called? I don't do much admin on github organizations, and it looks like they make you give people complete ownership over the organization in order to create new repos. I could make it for you and try and make you the owner of it.

**Comment by gosp** [comment]
ok. I create repo in my account, you can import it: https://github.com/gosp/gmagick

**Comment by justinfx** [comment]
See if it will let you transfer it now? If not, I will convert you to an admin.

**Comment by gosp** [comment]
done. thanks.
