### ISSUE TITLE
Bad example clipmask for im-7 branch

### ISSUE THREAD

**Issue by o-shabashov** [gographics/imagick#138]
Unresolved reference - https://github.com/gographics/imagick/blob/im-7/examples/clipmask/main.go#L31

Not enough arguments - https://github.com/gographics/imagick/blob/im-7/examples/clipmask/main.go#L38

**Comment by justinfx** [comment]
Updated all the examples and added a test script via df6248d332a2a0d062782f6403bc87058f9882fc
