### ISSUE TITLE
roundCorners

### ISSUE THREAD

**Issue by akzhou** [gographics/imagick#142]
Is there any method to set the image corners? like roundCornersImage in php

**Comment by justinfx** [comment]
Can you follow along with this C# example from someone who asked the same question on the ImageMagick forum? The API calls should be available. 

http://www.imagemagick.org/discourse-server/viewtopic.php?t=32092

**Comment by akzhou** [comment]
@justinfx  at last,I use RoundRectangle method to make a round corner.thanks
