### ISSUE TITLE
ERROR_MISSING_DELEGATE starting on second processing run

### ISSUE THREAD

**Issue by huehnerhose** [gographics/imagick#144]
Hi,

I need some help, I try to fetch several PDF files from a postgres database (largeobjects) and processing them using gographics/imagick

I have all (o)ids from these largeobjects in a slice, looping over it, reading the large object and handing it over to imagemagick. The processing function looks like this:

    func PreprocessPDF(blob []byte) ([]byte, error) {
  	  imagick.Initialize()
  	  defer imagick.Terminate()

  	  mw := imagick.NewMagickWand()
  	  defer mw.Destroy()

  	  err := mw.ReadImageBlob(blob)
  	  if err != nil {
  		  return nil, err
  	  }

      // PROCESSING

  	  image := mw.GetImageBlob()
  	  return image, nil
    }

the second time this function gets called `mw.ReadImageBlob(blob)` throws 

    ERROR_MISSING_DELEGATE: no decode delegate for this image format `PDF' @ error/blob.c/BlobToImage/450

The error gets thrown for every run _after_ the first one. Independently of which actual file gets processed. It also gets thrown when i try to process the same image twice.

I expect to make some kind of stupid error where somehow the second time I rewrite over allready allocated memory or something like this. But I didn't found anything :( (Hopefully I am just blind)

Thanks!

**Comment by justinfx** [comment]
Don't initialize and terminate on every function call. ImageMagick C API expects it to be set up once and usually you tear it down at the end of your program or when the ImageMagick support is really no longer needed. You wouldn't want to do it during normal program operation when different goroutines are using it.

Just move it to a main or init

**Comment by huehnerhose** [comment]
Thanks! That totally solved it for me. Maybe you could mention this in the basic examples in the README?

**Comment by justinfx** [comment]
Sure we could add it as an example with a comment. Seems it catches enough people out since not everyone reads the ImageMagick C API docs
