### ISSUE TITLE
Resize image while maintaining aspect ratio?

### ISSUE THREAD

**Issue by MattJBrowning** [gographics/imagick#145]
Hello, was wondering how I would resize an image for a thumbnail while maintaining the aspect ratio of the original image.
```
mw := imagick.NewMagickWand()
	defer mw.Destroy()

	buffer := streamToByte(resp.Body)
	err = mw.ReadImageBlob(buffer)
	if err != nil {
		log.Println(err)
	}

	width := mw.GetImageWidth()
	height := mw.GetImageHeight()

	newWidth := uint(400 * (width / height))
	newHeight := uint(400 * (height / width))

	err = mw.ThumbnailImage(newWidth, newHeight)
	if err != nil {
		log.Println(err)
	}

	err = mw.SetImageCompressionQuality(90)
	if err != nil {
		log.Println(err)
	}

	err = mw.SetFormat("jpeg")
	if err != nil {
		log.Println(err)
	}

	img := bytes.NewReader(mw.GetImageBlob())
```

That's what I have currently, not sure if there is a way to do it without having to do the math for the image size or not. If anyone can help that'd be great.
Thanks

**Comment by justinfx** [comment]
Unfortunately you do have to do the maths yourself. But your example doesn't seem to be preserving the aspect right now. You are just multiplying two fixed dimensions by the same number. It should involve either picking a fixed value for one dimension and scaling the other, or finding a new fit size for another rectangle. 

Here is an example from someone asking about the C API:
http://www.imagemagick.org/discourse-server/viewtopic.php?t=29725

**Comment by MattJBrowning** [comment]
Oh okay, that makes sense. Thanks for the help!
