### ISSUE TITLE
how can I covert image format from png to jpeg  with white background color

### ISSUE THREAD

**Issue by akzhou** [gographics/imagick#149]
how can I covert image format from png to jpeg  with white background color?
`
blob := []byte{}
ctxFormat := imagick.NewMagickWand()
defer ctxFormat.Destroy()
ctxFormat.ReadImage(saveOriginalPath)
blob = ctxFormat.GetImageBlob()

ctxFormat2 := imagick.NewMagickWand()
defer ctxFormat2.Destroy()
ctxFormat2.ReadImageBlob(blob)

ctxFormat2.SetImageFormat("jpeg")
ctxFormat2.SetImageBackgroundColor(color("white"))
ctxFormat2.SetBackgroundColor(color("white"))

jpegPath := distPath + pathSep + saveOriginalName + ".jpeg"
if err := ctxFormat2.WriteImage(jpegPath); err != nil {
	l4g.Error("save jpeg  error:", err.Error())
	panic(err)
}
`

**Comment by justinfx** [comment]
You can use compositing operators:

```go
func main() {
	in := imagick.NewMagickWand()
	in.ReadImage(`source.png`)

	bg := imagick.NewPixelWand()
	bg.SetColor("red")

	out := imagick.NewMagickWand()
	err := out.NewImage(in.GetImageWidth(), in.GetImageHeight(), bg)
	if err != nil {
		panic(err)
	}

	out.CompositeImage(in, imagick.COMPOSITE_OP_OVER, false, 0, 0)

	if err := out.WriteImage(`out.jpg`); err != nil {
		panic(err)
	}
}
```

**Comment by akzhou** [comment]
@justinfx  thank you !!!
