### ISSUE TITLE
seg fault when working with pngs in docker image golang:1.9-alpine

### ISSUE THREAD

**Issue by jsaterfiel** [gographics/imagick#150]
Locally my code with imagemagick 7.0.7-7 with my go code but when I put it into golang:1.9-alpine jpeg work file but png always cause a seg fault when i try to read a png image blob ReadImageBlob.  Could this be due to the fact that the imagemagick alpine package is compiled without threads but the version I have on my comp is compiled with threads.

alpine 3.6 imagemagick version: 7.0.5.10-r0
https://git.alpinelinux.org/cgit/aports/tree/main/imagemagick/APKBUILD?h=3.6-stable

When I manually run the convert app on the png files it works fine.

I also tried building alpine edge which has 7.0.7 (also without threads) but the same issue occurs.

code:
https://github.com/jsaterfiel/go-imagick

I'm really stuck on this problem and I'm not sure how to proceed now.

Any suggestions on how to go about resolving the issue would be welcomed!

**Comment by justinfx** [comment]
Is this similar to others having issues running within the Alpine image (see #118 and #130)? Is it compiling with musl? Could it be your version of libpng? Does it work in a larger image like Ubuntu?

It would be ideal to narrow the problem down to a small repro program and confirm if it's only happening in one particular docker image configuration.

**Comment by jsaterfiel** [comment]
It is built with musl as all the imagemagicks for alpine are.  I will try to build an ubuntu container to run the program in there.

By running ```identify -list format```

On my homebrew imagemagick version 7.0.7 which works perfectly fine with png files in my program, I had these values for jpeg and png:
JPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (90)
PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.32,1.6.34)

In the alpine container which is running alpine edge also with imagick 7.0.7 I found:
JPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (80)
PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.34)

**Comment by jsaterfiel** [comment]
When I turn on imagemagick's debug I get these two logs from when it crashes and when it works in the container (it's not often this occurs).

2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadPNGImage/4200/Coder
  Enter ReadPNGImage()
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/2237/Coder
    Enter ReadOnePNGImage()
    IM version     = 7.0.7-11
    Libpng version = 1.6.34
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/2250/Coder
      Zlib version   = 1.2.11
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/2282/Coder
      Before reading:
      image->alpha_trait=0
      image->rendering_intent=2
      image->colorspace=23
      image->gamma=0.454545
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/2583/Coder
      PNG width: 1280, height: 720
    PNG color_type: 6, bit_depth: 8
    PNG compression_method: 0
    PNG interlace_method: 0, filter_method: 0
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/2607/Coder
      Found PNG gAMA chunk.
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/2785/Coder
      Reading PNG gAMA chunk: gamma: 0.555550
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/2904/Coder
      Reading PNG pHYs chunk: xres: 2835, yres: 2835, units: 1.
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/3173/Coder
      image->gamma=0.555550
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/3199/Coder
      image->colorspace=23
2017-11-29T11:43:06+00:00 0:00.170 0.090u 7.0.7 Coder main[38]: png.c/ReadOnePNGImage/3353/Coder
      Reading PNG IDAT chunk(s)
      
      
      
      
      
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadPNGImage/4200/Coder
  Enter ReadPNGImage()
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/2237/Coder
    Enter ReadOnePNGImage()
    IM version     = 7.0.7-11
    Libpng version = 1.6.34
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/2250/Coder
      Zlib version   = 1.2.11
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/2282/Coder
      Before reading:
      image->alpha_trait=0
      image->rendering_intent=2
      image->colorspace=23
      image->gamma=0.454545
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/2583/Coder
      PNG width: 1280, height: 720
    PNG color_type: 6, bit_depth: 8
    PNG compression_method: 0
    PNG interlace_method: 0, filter_method: 0
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/2607/Coder
      Found PNG gAMA chunk.
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/2785/Coder
      Reading PNG gAMA chunk: gamma: 0.555550
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/2904/Coder
      Reading PNG pHYs chunk: xres: 2835, yres: 2835, units: 1.
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/3173/Coder
      image->gamma=0.555550
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/3199/Coder
      image->colorspace=23
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Coder main[44]: png.c/ReadOnePNGImage/3353/Coder
      Reading PNG IDAT chunk(s)
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Resource main[44]: resource.c/AcquireMagickResource/386/Resource
  Width: 1280P/1280P/107.374MP
2017-11-29T11:44:22+00:00 0:00.350 0.080u 7.0.7 Resource main[44]: resource.c/AcquireMagickResource/386/Resource
  Height: 720P/720P/107.374MP

The part it seems to be dying on is on ```Resource main[44]: resource.c/AcquireMagickResource/386/Resource``` perhaps this is is just a pointer issue with the musl builds?

**Comment by justinfx** [comment]
Ya, because this is the second time I have seen someone hit this situation, it may be a question for the Go community about any known issues compiling cgo programs with musl.

**Comment by jsaterfiel** [comment]
Does this help at all?  I set the go build to verbose.  I see some differences in what is being linked which may point to the issue?

Desktop (working):
```
/go/src/app # go build -ldflags '-v' main.go
# command-line-arguments
HEADER = -H1 -T0x1001000 -D0x0 -R0x1000
searching for runtime.a in $WORK/runtime.a
searching for runtime.a in /Users/saterfij/go/pkg/darwin_amd64/runtime.a
searching for runtime.a in /usr/local/go/pkg/darwin_amd64/runtime.a
 0.00 deadcode
 0.03 pclntab=1142718 bytes, funcdata total 317820 bytes
 0.03 dodata
 0.04 symsize = 0
 0.04 symsize = 0
 0.04 reloc
 0.05 dwarf
 0.07 symsize = 0
 0.13 reloc
 0.14 asmb
 0.14 codeblk
 0.14 datblk
 0.15 sym
 0.16 headr
 0.18 host link: "clang" "-m64" "-gdwarf-2" "-Wl,-headerpad,1144" "-Wl,-no_pie" "-Wl,-pagezero_size,4000000" "-o" "/var/folders/66/gw0r_xn11719x30yk49jtm5r0000gn/T/go-build819292665/command-line-arguments/_obj/exe/a.out" "-Qunused-arguments" "/var/folders/66/gw0r_xn11719x30yk49jtm5r0000gn/T/go-link-615196293/go.o" "/var/folders/66/gw0r_xn11719x30yk49jtm5r0000gn/T/go-link-615196293/000000.o" "/var/folders/66/gw0r_xn11719x30yk49jtm5r0000gn/T/go-link-615196293/000001.o" "/var/folders/66/gw0r_xn11719x30yk49jtm5r0000gn/T/go-link-615196293/000002.o" "/var/folders/66/gw0r_xn11719x30yk49jtm5r0000gn/T/go-link-615196293/000003.o" "-g" "-O2" "-L/usr/local/Cellar/imagemagick/7.0.7-7/lib" "-lMagickWand-7.Q16HDRI" "-lMagickCore-7.Q16HDRI" "-g" "-O2" "-g" "-O2" "-framework" "CoreFoundation" "-framework" "Security" "-g" "-O2" "-lpthread"
 0.72 cpu time
129464 symbols
239812 liveness data
```

Inside of go alpine container:
```
/go/src/app # go build -ldflags '-v' main.go
# command-line-arguments
HEADER = -H4 -T0x401000 -D0x0 -R0x1000
searching for runtime.a in $WORK/runtime.a
searching for runtime.a in /go/pkg/linux_amd64/runtime.a
searching for runtime.a in /usr/local/go/pkg/linux_amd64/runtime.a
 0.00 deadcode
 0.03 pclntab=1190315 bytes, funcdata total 402898 bytes
 0.04 dodata
 0.05 dwarf
 0.06 symsize = 0
 0.09 reloc
 0.11 asmb
 0.11 codeblk
 0.23 datblk
 0.26 sym
 0.27 symsize = 221256
 0.28 symsize = 235224
 0.28 dwarf
 0.39 headr
 0.45 host link: "gcc" "-m64" "-gdwarf-2" "-o" "/tmp/go-build183967037/command-line-arguments/_obj/exe/a.out" "-rdynamic" "/tmp/go-link-084763590/go.o" "/tmp/go-link-084763590/000000.o" "/tmp/go-link-084763590/000001.o" "/tmp/go-link-084763590/000002.o" "-g" "-O2" "-lMagickWand-7.Q16HDRI" "-lMagickCore-7.Q16HDRI" "-g" "-O2" "-g" "-O2" "-lpthread" "-no-pie" "-fno-PIC"
 0.64 cpu time
145720 symbols
323520 liveness data
```

I see the container musl version is using gcc but the desktop one is using clang.  I did read something about musl and c++ but unsure if this is still applicable.

http://dominik.honnef.co/posts/2015/06/go-musl/
```
Another drawback is that while musl supports C++, it doesn’t so as easily as with C. We can’t just use the musl-gcc wrapper, but instead would need to build a libstdc++ with musl. It’s doable, but outside the scope of this article. Unfortunately, the lack of easy C++ support also means that we can’t use Go’s race detector with musl, as it is written in C++.
```

**Comment by justinfx** [comment]
Yea I am sorry, but I don't have any experience compiling with musl or using the alpine image with cgo. You seem to have more information than I do at this point :-/
It makes perfect sense that you would end up with clang by default on OSX, but a different compiler (gcc in this instance) under a linux-based container. This project issue tracker is probably not going to be the best resource for getting more insight into this problem, unless @bweston92 or @ssttevee from the other issues have an updated info.

**Comment by jackluo2012** [comment]
FROM golang

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends libwebp-dev libjpeg-dev libpng-dev wget freetype2-demos libfreetype6-dev libfreetype6

RUN wget https://www.imagemagick.org/download/ImageMagick.tar.gz && \
    tar xvzf ImageMagick.tar.gz && \
    rm ImageMagick.tar.gz && \
    cd ImageMagick-7.0.7-12 && \
    ./configure && \
    make -j4 && \
    make install && \
    ldconfig /usr/local/lib && \
    cd .. && rm -rf ImageMagick-7.0.7-12

**Comment by jsaterfiel** [comment]
Yes that worked for me perfectly!

Here's my final dockerfiles in case somebody else runs into this issue as well.  I split it into two images so I don't have to recompile imagemagick every rebuild.

docker file to build the base image from above with imagemagick:
```
FROM golang

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends libwebp-dev libjpeg-dev libpng-dev wget freetype2-demos libfreetype6-dev libfreetype6

RUN wget https://www.imagemagick.org/download/ImageMagick.tar.gz \
    && tar xvzf ImageMagick.tar.gz \
    && rm ImageMagick.tar.gz \
    && cd ImageMagick-7.0.7-12 \
    && ./configure \
    && make -j4 \
    && make install \
    && ldconfig /usr/local/lib \
    && cd .. \
    && rm -rf ImageMagick-7.0.7-12
```

The project dockerfile:
```
FROM go-image-base

WORKDIR /go/src/app
COPY . .

RUN go-wrapper download   # "go get -d -v ./..."
RUN go-wrapper install    # "go install -v ./..."

RUN go build main.go

CMD ["/bin/sh", "/go/src/app/main"]
```
