### ISSUE TITLE
imagick.v2: could not determine kind of name for C.HeightResource

### ISSUE THREAD

**Issue by wwarner** [gographics/imagick#152]
```
# apt-get update && apt-get install -y libmagickwand-dev
# pkg-config --cflags --libs MagickWand
-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -lMagickWand-6.Q16 -lMagickCore-6.Q16
# go get gopkg.in/gographics/imagick.v2/imagick
# gopkg.in/gographics/imagick.v2/imagick
could not determine kind of name for C.HeightResource
could not determine kind of name for C.WidthResource
```
This has been working for me for about a year. Any guidance on how to repair it?

I'm running all this in a docker container based from `golang:1.7`, so it's debian based.

**Comment by justinfx** [comment]
Can you tell me the version of ImageMagick that you are picking up?

`identify -version`

It's possible you are using either too old of a 6.x, or a newer patch that contains breaking changes to the v2 bindings

**Comment by wwarner** [comment]
```
# identify -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-07-15 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
```

**Comment by wwarner** [comment]
Well, I changed the order of `go get`s in my Dockerfile, and that seems to have fixed the problem.

This caused the compilation failure
```
RUN go get github.com/pilu/fresh

RUN apt-get update && apt-get install -y libmagickwand-dev
RUN pkg-config --cflags --libs MagickWand
RUN go get gopkg.in/gographics/imagick.v2/imagick # FAIL
```

Moving `pilu/fresh` after successfully installing `imagick.v2` doesn't error out

Closing.

**Comment by justinfx** [comment]
I don't understand the correlation with the order in which that other package is installed, but I am glad to hear your problem is resolved.

**Comment by wwarner** [comment]
I think if I deleted the docker image, it fail again. By adding the docker command after the successful install, the build reuses the image created earlier, then runs the new command on that image.

**Comment by wwarner** [comment]
@justinfx I was able to fix this issue by changing the base image in my Dockerfile from `FROM golang:1.7` to `FROM golang:1.9.3`. `1.7.4` and `1.7.6` failed with the same error.

This Dockerfile will generate the error.

```
FROM golang:1.7

RUN apt-get update && apt-get install -y libmagickwand-dev
RUN pkg-config --cflags --libs MagickWand
RUN go get gopkg.in/gographics/imagick.v2/imagick
```

**Comment by justinfx** [comment]
Cool. Then just make sure to use the latest releases of Go.

**Comment by wwarner** [comment]
Well, it's a bit more than the latest Go. It's the latest base image provided by the Go team. It's all built on Debian stretch.

**Comment by wwarner** [comment]
Without Docker, you can produce the error with Go 1.9.3 and and libmagickwand-dev 8:6.8.9.9-7ubuntu5.9

**Comment by justinfx** [comment]
Ok I think I got it now. Those two symbols were actually not introduced until ImageMagick 6.9.0-2, but we advertise that the v2 bindings support  6.8.9-9 through 6.9.6-2. We should update the README to the following:

```
master (tag v2.x.x): 6.9.0-2 <= ImageMagick <= 6.9.6-2
im-7   (tag v3.x.x): 7.x     <= ImageMagick <= 7.x
legacy (tag v1.x.x): 6.7.x   <= ImageMagick <= 6.8.9-10
```

Can you try building against "gopkg.in/gographics/imagick.v1/imagick"? You will see a couple deprecation warnings, but the tests pass.

**Comment by wwarner** [comment]
Worked exactly as you described, thanks for your help!

**Comment by justinfx** [comment]
Thanks for hanging in there and finding a simple reproduction!
