### ISSUE TITLE
Question: Passing command line options to imagemagick

### ISSUE THREAD

**Issue by jbeil** [gographics/imagick#153]
Hi, how can I pass command line options to imagemagick from go?

**Comment by justinfx** [comment]
I don't fully understand what you mean by this. What command line options are you trying to pass to ImageMagick? This is an API and not the "convert" command that comes with ImageMagick. Anything you want to do has to be expressed through API calls.

**Comment by justinfx** [comment]
No movement on this issue. Closing it. Let me know if you still have questions.
