### ISSUE TITLE
Problems building multi stage docker container with library dependencies

### ISSUE THREAD

**Issue by mattisx** [gographics/imagick#156]
I feel a bit douchy to post this here, but I've spent the last 8 hours banging my head against this to no avail. I am trying to build my imagemagick dependant go app docker container in stages, but I'm stuck at this point:

```
Step 10/17 : RUN pkg-config --cflags --libs MagickWand
 ---> Running in 0c3fa8089d49
-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -lMagickWand-6.Q16 -lMagickCore-6.Q16
Removing intermediate container 0c3fa8089d49
 ---> 02e355d0dc64
Step 11/17 : RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./src
 ---> Running in 6b09396484ce
# app/src
src/handlers.go:32:2: undefined: imagick.Initialize
src/handlers.go:33:8: undefined: imagick.Terminate
src/handlers.go:35:8: undefined: imagick.NewMagickWand
src/handlers.go:48:44: undefined: imagick.FILTER_LANCZOS
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./src' returned a non-zero code: 2
```

The Dockerfile looks like this:
```
FROM golang:1.10.0-stretch AS builder
RUN apt-get update && \
    apt-get install -y libmagickwand-dev --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
RUN go get github.com/golang/dep/cmd/dep
WORKDIR /go/src/app
ADD Gopkg.toml Gopkg.toml
ADD Gopkg.lock Gopkg.lock
RUN dep ensure --vendor-only
ADD .env .env
ADD src src
RUN pkg-config --cflags --libs MagickWand
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./src

FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
#RUN apk add --no-cache imagemagick && \
#    apk add --no-cache imagemagick-dev && \
#    rm -rf /var/lib/apt/lists/*

WORKDIR /root
COPY --from=builder /go/src/app/main .
COPY --from=builder /go/src/app/.env .
CMD ["./main"]
```
I've checked it in stages and everything is well with `pkg-config --cflags --libs MagickWand` and the other gotchas. I've read a lot about LDFLAGS and static and dynamic linking but I just can't get my head around it. 

(If I use CGO_ENABLED=1, everything builds fine, but then I can't run the built file inside the container environment.)

Would appreciate any input.

**Comment by justinfx** [comment]
imagick is a cgo binding around the C ImageMagick library. It would be impossible to use `CGO_ENABLED-0` because you would end up without the ability to create the calls into C. So stick with leaving that out.

The focus should be on why you can't run your binary after it is built. I don't have any personal experience building imagick applications in docker images, but my experience has been from seeing other people post issues on this project. It always seems like problems arise when minimal docker base images are used, such as those that end up using the musl compiler. It would be great to confirm that you can build a working container first from something beefier like an ubuntu image. Once that is working you can try reducing it. 
But once you build your binary, you need to make sure ImageMagick is still installed in the final container. Your program is going to need to dynamically link to it when it runs. So if you build it in one container and them copy the binary to another container, and you leave out the ImageMagick dependency, then it won't run.

**Comment by mattisx** [comment]
Thanks for your reply @justinfx, just your answer about CGO_ENABLED limited my potential options down a lot - appreciated!

When I do CGO_ENABLED=1 and build it with alpine, this is the result:

```
Mattis:image-service mattis$ docker run --rm -it -p 8080:8080 image-service-prod
~ # ls
main
~ # ./main
/bin/sh: ./main: not found
```
It does work when I run it on `ubuntu:latest`, just as you suspected. The container image is over 10 times larger though. Would be nice to get it really slim.

**Comment by justinfx** [comment]
But why is the `./main` not found? It obviously failed to build along the way, and what was the reason?

**Comment by mattisx** [comment]
@justinfx With a fresh head I've looked at it again. Summary (and solution?):

My go app uses imagick and I need to run with CGO_ENABLED=1 for the compilation to succeed. The resulting binary could not be executed on the alpine image. There are a bunch of issues and posts around it (a search for "cgo alpine" shows you most of it).

I had limited success with an "empty" go app and running:
`RUN CGO_ENABLED=1 GOOS=linux go build -tags /app/vendor/gopkg.in/gographics/imagick.v2/imagick -a -v -installsuffix cgo -o main ./src`
which ran fine on alpine - but when I added my imagick dependencies to the go code it failed again.

I realised the issue probably was related to me building in one environment and running in a different one (alpine use /lib, not /lib64 for example).

I decided to use the new `golang:1.10.0-alpine3.7` image as the build environment, adding what it needed to manage the build. Et voilà, there we go.

Working Dockerfile here:

```
FROM golang:1.10.0-alpine3.7 AS builder
RUN apk update && \
    apk add --no-cache build-base && \
    apk add --no-cache imagemagick-dev && \
    apk add --no-cache git && \
    rm -rf /var/lib/apt/lists/*
RUN go get github.com/golang/dep/cmd/dep
WORKDIR /go/src/app
ADD Gopkg.toml Gopkg.toml
ADD Gopkg.lock Gopkg.lock
RUN dep ensure --vendor-only
ADD .env .env
ADD src src
RUN CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o main ./src

FROM alpine:3.7
RUN apk update && apk add ca-certificates && \
    rm -rf /var/cache/apk/*
RUN apk add --no-cache imagemagick-dev && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /root
COPY --from=builder /go/src/app/main .
COPY --from=builder /go/src/app/.env .
CMD ["./main"]
```

The result: A 20 MB container with ImageMagick support :)

**Comment by justinfx** [comment]
Nice. Glad you got it working. I will refer people to this ticket if they have issues again with alpine docker images.

**Comment by aclowkey** [comment]
@justinfx  @mattisx Which version of of imagick did you use? I tried using v2 but then I get:

> \#gopkg.in/gographics/imagick.v2/imagick
> src/gopkg.in/gographics/imagick.v2/imagick/affine_matrix.go:8:29: fatal error: wand/MagickWand.h: No such file or directory
>  #include <wand/MagickWand.h>
>                              ^
> compilation terminated.
> 

When I try to use v3, I get the app compiled and running, but when I try to convert an image I get: 
`ERROR_MISSING_DELEGATE: NoDecodeDelegateForThisImageFormat `PNG' `

**Comment by justinfx** [comment]
@aclowkey please make sure to consult the README for this project. V2 is for ImageMagick6 and V3 is for ImageMagick7. Sounds like you got past that issue now.

The delegate problem is from a lack of libpng and/or other plugin dependencies.

As for the docker image size, note in the example that there is a builder stage and a run stage. The builder stage is used to download and build the binary. It is then discarded and only the run stage is kept in the docker image. In your example I think you just built and run the binary in the same image, so you are keeping around the ImageMagick sources.

**Comment by mattisx** [comment]
@aclowkey I actually thought that it worked, but once I dove into deeper it didn't. I ended up running a 4-500 MB container to get all the functionality we needed. My proposed solution above does not work, but it's probably due to my own limited abilities.
