### ISSUE TITLE
Processing time slowy increase

### ISSUE THREAD

**Issue by huhr** [gographics/imagick#163]
Our program is a HTTP Server, When I first start server, the average processing time for each request is about 700ms, as runing on, the average processing time climb to seconds or even more. 

I have use perf tool to analysis process and find out that when server has running after hours，cpu spend lots of time on "DeleteNodeByValueFromSplayTree" and "SplaySplayTree", which appear at create and destroy wands, it seems that imagick splay-tree has grow too huge,  but I reviewed my program and didn`t any wands that forget to destroy.

Is there any method helping debug, my imagick version is 6.9.0-0

**Comment by justinfx** [comment]
If you set `MAGICK_DEBUG=Trace` in your environment before starting the application then you should get debug information out of ImageMagick. What does your pattern look like for creating and destroying wands? Even if you forgot to delete manually, as long as you aren't holding onto instances the garbage collector should end up running the finalizers on the objects eventually.

**Comment by huhr** [comment]
Thank you for quick replay！
Normally，all imagick objects can be collected by gc after  function done，i have use serval methods related to wands creation.

```
New* constructors
magickWand.Clone()
pixelIterator.GetNextIteratorRow()
```
But find I havn`t wands that without destroy

**Comment by aclowkey** [comment]
@justinfx I'm also experiencing this. I've set up a JMeter test of 10 threads, each sends the same image 100 times to be resized. It takes few seconds to finish the first 800~ requests, then there are only 3 threads  and the last 200 requests take several minutes.

**Comment by justinfx** [comment]
@aclowkey I am pretty positive it isn't the http server unless you are doing more in your request handlers than just resizing and writing images. It's going to be somewhere in ImageMagick C api most likely, in combination with how the bindings are being used to access it. Does it slow down when there are only 2-4 workers? I will have to give this a test when I have time

**Comment by aclowkey** [comment]
@justinfx It's werid, I'm not even sure all of those 800 requests were actually processed.
Running with 2 workers doesn't seem to change much. Also starts quickly and goes slowly but not as quickly as with 10.  Average time increased drastically

**Comment by huhr** [comment]
I have solved my problem by upgrading ImageMagick to version 6.9.9 without any modification of my code.

**Comment by justinfx** [comment]
That is really great news! @aclowkey is your related issue fixed on a newer ImageMagick version?
