### ISSUE TITLE
signal: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wjzhangcsu** [gographics/imagick#168]
"gopkg.in/gographics/imagick.v3/imagick"
(1/2) Installing imagemagick-c++ (7.0.5.10-r0)
(2/2) Installing imagemagick-dev (7.0.5.10-r0)

Goroutines

go func(){
     fmt.Println("start...")
     ConvertPdfToJpg(pdfPath, "jpg")
     fmt.Println("end...")
  }()

result:signal: segmentation fault (core dumped)

**Comment by justinfx** [comment]
Does this mean you are using docker with alpine? Do you have any imagick code that you can show?
Does it crash when you are not using goroutines?

**Comment by wjzhangcsu** [comment]
My imagick code:
func ConvertPdfToJpg(pdfTmpPath string, imageFormat string) error {
  // Setup
  imagick.Initialize()
  defer imagick.Terminate()

  mw := imagick.NewMagickWand()
  defer mw.Destroy()

  // Must be *before* ReadImageFile
  // Make sure our image is high quality
  if err := mw.SetResolution(200, 200); err != nil {
    return err
  }

  // Load the image file into imagick
  if err := mw.ReadImage(pdfTmpPath); err != nil {
    return err
  }

  // Must be *after* ReadImageFile
  // Flatten image and remove alpha channel, to prevent alpha turning black in jpg
  if err := mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_OFF); err != nil {
    return err
  }

  // Set any compression (100 = max quality)
  //if err := mw.SetCompressionQuality(95); err != nil {
  //  return err
  //}

  pageCount := int(mw.GetNumberImages())
  for i := 1; i <= pageCount; i++ {
    // Select the page of pdf
    mw.SetIteratorIndex(i - 1)

    // Convert into imageFormat
    if err := mw.SetFormat(imageFormat); err != nil {
      return err
    }

    // Save file
    imageTmpFilePath := fmt.Sprintf("%s_%d.%s", pdfTmpPath, i, imageFormat)
    if err := mw.WriteImage(imageTmpFilePath); err != nil {
      return err
    }
  }

  return nil
}

**Comment by wjzhangcsu** [comment]
My imagick code:
```
func ConvertPdfToJpg(pdfTmpPath string, imageFormat string) error {
  // Setup
  imagick.Initialize()
  defer imagick.Terminate()

  mw := imagick.NewMagickWand()
  defer mw.Destroy()

  // Must be *before* ReadImageFile
  // Make sure our image is high quality
  if err := mw.SetResolution(200, 200); err != nil {
    return err
  }

  // Load the image file into imagick
  if err := mw.ReadImage(pdfTmpPath); err != nil {
    return err
  }

  // Must be *after* ReadImageFile
  // Flatten image and remove alpha channel, to prevent alpha turning black in jpg
  if err := mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_OFF); err != nil {
    return err
  }

  // Set any compression (100 = max quality)
  //if err := mw.SetCompressionQuality(95); err != nil {
  //  return err
  //}

  pageCount := int(mw.GetNumberImages())
  for i := 1; i <= pageCount; i++ {
    // Select the page of pdf
    mw.SetIteratorIndex(i - 1)

    // Convert into imageFormat
    if err := mw.SetFormat(imageFormat); err != nil {
      return err
    }

    // Save file
    imageTmpFilePath := fmt.Sprintf("%s_%d.%s", pdfTmpPath, i, imageFormat)
    if err := mw.WriteImage(imageTmpFilePath); err != nil {
      return err
    }
  }

  return nil
}

```

**Comment by justinfx** [comment]
Thank you for the details about the problem.

This is why you are crashing:
```
  // Setup
  imagick.Initialize()
  defer imagick.Terminate()
```

Just like in the ImageMagick C API, initializing should be done once for the whole program and terminated at the end (or as long as you need ImageMagick resources). Your goroutines are racing each other to setup and tear down the global ImageMagick state. Move that out and you will most likely stop crashing.

**Comment by wjzhangcsu** [comment]
This does not seem to be the focus. I only request once,but it can not work too. I already attempted to   Move that out ,and it still crashed.

**Comment by justinfx** [comment]
I'm surprised to hear that it crashed with only a single call to that function, and the only factor that makes it crash is whether it is called as a goroutine or not. Do you know which line the segfault is occurring in the code?

**Comment by wjzhangcsu** [comment]
I'm also surprised to find this problem . The segfault is occurring in the codes:
```
  // Load the image file into imagick
  if err := mw.ReadImage(pdfTmpPath); err != nil {
    return err
  }
```

**Comment by wjzhangcsu** [comment]
My Dockerfile:
```

FROM bradobro/golang-alpine-dep 

ENV DUMB_INIT_VERSION=1.2.0
ENV DEBIAN_FRONTEND=noninteractive
ENV SU_EXEC_VERSION=0.2

RUN apk update \
 && apk upgrade \
 && apk add --no-cache \
        ca-certificates \
        ruby ruby-irb \
        su-exec==${SU_EXEC_VERSION}-r0 \
        dumb-init==${DUMB_INIT_VERSION}-r0 \
 && apk add --no-cache --virtual .build-deps \
        build-base \
        ruby-dev wget gnupg \
 && apk add --no-cache ghostscript \
 && apk add --no-cache imagemagick \
 && apk add --no-cache imagemagick-dev

```

**Comment by justinfx** [comment]
Do you build your go binary against this within the alpine image? Users have reported issues in the past that have led to problems with alpine and the musl compiler. Then they switch to some light version of ubuntu and it works.

Again, I can't understand how one single call to your conversion code crashes if its in a goroutine but not if it is called inline. Do you have more examples of how your problem looks when it is waiting for the goroutine?

**Comment by wjzhangcsu** [comment]
yes,I build my go binary against this within the alpine image. Also, I switch to some lversion of ubuntu and it works. I have no more examples,but you can build the docker image and try the code.Then, you can  
recurrent this problem.
This is my whole code:
```
package main

import (
  log "github.com/sirupsen/logrus"
  "gopkg.in/gographics/imagick.v3/imagick"
  "fmt"
)

func main() {
  pdfPath := "./small.pdf"

  go func(){
     fmt.Println("start...")
     //convertPDFToImage(pdfPath, "jpg")
     ConvertPdfToJpg(pdfPath, "jpg")
     fmt.Println("end...")
  }() 
  var a int
  fmt.Scan(&a)
}

func ConvertPdfToJpg(pdfTmpPath string, imageFormat string) error {
  // Setup
  imagick.Initialize()
  defer imagick.Terminate()

  mw := imagick.NewMagickWand()
  defer mw.Destroy()

  // Must be *before* ReadImageFile
  // Make sure our image is high quality
  if err := mw.SetResolution(200, 200); err != nil {
    return err
  }

  // Load the image file into imagick
  if err := mw.ReadImage(pdfTmpPath); err != nil {
    return err
  }

  // Must be *after* ReadImageFile
  // Flatten image and remove alpha channel, to prevent alpha turning black in jpg
  if err := mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_OFF); err != nil {
    return err
  }

  // Set any compression (100 = max quality)
  //if err := mw.SetCompressionQuality(95); err != nil {
  //  return err
  //}

  pageCount := int(mw.GetNumberImages())
  for i := 1; i <= pageCount; i++ {
    // Select the page of pdf
    mw.SetIteratorIndex(i - 1)

    // Convert into imageFormat
    if err := mw.SetFormat(imageFormat); err != nil {
      return err
    }

    // Save file
    imageTmpFilePath := fmt.Sprintf("%s_%d.%s", pdfTmpPath, i, imageFormat)
    if err := mw.WriteImage(imageTmpFilePath); err != nil {
      return err
    }
  }

  return nil
}

```
This is the PDF [small.pdf](https://github.com/gographics/imagick/files/2230376/small.pdf)

**Comment by wjzhangcsu** [comment]
@justinfx  Thank you for your help again!

**Comment by justinfx** [comment]
Thanks. Well if it works under a different image, then I am not going to spend any time looking into this. It sounds like another problem using the musl compiler on alpine docker images, which is hit and miss with C libraries. I think maybe musl isn't good to use with ImageMagick C api at this point.
