### ISSUE TITLE
Add a docker example, such as dockerfile or image

### ISSUE THREAD

**Issue by penhauer-xiao** [gographics/imagick#173]
To add docker examples, such as dockerfile or image, in different versions.

**Comment by justinfx** [comment]
Are you looking for a Go builder image that apt installs ImageMagick?

**Comment by penhauer-xiao** [comment]
@justinfx like this: https://gist.github.com/namsoila/fcdbc8c8ee28b7250e59afc260a8a593
Just this is too simple, not all functional tests, such as fonts have problems, and then put in docker

**Comment by justinfx** [comment]
Ok well if you have an idea of what you are after, please submit a merge
request.

Thanks!

**Comment by justinfx** [comment]
In #174 I have an example for imagick.v2
If this is what you are after, I also have a variant ready to push for imagick.v3

**Comment by justinfx** [comment]
imagick.v3 variation available via #175

**Comment by justinfx** [comment]
These have been merged.
