### ISSUE TITLE
how to pass MagickWand reference to functions and apply methods? 

### ISSUE THREAD

**Issue by byanjiong** [gographics/imagick#176]
May I know how to pass `imagick.MagickWand` struct to functions and apply methods on it?

I can't get it done, keep getting the error message: `ERROR_WAND: ContainsNoImages 'MagickWand-0'.`

```go
func generateImage() error {
    // skip error handling
    var err error 

    mw := imagick.NewMagickWand()
    defer mw.Destroy()

    err = createCanvas(mw, "red") // create canvas
    err = compositeIcon(mw, "c:/icon.png") // add icon
    err = addText(mw, "Hello world") // add text

    err = mw.WriteImage("c:/output") // get the output
}

func createCanvas(mw *imagick.MagickWand, color string) error {
    // skip error handling
    var err error
    pw := imagick.NewPixelWand()
    defer pw.Destroy()

    pw.SetColor("blue")
    err = mw.NewImage(200, 100, pw) // <-- ERROR_WAND: ContainsNoImages
    return nil
}
```

May please help? I try a few approaches, some approaches get the error of `createCanvas passes lock by value: .../imagick.v3/imagick.MagickWand contains sync.Once contains sync.Mutex`...

May I know how to implement these functions? Functions that can manipulate the `MagickWand` struct continuously, so that the final `mw` will yield the desired result (as in the example above).

**Comment by justinfx** [comment]
Passing the `*imagick.MagickWand` is the correct thing to do. If you tried to deference the pointer and pass the value then you would get the error your descibed, since the internal fields cannot be copied.

This exact complete program works fine for me:

```go
package main

import "gopkg.in/gographics/imagick.v2/imagick"

func generateImage() error {
	mw := imagick.NewMagickWand()
	defer mw.Destroy()

	if err := createCanvas(mw, "red"); err != nil {
		return err
	}

	return mw.WriteImage("/tmp/output.png")
}

func createCanvas(mw *imagick.MagickWand, color string) error {
	pw := imagick.NewPixelWand()
	defer pw.Destroy()

	pw.SetColor(color)
	return mw.NewImage(200, 100, pw)
}

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	if err := generateImage(); err != nil {
		panic(err)
	}
}
```

You will need to be more specific about the error you are getting.

**Comment by byanjiong** [comment]
Ops, sorry... after hours of debugging... I just realized that I debug the wrong lines. Sorry... Everything is ok, no problem... So sorry...

Thank you @justinfx  who try to help me with the code... I naively debug the wrong lines... So sorry... MagickWand is ok, no bug no problem... sorry for the confussion...

Close issue because issue solved, reason:
--> debug the wrong lines

**Comment by justinfx** [comment]
Hey no worries. Glad you figured it out.
