### ISSUE TITLE
not support setImageOpacity?

### ISSUE THREAD

**Issue by tczf1128** [gographics/imagick#177]

**Comment by justinfx** [comment]
Hi. When you submit an issue to a project, please take the time to properly describe your problem. This can at least be an example of code that is not working as you would expect. It should also include the version of imagick/ImageMagick.

**Comment by justinfx** [comment]
I looked into what you might have meant. ImageMagick6 has a `SetImageOpacity` function which still exists in the imagick.v2 bindings:
https://godoc.org/gopkg.in/gographics/imagick.v2/imagick#MagickWand.SetImageOpacity

But it was deprecated in ImageMagick7 and renamed to `SetImageAlpha`. And yes that function was missing from our bindings, so I have just added them.

**Comment by justinfx** [comment]
All good. Thanks for reporting the missing function

**Comment by tczf1128** [comment]
SetImageAlpha seems not work well.  
`
watermark.SetImageAlpha(0.9)  
mw.CompositeImage(watermark, imagick.COMPOSITE_OP_OVER, false, x, y)
`

when I set watermark alpha, I get the error picture. 
![ok](https://user-images.githubusercontent.com/4197519/46995653-31eaef00-d14c-11e8-985b-a355cf125268.jpg)
![error](https://user-images.githubusercontent.com/4197519/46995654-31eaef00-d14c-11e8-8356-a7d22aab2759.jpg)

**Comment by tczf1128** [comment]
thanks anyway
