### ISSUE TITLE
ERROR_CODER: data encoding scheme is not supported `' @ error/webp.c/ReadWEBPImage/338

### ISSUE THREAD

**Issue by tczf1128** [gographics/imagick#181]
error when load a webp image， but  I can get format by this command `magick identify example.webp`

ImageMagick 7.0.8-12
gographics/imagick (im-7)

**Comment by tczf1128** [comment]
anyone have this problem?   I have installed the webp lib

**Comment by justinfx** [comment]
Does this help at all?
https://github.com/ImageMagick/ImageMagick/issues/22

It talks about using a different webp delegate plugin if you are using extended webp files. Its not really something that can be fixed by the Go bindings.

**Comment by tczf1128** [comment]
so use webpmux or vwebp command-line instead?

**Comment by justinfx** [comment]
Does the convert command support your webp file? If it doesn't, then you have that same problem. The ImageMagick C api can't do anything that the convert command can't support.

**Comment by tczf1128** [comment]
convert works well

**Comment by RecurTree** [comment]
Hi, recently，I meet the same problem as your, can I ask you how you solve this problem finally?
