### ISSUE TITLE
How do I set the text to be bold?

### ISSUE THREAD

**Issue by edoger** [gographics/imagick#182]
I tried calling DrawingWand.SetFontWeight(800) to set the text to bold, but it doesn't seem to work. Is there any better suggestion?

**Comment by ChengHuaUESTC** [comment]
try DrawingWand.SetFontSize(size).

**Comment by edoger** [comment]
@ChengHuaUESTC I tried it, it didn't be bold, and this method DrawingWand.SetFontSize(size) changed the text size. Thank you~

**Comment by justinfx** [comment]
As per the suggestion on the ImageMagick forum (which is a good source for finding how to use Imagmagick API), if you don't want to choose a bold font family as your font, this works for me:

```go
	blk := imagick.NewPixelWand()
	blk.SetColor("black")
	dw.SetStrokeColor(blk)
	dw.SetStrokeWidth(5)
```
The stroke width and color control the bold effect.

Ref: http://www.imagemagick.org/discourse-server/viewtopic.php?t=10246

**Comment by justinfx** [comment]
@edoger is your issue resolved?

**Comment by edoger** [comment]
@justinfx Not solved, but I found this to be closely related to the font file used.

**Comment by justinfx** [comment]
Beyond my code suggestion, earlier, is there anything else we can do for this ticket?

**Comment by edoger** [comment]
@jalevin The current stable solution is to solve this problem with different weight font files.

**Comment by justinfx** [comment]
Ok then. Sounds like its not an issue with imagick. Thanks for confirming.

**Comment by edoger** [comment]
@justinfx We did a lot of testing, and the impact of many font files on the results is very significant, the code does not affect the weight of the font file in the image. Thank you~
