### ISSUE TITLE
How to control the text position through the x and y in DrawingWand.Annotation(x, y float64) 

### ISSUE THREAD

**Issue by wangjinbei** [gographics/imagick#183]
how to set x `and` y in DrawingWand.Annotation(x, y float64) let words left vertex alignment

what i want：
![text_plain2](https://user-images.githubusercontent.com/12269209/47891606-f0b64700-de8e-11e8-92c1-1312a5fd226a.png)

But if i set x = 0 , there is a little distance to the left .
And how to calculate the value of y ？

![text_plain2](https://user-images.githubusercontent.com/12269209/47891663-2ce9a780-de8f-11e8-84e2-680c67ee553c.png)

```go
package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	dw := imagick.NewDrawingWand()
	pw := imagick.NewPixelWand()
	pw.SetColor("yellow")
	mw.NewImage(500, 500, pw)
	// Set up a 72 point font
	dw.SetFont("Verdana-Bold-Italic")
	dw.SetFontSize(72)
	dw.SetTextAntialias(true)
	dw.Annotation(0, 76, "magick")
	mw.DrawImage(dw)
	mw.WriteImage("text_plain2.png")
}
```

**Comment by ChengHuaUESTC** [comment]
There is a example, 
![image](https://user-images.githubusercontent.com/6637869/47893461-0a0fc100-de98-11e8-8229-e9881de7a7c5.png).
[http://image-49061403.image.mtmss.com/example.jpg@watermark=2&size=40&text=SGVsbG8g5Zu-54mH5pyN5YqhIQ&p=1&x=0&y=0](url).

For X, there is a little bit space between the left edge and the left of text and  It is OK for our product. You can adjust it with set x < 0.
For Y, I set y = the size of text / 8.

**Comment by justinfx** [comment]
This seems to do what you want:

```go
package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	pw := imagick.NewPixelWand()
	pw.SetColor("yellow")
	mw.NewImage(500, 500, pw)

	dw := imagick.NewDrawingWand()
	dw.SetFont("Verdana-Bold-Italic")
	dw.SetFontSize(72)
	dw.SetTextAntialias(true)
	dw.SetGravity(imagick.GRAVITY_NORTH_WEST)
	dw.Annotation(0, 0, "magick")

	pw.SetColor("none")
	text := imagick.NewMagickWand()
	text.NewImage(500, 500, pw)
	text.DrawImage(dw)
	text.TrimImage(1)

	err := mw.CompositeImage(text, imagick.COMPOSITE_OP_OVER, false, 0, 0)
	if err != nil {
		panic(err)
	}
	mw.WriteImage("/tmp/out.png")
}
```

By using `Trim` we can fully crop the text to its bounds and then composite it in the top left corner at the exact edges.

**Comment by wangjinbei** [comment]
it works.
