### ISSUE TITLE
How to tile image like this command?

### ISSUE THREAD

**Issue by tczf1128** [gographics/imagick#187]
`convert -size 140x80 xc:none -fill grey           -gravity northwest -draw "text 20,20 'copyright'"           -gravity southeast -draw "text 15,25 'copyright'"           miff:- |    composite -tile - 58a40d9d85367.png  wmark_text_tiled.pn`

**Comment by linfangrong** [comment]
How to tile image?

**Comment by linfangrong** [comment]
I see... 
Use TextureImage and set options
