### ISSUE TITLE
can't build examples/resize: too many arguments in call to mw.ResizeImage

### ISSUE THREAD

**Issue by bciceron** [gographics/imagick#188]
using imagick.v3@v3.2.0 on linuxbrew with go version 1.10 and 1.11 result in the same type of error:

```go build ./...
# gopkg.in/gographics/imagick.v3/examples/resize
examples/resize/main.go:33:22: too many arguments in call to mw.ResizeImage
	have (uint, uint, imagick.FilterType, number)
	want (uint, uint, imagick.FilterType)
```
it builds after i remove the blurring effect number but this might mean some of our examples have not been fully ported to imagick.v3 ?

**Comment by justinfx** [comment]
I'm sure you are right on this. There is no testing script that runs a build test on all the examples, but there should be one and the Travis config should probably run them to ensure they build.

**Comment by justinfx** [comment]
related to #138

**Comment by justinfx** [comment]
I've fixed up the examples and added a test script to the travis ci config: df6248d332a2a0d062782f6403bc87058f9882fc

**Comment by bciceron** [comment]
thanks @justinfx
