### ISSUE TITLE
generate lots of tmp files

### ISSUE THREAD

**Issue by 39Er** [gographics/imagick#191]
os: centos 6.3
imagemagick: 6.9.1-10
go: 1.8.3

when I first use this, I call like this(there are 10 goroutines call this method):

```go
func ConverPicToWebp(sourcePic string, picName string) error {
	if sourcePic == "" || picName == "" {
		return nil
	}
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	if err := mw.ReadImage(sourcePic); err != nil {
		return err
	}
	if err := mw.SetCompressionQuality(95); err != nil {
		return err
	}
	if err := mw.SetFormat("webp"); err != nil {
		return err
	}
	if err := mw.WriteImage(picName + ".webp"); err != nil {
		return err
	}
	return nil
}
```
but,then I got this error:

> magick/semaphore.c:346: LockSemaphoreInfo: Assertion `semaphore_info != (SemaphoreInfo *) ((void *)0)' fail ed.

I find this issue: https://github.com/gographics/imagick/issues/26 

So I put the imagick.Initialize() and imagick.Terminate() in the init method,and run it only once.
But my service is running forever,and it generate lots of temporary files in the /tmp，like magick-171425rTL830LoD8gr.

How should I handle this?

**Comment by justinfx** [comment]
Moving the Initialize/Terminate to an init or main function is the right thing to do. ImageMagick generates lots of tmp data which is meant to be cleaned up both by the destruction of objects and when you end up terminating. Are you running into disk space issues?

**Comment by justinfx** [comment]
Also check out this issuss:
https://github.com/ImageMagick/ImageMagick/issues/395

They reference using a more recent release of ImageMagick if you are seeing temp files hanging around long after the process is complete and you have destroyed the objects

**Comment by 39Er** [comment]
Yes,the tmp files make my disk space full.Should I use a higher version of imagemagick?And I use the master branch, which version should I use? What's the difference between master and im-7 branch?Please give me some suggestions,thanks.

**Comment by justinfx** [comment]
Please refer to the README of this project. The master branch currently targets ImageMagick6 (v2) and the im-7 branch targets ImageMagick7 (v3) . But the README describes how you should be importing the package (v2 vs v3)

I would recommend using a more recent release of ImageMagick6 if that is what you are using. That other link suggests they may have done some work around cleaning up. But they also recommend that you have ample tmp disk space so that it can allocate virtual memory. 

How much space is getting filled up over a single run of your app?

**Comment by 39Er** [comment]
My app need running forever, so it is  increasing forever...

**Comment by justinfx** [comment]
The that implies that objects are not getting cleaned up by ImageMagick. If you change it to a format other than webp does it still continue to grow with temp files? Because it could be the webp delegate. I would highly recommend testing against a newer ImageMagick6 or trying ImageMagick7
