### ISSUE TITLE
Original WebP image size reduces after using ReadImageBlob

### ISSUE THREAD

**Issue by palaiyacw** [gographics/imagick#192]
I am facing this strange issue  where i am trying to read the blob of WebP Image through `ReadImageBlob` and in the next line i just try to fetch the same blob using `GetImageBlob`. So, my final blob size reduces strangely. I don't understand whether this is the issue with underlying C library of ImageMagick or with your wrapper. Could you please help. 

I am using `Version: ImageMagick 6.9.8-10 Q16 x86_64` on `ubuntu 16.04`

**Comment by justinfx** [comment]
If you look at the Go source code for ReadImageBlob and GetImageBlob, you will see that it does very little other than call into C and translate the types. There is no resize operation. This means the most likely cause is that the unwanted resize happens somewhere on the ImageMagick webp delegate.

**Comment by palaiyacw** [comment]
Ok, Thanks. I will post this on ImageMagick repository.
