### ISSUE TITLE
 undefined: imagick.Initialize

### ISSUE THREAD

**Issue by bciceron** [gographics/imagick#195]
# env
go version go1.11.4 darwin/amd64

package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()
}

# works:
$ go build -o main main.go
$ GOARCH=amd64 go build -o main main.go

# fails:
GOOS=linux go build -x -o main main.go
WORK=/var/folders/h1/567r1c2x14536fzlj8rnrx1m0000gp/T/go-build193232203
mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg << 'EOF' # internal
// import config
packagefile gopkg.in/gographics/imagick.v3/imagick=/Users/REDACTED/Library/Caches/go-build/02/02b0eee81f2c3f2a200c9bddaa5e95532881b87e1f72fde60697cfc726f04676-d
packagefile runtime=/Users/REDACTED/Library/Caches/go-build/94/94497e7cb947dd063dc62f4f5fe28854d3e5d91182c9ee4fa43550a904ea2b7c-d
EOF
cd /Users/REDACTED/go/src/github.com/REDACTED/converter
/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64/compile -o $WORK/b001/_pkg_.a -trimpath $WORK/b001 -p main -complete -buildid LIPwQPabF3xD2F6h4lD-/LIPwQPabF3xD2F6h4lD- -goversion go1.11.4 -D _/Users/REDACTED/go/src/github.com/REDACTED/converter -importcfg $WORK/b001/importcfg -pack -c=4 ./main.go
// command-line-arguments
./main.go:8:2: undefined: imagick.Initialize
./main.go:9:8: undefined: imagick.Terminate

**Comment by justinfx** [comment]
Cross-compiling a cgo application is complicated. Where have you stored your linux-compiled ImageMagick library and how have you set your environment to discover them? If you have not set anything other than what you have listed, then you are likely trying to pick up the pkg-config or or system location of your OSX build of ImageMagick.

The error though is a bit different than what I would expect to see. It implies it couldn't build a linux version of imagick, and then couldn't import it into your app.

**Comment by justinfx** [comment]
I'm going to close this for lack of activity. I think unless you have the proper cross-platform complilers available, it is complicated to cross-compile a CGO application with vanilla Go tools. I recommend trying on of these 2 options

1. Use docker to build a linux variant of your app
2. Use xgo: https://github.com/karalabe/xgo (high level wrapper around docker)
