### ISSUE TITLE
COMPOSITE_OP_COPY_ALPHA not works

### ISSUE THREAD

**Issue by tczf1128** [gographics/imagick#196]
I want to composite two images, one is a circle image, another is a normal image.
And I want the result is a circle image.

![circle](https://user-images.githubusercontent.com/4197519/51978328-e115c100-24c4-11e9-8352-960a6f7572ae.png)
![input](https://user-images.githubusercontent.com/4197519/51978383-073b6100-24c5-11e9-9032-9a220aa662d9.png)

```go
func (i imagickCircle) circle(buf []byte, opts model.CircleOptions) ([]byte, error) {
	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	err := mw.ReadImageBlob(buf)
	if err != nil {
		log.WithError(err).Error("read image blob")
		return nil, err
	}

	radius := opts.Radius
	pw := imagick.NewPixelWand()
	defer pw.Destroy()
	pw.SetColor("none")
	circle := imagick.NewMagickWand()
	defer circle.Destroy()
	circle.NewImage(radius*2, radius*2, pw)

	draw := imagick.NewDrawingWand()
	defer draw.Destroy()
	color := imagick.NewPixelWand()
	defer color.Destroy()
	color.SetColor("white")
	draw.SetFillColor(color)
	draw.Circle(float64(radius), float64(radius), float64(radius), float64(radius*2))
	circle.DrawImage(draw)

	circle.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_COPY)
	circle.WriteImage("circle.png")

	// mw.SetImageMatte(true)
	width, height := mw.GetImageWidth(), mw.GetImageHeight()
	mw.CropImage(radius*2, radius*2, int(width/2-radius), int(height/2-radius))
	mw.CompositeImage(circle, imagick.COMPOSITE_OP_COPY_ALPHA, false, 0, 0)

	return mw.GetImageBlob(), err
}
```

**Comment by acepukas** [comment]
Was this ever resolved? I'm having the exact same issue. When using imagemagick via the command line I composited a black and white image as a kind of mask and used `copy-opacity` as the compose method. That doesn't seem to be available with imagick (v3) so I attempted to do what tczf1128 was doing but it doesn't work. Maybe I am going about it the wrong way?

**Comment by justinfx** [comment]
@tczf1128 must have figured out the source of the issue

**Comment by acepukas** [comment]
Just want to mention, in case anyone else ends up here too, that the image I was compositing onto was a jpeg. I changed the format to "PNG32" and it worked. I originally was testing compositing on the command line with 3 images. A base image, the composite and a mask image. In that case, the base image (which was created from imagemagick) already had alpha transparency so the format of subsequent images made no difference.
