### ISSUE TITLE
How to save image to webp format?

### ISSUE THREAD

**Issue by raoptimus** [gographics/imagick#199]
Hello
I have tried as
image.SetFormat("webp")
image.WriteImageFile(...)
but image has been saved in jpg format

How to save image to webp format?

```
[[constraint]]
  name = "gopkg.in/gographics/imagick.v3"
  version = "3.2.0"
```

**Comment by justinfx** [comment]
Does your ImageMagick build have the "webp" delegate?

```
$ identify -version
...
Delegates: ...
```

If not, then you need to build ImageMagick with webp support:
http://www.imagemagick.org/discourse-server/viewtopic.php?t=34785
http://www.imagemagick.org/discourse-server/viewtopic.php?t=33718

**Comment by raoptimus** [comment]
```
identify -version
Version: ImageMagick 7.0.8-12 Q16 x86_64 2018-09-23 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```
```
convert -list delegate
webp =>          "dwebp' -pam '%i' -o '%o"
```
command is working:
```
convert test.jpg -quality 80 test2.webp
```
 test2.webp has been saved successfully

**Comment by justinfx** [comment]
So do you get a delegate error from the Imagick program? What kind of result are you getting when you try to convert to "webp". I'm assuming you are correctly linking against that same ImageMagick 7.0.8-12 using the v3 import of this go binding.

**Comment by raoptimus** [comment]
```
image.SetFormat("webp")
image.WriteImageFile(...)
```
code does not get error, and image is saved, but the image in jpg format

if i execute command line convert test.jpg -quality 80 test2.webp
then image in webp format

**Comment by justinfx** [comment]
Normally the extension on the `Write*()` method would do it. But if you are using the ".webp" extension and its still not working, I will need to find time to test this.

**Comment by raoptimus** [comment]
more problem
function GetFormat returns empty string
example
```
img := imagick.NewMagickWand()
img.ReadImage(...)
...
empty := img.GetFormat() 
```

**Comment by raoptimus** [comment]
> Normally the extension on the `Write*()` method would do it. But if you are using the ".webp" extension and its still not working, I will need to find time to test this.

yes. i am using the ".webp" extension
```
originalImg.SetFormat("webp")
fo, _ := os.Create("/Users/.../Downloads/test2.webp")
if err = originalImg.WriteImageFile(fo); err != nil {
    return err
}
fo.Close()
```

**Comment by justinfx** [comment]
> more problem
function GetFormat returns the empty string
example

`GetFormat` is only a getter for the value that was manually set by `SetFormat`. Try using `GetImageFormat`.

**Comment by raoptimus** [comment]
> > more problem
> > function GetFormat returns the empty string
> > example
> 
> `GetFormat` is only a getter for the value that was manually set by `SetFormat`. Try using `GetImageFormat`.

GetImageFormat is working
thank you

**Comment by justinfx** [comment]
I had a moment to test this, and it seems to work as expected on my Linux build, using im 7.0.8-3

```
convert -version

Delegates (built-in): bzlib djvu fontconfig freetype 
    gslib jbig jng jpeg lcms lqr lzma 
    openexr png ps tiff webp wmf x xml zlib
```

The following code produces a valid webp file:

```go
	mw := NewMagickWand()
	mw.ReadImage("in.jpg")
	mw.WriteImage("out.webp")
```

```
identify out.webp
out.webp WEBP 1440x900 1440x900+0+0 8-bit sRGB 122614B 0.000u 0:00.000
```

It looked like from your own `convert` command that you didn't have it built with webp support, like mine shows.

**Comment by raoptimus** [comment]
> ```go
> mw.WriteImage("out.webp")
> ```

it is working, but WriteImageFile is not working
it's strange

thank you very much
sorry for your time

**Comment by justinfx** [comment]
I imagine under the hood `WriteImageFile` is just writing to a file descriptor and isn't considering a name since the file is already open. In that case it must require some other settings.
Glad to hear it is working now.
