### ISSUE TITLE
How to properly crop an image?

### ISSUE THREAD

**Issue by tiagomelo** [gographics/imagick#201]
Hi everyone,

A few years ago I wrote a perl script to resize images to the following dimensions:

- 250x188
- 400x300
- 700x525 

So, suppose a vertical image like this (600x800 resolution):
![600x800](https://user-images.githubusercontent.com/140403/57094582-4016ec00-6ce7-11e9-9528-d36f5fd062bc.jpg)

this is the 250x188 version of it:
![600x800---250x188---resized](https://user-images.githubusercontent.com/140403/57094695-84a28780-6ce7-11e9-9d70-5942721e58d2.jpg)

this is the 400x300 version of it:
![600x800---400x300---resized](https://user-images.githubusercontent.com/140403/57094716-8ec48600-6ce7-11e9-9c2b-c4b0f18a0707.jpg)

and this is the 700x525 version of it:
![600x800---700x525---resized](https://user-images.githubusercontent.com/140403/57094735-9be17500-6ce7-11e9-83e8-19f4c2bdc41d.jpg)

Now I'm gonna show a bit of code to illustrate how I came to this outcome...

```
use Image::Magick;

my $image = Image::Magick->new;
$image->Read($photo_name);

my $clone = $image->Clone();

  # for dimensions 250x188 or 400x300, we'll crop the image
  if($crop_sizes->{"${width}x${height}"}) {
	my ($img_width, $img_height) = $image->Get('width','height');
        
        # checking if the image is vertical or horizontal
        my $desired_geometry = ($img_width > $img_height ? "x$height" : "${width}x");	      
	      
	$clone->Resize(geometry=>$desired_geometry, filter=>'Box');
	$clone->Crop(geometry=>"${width}x${height}", gravity=>"Center");
  } else {
    # for 700x525 dimension, we'll fill the remaining spaces with grey  
    $clone->Resize(geometry=>"${width}x${height}", filter=>$filter);
    $clone->Extent(gravity => "Center", geometry =>"${width}x${height}", background => '#404040');
  }
```

So, I want to implement the same behavior using Go.

So far I have:

```
func main() {
	var err error
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	defer mw.Destroy()

	if err = mw.ReadImage("600x800.jpg"); err != nil {
		log.Fatal(err)
	}

        err = mw.ResizeImage(188, 250, imagick.FILTER_BOX, 1)
	if err != nil {
		log.Fatal(err)
	}
}
```

But how can set the Gravity as 'center', and how can I crop the image like I did in perl? And how can I extent the image with a background color?

**Comment by justinfx** [comment]
Hey. I'm not near a computer that can work through the examples. But have you looked through the available api documentation and code examples in the repo? There is a crop and extent method on wands,
https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.CropImage
But that alone means you have to calculate the offset yourself to make it centered. There is a set SetGravity method:
https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.SetGravity

**Comment by tiagomelo** [comment]
Hi Justin, thanks for the reply. Yes, after researching the API I've found those methods, and indeed I have to calculate the offset to make it centered. I'll try to do it.
