### ISSUE TITLE
 PSD converted to jpg, but PSD layer lost

### ISSUE THREAD

**Issue by taomin597715379** [gographics/imagick#202]
The image in PSD format is compressed into jpg format. The compressed JPG image is only the last layer. The other layers are lost.

**Comment by justinfx** [comment]
Can you try using [MagickWand.MergeImageLayers()](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.MergeImageLayers) ?

It should return you a new wand with all the layers flattened.

**Comment by taomin597715379** [comment]
Thanks a lot, I'm try ...

**Comment by taomin597715379** [comment]
how can I ensure where each layer of psd image put on the initial canvas. Will each of images' position information lost?

**Comment by justinfx** [comment]
What behaviour are you seeing in your tests? The documentation for the merge function says that it depends on the layer option you use, but that it would use the layer offsets from the image.

**Comment by taomin597715379** [comment]
func TestFromPsdTranstoJpg(t *testing.T) {
	w := &bytes.Buffer{}
	err := GetPsd("1234567890.psd", w, "bucket0")
	if err != nil {
		t.Errorf("failed. error:%s", err.Error())
	}
	bf := w.Bytes()
	origin, _ := os.Create("psd_origin.jpg")
	origin.Write(bf)
	origin.Close()

	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	mw.ReadImageBlob(bf)
	rb := mw.GetImageBlob()
	after, _ := os.Create("trans_after.jpg")
	after.Write(rb)
	after.Close()
}
1234567890.psd, this PSD picture after ReadImageBlob and GetImageBlob two processing, only the last layer of this psd picture, the other layers are all lost, how can we do not lose the data of other layers?

**Comment by taomin597715379** [comment]
func TestFromPsdTranstoJpg(t *testing.T) {
	w := &bytes.Buffer{}
	err := GetPsd("1234567890.psd", w, "bucket0")
	if err != nil {
		t.Errorf("failed. error:%s", err.Error())
	}
	bf := w.Bytes()
	origin, _ := os.Create("psd_origin.jpg")
	origin.Write(bf)
	origin.Close()
	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	mw.ReadImageBlob(bf)
	rb := mw.GetImageBlob()
	after, _ := os.Create("trans_after.jpg")
	after.Write(rb)
	after.Close()
}

1234567890.psd, this PSD picture after ReadImageBlob and GetImageBlob two processing, only the last layer of this psd picture, the other layers are all lost, how can we do not lose the data of other layers?

**Comment by justinfx** [comment]
It turns out that the only magic you need is a call to `mw = mw.CoalesceImages()`. That fixes it in my test. It aligns all of the layers properly. I didn't even need a call to merge the layers.

**Comment by taomin597715379** [comment]
Okay, let me test it

**Comment by taomin597715379** [comment]
Hi, After using the mw.CoalesceImages(), layers of the PSD's Image will not be lost，but image cannot be watermarked.

**Comment by justinfx** [comment]
Can you be more specific about your new issue?

**Comment by taomin597715379** [comment]
func TestFromPsdTranstoJpg(t *testing.T) {
	w := &bytes.Buffer{}
	err := GetPsd("1234567890.psd", w, "bucket0")
	if err != nil {
		t.Errorf("failed. error:%s", err.Error())
	}
	bf := w.Bytes()
	origin, _ := os.Create("psd_origin.jpg")
	origin.Write(bf)
	origin.Close()
	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	mw.ReadImageBlob(bf)
	mw = mw.CoalesceImages()
	/*****/
	// Formatting and watermarking
	mw.SetImageFormat("JPEG")
	mw.CompositeImage(water, imagick.COMPOSITE_OP_OVER, 800, 800)
	/*****/
	rb := mw.GetImageBlob()
	after, _ := os.Create("trans_after.jpg")
	after.Write(rb)
	after.Close()
}
CompositeImage() does not work

**Comment by justinfx** [comment]
> mw.CompositeImage(water, imagick.COMPOSITE_OP_OVER, 800, 800)

That 800,800 offset is likely compositing your watermark outside of the image area. I tested this fine with compositing it at 0,0

If you are trying to watermark it at the center, then you need to calculate the correct offsets based on the side of the main image.

**Comment by taomin597715379** [comment]
Is it convenient to give your test code?

**Comment by justinfx** [comment]
I'm using v3

```go
package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error

	mw := imagick.NewMagickWand()

	err = mw.ReadImage("/tmp/layers.psd")
	if err != nil {
		panic(err)
	}

	water := imagick.NewMagickWand()
	if err = water.ReadImage("/tmp/water.png"); err != nil {
		panic(err)
	}

	mw = mw.CoalesceImages()
	if err = mw.CompositeImage(water, imagick.COMPOSITE_OP_OVER, false, 0, 0); err != nil {
		panic(err)
	}

	if err = mw.WriteImage("/tmp/out.jpg"); err != nil {
		panic(err)
	}
}
```

**Comment by taomin597715379** [comment]
I upgraded to V3 version, and now it can be watermarked normally, but there are still some problems in watermarking. The problems are as follows: watermarking is a white LOG. I test that different management methods of PSD layers will affect the final color of the watermarking. If the PSD layers are simple layer by layer, the watermarking is normal, but if the PSD layers are grouped, the watermarking is normal. Print color is abnormal, LOG turned black

**Comment by taomin597715379** [comment]
In short, the complexity of the PSD layer will affect the watermarking effect, which I do not want to see.

**Comment by justinfx** [comment]
Yea at this point I am not sure what to tell you, other than to ask on the ImageMagick forum where there are people that are experts in using the API. This project is a binding which means I can help with bugs and missing features that need to be added to access the C API.  I don't really have any advice on how to work with psd layers beyond helping you find the method to flatten it and to properly composite an overlay in the right position.

**Comment by taomin597715379** [comment]
using v3
```
func TestImageEps() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error

	mw := imagick.NewMagickWand()

	err = mw.ReadImage("/tmp/abc.eps")
	if err != nil {
		panic(err)
	}

	mw = mw.CoalesceImages()
	err = mw.ScaleImage(3508, 2636)
	if err != nil {
		panic(err)
	}

	if err = mw.WriteImage("/tmp/abc.jpg"); err != nil {
		panic(err)
	}
}
```
After the images in EPS format are output to JPG through ScaleImage, it is found that the noise and granularity of the images are very large. Why?
I hope that the images processed by API will be as good as the ones turned out by AI tools.

**Comment by justinfx** [comment]
Is this a completely new issue to the last 2 issues in this ticket?

**Comment by taomin597715379** [comment]
Yes, It's new issue

**Comment by taomin597715379** [comment]
I submitted a new issue not in this ticket
