### ISSUE TITLE
After the EPS format picture is enlarged in equal proportion, the quality of the picture is not high

### ISSUE THREAD

**Issue by taomin597715379** [gographics/imagick#203]
using v3

func TestImageEps() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error

	mw := imagick.NewMagickWand()

	err = mw.ReadImage("/tmp/abc.eps")
	if err != nil {
		panic(err)
	}

	mw = mw.CoalesceImages()
	err = mw.ScaleImage(3508, 2636)
	if err != nil {
		panic(err)
	}

	if err = mw.WriteImage("/tmp/abc.jpg"); err != nil {
		panic(err)
	}
}
After the images in EPS format are output to JPG through ScaleImage, it is found that the noise and granularity of the images are very large. Why?
I hope that the images processed by API will be as good as the ones turned out by AI tools.

**Comment by justinfx** [comment]
Is the solution from #122 relevant to your problem? It was similar in that it was about converting a pdf with enough resolution. I think when you read an EPS, it will need to rasterize it and you are likely getting a low PPI value. Does it improve when you set it to 300 via `SetResolution() ` before you read it in?

**Comment by taomin597715379** [comment]
OK

**Comment by taomin597715379** [comment]
Thank you very much. With your help, most of the problems I have encountered have been solved.But there is another problem，The code is as follows, Using V3
```
func TestImageWater() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error

	mw := imagick.NewMagickWand()
	mw.SetResolution(200, 200)
	err = mw.ReadImage("/tmp/abc.psd")
	if err != nil {
		panic(err)
	}

	water := imagick.NewMagickWand()
	if err = water.ReadImage("llogo.png"); err != nil {
		panic(err)
	}
	mw = mw.CoalesceImages()

	if err = mw.CompositeImage(water, imagick.COMPOSITE_OP_OVER, true, 100, 200); err != nil {
		panic(err)
	}

	if err = mw.WriteImage("/tmp/abc.jpg"); err != nil {
		panic(err)
	}
}
```
the color of the watermarking on this picture(/tmp/abc.jpg) is different from llogo.png.  I don't know why?

**Comment by justinfx** [comment]
I tested this with my own images and everything looks normal. It could be related to your source images and the colorspace/colorprofile settings:
https://imagemagick.org/script/color-management.php

You would need to provide the sample input images to be sure. But it would likely have to do with converting

**Comment by justinfx** [comment]
Since your EPS scaling issue is solved, I am going to close this issue.
