### ISSUE TITLE
JP2 compression

### ISSUE THREAD

**Issue by Crapulax** [gographics/imagick#204]
Hello
I use imagick v3 to change image format, compress and resize images since 3 years.

I have recompiled imagick 7.0.8-41 with webp and jp2 support (libopenjp2.so.2.1.2). For webp everything is working just fine. For jp2, images generated from original jpg/png images are indeed jp2 image as shown by identify:
_identify image.jp2
image.jp2 **JP2** 800x600 800x600+0+0 8-bit sRGB 0.000u 0:00.000_
But quality compression is not working. Whatever I am doing, i always get the same image size.

If I use on command line convert image.png -quality xx image.jp2 I do get compressed jp2 images with different size depending on quality parameter, so I guess that libraries are well installed. For information, convert -version output:
`Version: ImageMagick 7.0.8-41 Q16 x86_64 2019-05-30 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP
Delegates (built-in): bzlib fftw fontconfig freetype gvc jbig jng jp2 jpeg lcms lqr lzma openexr pangocairo png webp wmf x xml zlib`

This is the jp2 code i use (i removed some error checking in below, but all errors are checked in original code):
`
if err := mw.ReadImageBlob(img); err == nil {

		if err := mw.SetImageFormat("JP2"); err == nil {
			if err := mw.SetImageCompression(imagick.COMPRESSION_JPEG2000); err != nil{
				return nil
			}

			if err := mw.SetImageCompressionQuality(20); err != nil {
				return nil
			}
		} 
	}
	return mw.GetImageBlob()
`
I am not an image expert so I might miss something obvious. Similar code does work for webp and jpg format. I tried different compression format, changing order of  imagick instructions (set compression and thet set image format) without result. I always get the same resulting size for a given image. What do i need to do to dig further on this issue, any help greatly appreciated.

Thanks

**Comment by justinfx** [comment]
This works for me:

```go
mw.SetCompressionQuality(50)
```
You want `SetCompressionQuality` instead of `SetImageCompressionQuality` ([ref](https://stackoverflow.com/questions/46441364/what-is-difference-between-setimagecompressionquality-vs-setcompressionquality))
> The method setImageCompressionQuality sets compression quality for your current image.
> ...
> The method setCompressionQuality sets compression quality for the whole object.

Also, the compression option JPEG2000 probably isn't needed since it figures it out when you are using `WriteImage` with a ".jp2" extension. But you likely want `SetCompression()` if you are going to extract a blob.

**Comment by Crapulax** [comment]
Thanks Justin, using `SetCompressionQuality` did make the trick!
The only thing is that I was aware of these two functions. But, when I added the webp support, I had the same issue with compression not working. BUT that time, to get webp compression working I had and have to use `SetImageCompressionQuality` !!?. `SetCompressionQuality` seems just ignored on webp. By the way I did not ever try to do the reverse on jp2... I guess that I am still missing something on how imagick works...

But thanks again !

**Comment by justinfx** [comment]
Glad it's working for your now.

> I guess that I am still missing something on how imagick works

Just to be clear, it is not a peculiarity of Imagick, which is just a binding library. This is the behavior of the ImageMagick C API which means it would be the same situation in other bindings, for php, C#, etc.
