### ISSUE TITLE
extract dominant colors

### ISSUE THREAD

**Issue by sarovin** [gographics/imagick#205]
Hi,
how to extract dominant colors from an image?

I search the equivalent of: "convert web-applications.svg  -format %c -colorspace LAB -colors 5 histogram:info:- | sort -n -r"

**Comment by justinfx** [comment]
I haven't tried anything, but would it be a combination of using:

[MagickWand.SetColorspace](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.SetColorspace)
[MagickWand.GetImageHistogram](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.GetImageHistogram)

**Comment by sarovin** [comment]
HI @justinfx , I want create an example on this repo.

I tryed this code:
```
imagick.Initialize()
defer imagick.Terminate()

mw := imagick.NewMagickWand()
defer mw.Destroy()

if err := mw.ReadImageBlob(blob); err != nil {
    return err
}

mw.UniqueImageColors()
mw.QuantizeImage(5, imagick.COLORSPACE_LAB, 0, imagick.DITHER_METHOD_UNDEFINED, false)
ncolors, colors := mw.GetImageHistogram()

for i, c := range colors {
    h, s, b := c.GetHSL()
    fmt.Println(i, "- COLOR: ", h, s, b)
} 
```
What do you think about this snippet???
Can you help me to calculate HEX from HSL?

**Comment by justinfx** [comment]
Does the snippet do what you want? I'm not sure what you are asking, regarding the snippet. But if you were after a way to convert to hex, a quick google search turns up this logic:
https://github.com/gerow/go-color/blob/master/color.go#L103

So:
```go
const delta = 1 / 512.0

func ToHTML(p *imagick.PixelWand) string {
	return fmt.Sprintf("#%02x%02x%02x",
		byte((p.GetRed()+delta)*255),
		byte((p.GetGreen()+delta)*255),
		byte((p.GetBlue()+delta)*255))
}
```
