### ISSUE TITLE
how to convert image 72 dpi to 300 dpi

### ISSUE THREAD

**Issue by maojindao55** [gographics/imagick#207]
```	
        mw := imagick.NewMagickWand()
	mw.SetResolution(300, 300)
	pw := imagick.NewPixelWand()
	pw.SetColor("white")
	mw.NewImage(w, h, pw)
	mw.WriteImage("/Users/apple/Downloads/picsrc/con.png")
```
the code not work,  the con.png still 72 dpi

**Comment by justinfx** [comment]
That repro seems to work fine for me, producing a png with 300x300 PPI, when I check it with `identify -verbose `

**Comment by maojindao55** [comment]
I use mac picture preview get the info:
![image](https://user-images.githubusercontent.com/6436125/60635598-eac19d00-9e45-11e9-9d62-07b1161ee3a5.png)

**Comment by justinfx** [comment]
I think its a bit of missing metadata in the image. Try this:

```go
        mw := imagick.NewMagickWand()
        mw.SetImageUnits(imagick.RESOLUTION_PIXELS_PER_INCH)
	mw.SetResolution(300, 300)
	pw := imagick.NewPixelWand()
	pw.SetColor("white")
	mw.NewImage(w, h, pw)
        mw.SetImageUnits(imagick.RESOLUTION_PIXELS_PER_INCH)
        mw.SetImageResolution(300, 300)
	mw.WriteImage("/Users/apple/Downloads/picsrc/con.png")
```

The first part, `SetResolution()` controls how the wand will **READ** in image data.
The second part, `SetImageResolution()` controls the image density before you **WRITE**

**Comment by maojindao55** [comment]
thx bro. it works well!
