### ISSUE TITLE
A single go binary which uses both v2 and v3 bindings ends up identifying reliably as ImageMagick7

### ISSUE THREAD

**Issue by jhford-scout24** [gographics/imagick#208]
I am building a small server to compare different image processing systems.  Our current system is built on ImageMagick6, which requires me to include tests for ImageMagick6.  In order to simplify building a docker file, I have collected all the various processors into a single binary, which has a `--encoder` flag which can be set to values like `magick` and `magick6`.

I have applied two different patches to both of my imagick clones:
```bash
RUN go get -d "gopkg.in/gographics/imagick.v2/imagick"
WORKDIR /go/src/gopkg.in/gographics/imagick.v2/
COPY magick6-pkgconfig.diff magick6-pkgconfig.diff
RUN patch -p1 < magick6-pkgconfig.diff

RUN go get -d "gopkg.in/gographics/imagick.v3/imagick"
WORKDIR /go/src/gopkg.in/gographics/imagick.v3/
COPY magick7-pkgconfig.diff magick7-pkgconfig.diff
RUN patch -p1 < magick7-pkgconfig.diff
```

```diff
diff --git a/imagick/imagick.go b/imagick/imagick.go
index 1330fc0..16dc49e 100644
--- a/imagick/imagick.go
+++ b/imagick/imagick.go
@@ -5,6 +5,6 @@
 package imagick // import "gopkg.in/gographics/imagick.v2/imagick"

 /*
-#cgo !no_pkgconfig pkg-config: MagickWand MagickCore
+#cgo !no_pkgconfig pkg-config: MagickWand-6.Q16HDRI MagickCore-6.Q16HDRI
 */
 import "C"
```

```diff
diff --git a/imagick/imagick.go b/imagick/imagick.go
index 8cda684..a697767 100644
--- a/imagick/imagick.go
+++ b/imagick/imagick.go
@@ -5,6 +5,6 @@
 package imagick // import "gopkg.in/gographics/imagick.v3/imagick"

 /*
-#cgo !no_pkgconfig pkg-config: MagickWand MagickCore
+#cgo !no_pkgconfig pkg-config: MagickWand-7.Q16HDRI MagickCore-7.Q16HDRI
 */
 import "C"
```

When I build this on both my local host (mac os x) with the home brew image magick packages and when I run this under docker, I am definitely linking to both versions of ImageMagick:
```
ldd app
<snip>
	libMagickWand-7.Q16HDRI.so.6 => /deps/lib/libMagickWand-7.Q16HDRI.so.6 (0x00007fb052b15000)
	libMagickCore-7.Q16HDRI.so.6 => /deps/lib/libMagickCore-7.Q16HDRI.so.6 (0x00007fb052587000)
	libMagickWand-6.Q16HDRI.so.6 => /deps/lib/libMagickWand-6.Q16HDRI.so.6 (0x00007fb05228d000)
	libMagickCore-6.Q16HDRI.so.6 => /deps/lib/libMagickCore-6.Q16HDRI.so.6 (0x00007fb051d02000)
<snip>
```
```
otool -L app
<snip>
	/usr/local/opt/imagemagick/lib/libMagickWand-7.Q16HDRI.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/imagemagick@6/lib/libMagickWand-6.Q16.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/imagemagick@6/lib/libMagickCore-6.Q16.6.dylib (compatibility version 7.0.0, current version 7.0.0)
<snip>
```

What's strange to me is that when I run both versions of the decoder, they both work even though the APIs that I'm using are specific to the version of image magick in use, but calls to `imagick.GetVersion()` reliably return the ImageMagick7 version string `magick (ImageMagick 7.0.8-53 Q16 x86_64 2019-07-09 https://imagemagick.org)`

I know that I could use a build time tag to select between using ImageMagick 6 and 7, but that makes the docker deployment significantly more complex, so I'd like to avoid it.

I'm wondering if I'm doing something incredibly stupid here, by linking to both versions of ImageMagick or if it's just something simple like both versions of ImageMagick writing their version information to the same location and the C function just looks to the same address for the strings.

Each implementation for v6 and v7 are in their own modules and I've verified that for their respective test binaries, they only link to a single version and also have significant performance differences, implying that they're using the correct version of imagemagick.

I'd appreciate any information to help me figure this out.  Thanks for the great library!

**Comment by justinfx** [comment]
I've never tried to link a program that uses both ImageMagick6 and ImageMagick7, but the problem really lies with ImageMagick C API as opposed to any bindings. C has no concept of namespaces. The convention lies solely with the naming of the symbols. Because IM6 and IM7 are using the same names for symbols, when you link both of them you are likely having symbol collision and only one of them is going to win. See this (on linux):

```
nm -C ImageMagick/dist/6.9.9-35/lib/libMagickWand-6.Q16.so | grep GetVersion
00000000000aa8c0 T MagickGetVersion

nm -C ImageMagick7/dist/lib/libMagickWand-7.Q16HDRI.so | grep GetVersion
00000000000b0470 T MagickGetVersion
```

It is the same symbol being linked into your program. My recommendation would be to avoid this situation and build 2 different binaries. Otherwise you would have to do some much more complicated approach by possibly building a shim C layer that links against each version of ImageMagick and hides the ImageMagick symbols. Then it would provide non-conflicting delegate functions such as:

```
# shim_im6.so
Magic6GetVersion()

# shim_im7.so
Magic7GetVersion()
```

Your Go program would need to only use the symbols from the shim so that it doesn't get symbols colliding. Probably not worth it.

**Comment by jhford-scout24** [comment]
Yes, that doesn't seem worth it.  Thanks for the clear and quick explanation.  I think I can acheive most of what I want by just having two binaries: both with all encoders, but only one of v6 and v7 of imagemagick.

Thanks!
