### ISSUE TITLE
on windows,  open main.exe failed, miss xx.dll

### ISSUE THREAD

**Issue by maojindao55** [gographics/imagick#211]
on my develop pc, I go build project to main.exe, the main exe work well,
but cp the main.exe to a new win pc,  open failed, miss xx.dll

i guest that all win pc have to install this
```
Install msys2-x86_64
In msys shell, do:
pacman -Syuu
pacman -S mingw-w64-x86_64-gcc
pacman -S mingw-w64-x86_64-pkg-config
pacman -S mingw-w64-x86_64-zlib
pacman -S mingw-w64-x86_64-imagemagick
```
i think  it is  not a friendly way to request users that not a developer to install that  dependents

have a another idea?

**Comment by justinfx** [comment]
It is because the default way of building your application is using dynamic linking to shared library dependencies (ImagMagick, ...). The way to solve this is by static linking all of your dependencies. I have done this on Linux, but I have no details for other platforms.

**Comment by maojindao55** [comment]
> It is because the default way of building your application is using dynamic linking to shared library dependencies (ImageMagick, zlib, ...). The way to solve this is by static linking all of your dependencies. I have done this on Linux, but I have no details for other platforms. It means you need to have static libraries for all your dependencies. Then you need to pass explicit cgo flags to your `go` build command to tell it to link your C libraries statically.

Would you share your way that static linking dependencies On Linux? I maybe use of reference on window platform

**Comment by justinfx** [comment]
This was years ago when I used these bindings as a static library dependency:

```
export CGO_CFLAGS="`pkg-config --cflags MagickWand MagickCore`"

export CGO_LDFLAGS="\
-lstdc++ -lXext -lX11 \
-Wl,-Bstatic \
    `pkg-config --libs MagickWand MagickCore` \
    -lIlmImf -lImath -lHalf -lIlmThread -lIex \
    /path/to/lib/libtiff.a \
    /path/to/lib/libjpeg.a \
    -llcms -lfontconfig -lfreetype -lxml2 -lexpat -lfftw3 -lpng12 -lbz2 -lz -lm \
-Wl,-Bdynamic"

go build -tags no_pkgconfig -v gopkg.in/gographics/imagick.v2/imagick
```

In my case I had needs for extra delegates like OpenEXR

**Comment by maojindao55** [comment]
thx my bro, i had solved few days ago, 
i  copy the .dll files to a foders and set a env path ,  it runed ok!
My customer almost jumped when he used my win soft. haha
