### ISSUE TITLE
Finalizers for Clone calls?

### ISSUE THREAD

**Issue by pfitzner** [gographics/imagick#212]
Just a point of information: As stated, wand constructors of the New* type have finalizers and are handled the GC, obviating the need to manually deallocate them with Destroy. Are the wands returned by the corresponding Clone calls also GC managed, or do I have to muck up my code by mixing the deallocation methods?

**Comment by justinfx** [comment]
It is pretty easy to just look at the source for the `Clone()` call:
https://github.com/gographics/imagick/blob/v3.2.0/imagick/magick_wand.go#L53
https://github.com/gographics/imagick/blob/v3.2.0/imagick/pixel_iterator.go#L63
https://github.com/gographics/imagick/blob/v3.2.0/imagick/drawing_wand.go#L43

They call go through the private `new*` constructors which set finalizers.

**Comment by pfitzner** [comment]
Thanks! This was enlightening, once I understood what the KeepAlive call does. It's pretty shocking that a variable's extent doesn't persist throughout the lexical scope of its context. Still, things were done correctly. Might I suggest that this be made explicit (i.e. for all such calls) in the memory management section?

**Comment by justinfx** [comment]
It is references in the last sentence in that memory management section:

> Calling Destroy() on types that are either created via New* or returned from other functions calls only forces the cleanup of the item immediately as opposed to later after garbage collection triggers the finalizer for the object.

But I could update the second sentence as well so that it doesn't only refer to calls starting with `New*` if that would help?

**Comment by pfitzner** [comment]
Indeed. A more careful reading would have told me that, but looking at the code was educational. Thanks again.

**Comment by justinfx** [comment]
Cool. I've edited the text in that section.
