### ISSUE TITLE
Convert PDF to jpg:   wand contains no images `MagickWand-0' @ error/magick-image.c/MagickWriteImage/13081

### ISSUE THREAD

**Issue by fengbenming** [gographics/imagick#214]
if occur error message like before. you need to install ghostscript.   
brew uninstall ghostscript
brew install ghostscript

**Comment by taylorkline** [comment]
Thanks, this helped me on MacOS.

**Comment by rmysore-sukshi** [comment]
Helped me on ubuntu.
