### ISSUE TITLE
Missing Image Attributes -- any plans?

### ISSUE THREAD

**Issue by jn0** [gographics/imagick#217]
I'd like to have a mean to apply some EXIF to the image being created (captured from a CV cam).
Hence, I need ["image attributes"](http://www.imagemagick.org/api/Image++.php#Image%20Attributes) access.
I couldn't find them in the implementation provided.
Is there any plans to add those methods too?

**Comment by justinfx** [comment]
Can you try using:
https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.SetImageProperty

It seems they deprecated MagickSetImageAttribute in favor of MagickSetImageProperty

**Comment by jn0** [comment]
Hm... Trying to set `exif:comment` (or `EXIF:usercomment`) neither fails nor works :/
I use this code to verify:
```golang
	fmt.Printf("Image identification: %s", mw.IdentifyImage())
	var n int = 0
	for i, a := range mw.GetImageArtifacts("") {
		v := mw.GetImageProperty(a)
		fmt.Printf("[%#v]=[%#v]=%#v\n", i, a, v)
		n++
	}
	if n == 0 {
		fmt.Printf("Image has no artifacts.\n")
	}
```
So, I can see
```
  Properties:
    date:create: 2019-10-22T12:03:39+03:00
    date:modify: 2019-10-22T12:03:39+03:00
    jpeg:colorspace: 1
    jpeg:sampling-factor: 1x1
    signature: 37cc191c39009f8ea497cbe939507668c33cddef2ca03422712d5e70307e45e8
```
and
```
[0]=["date:create"]="2019-10-22T12:03:39+03:00"
[1]=["date:modify"]="2019-10-22T12:03:39+03:00"
[2]=["jpeg:colorspace"]="1"
[3]=["jpeg:sampling-factor"]="1x1"
[4]=["signature"]="37cc191c39009f8ea497cbe939507668c33cddef2ca03422712d5e70307e45e8"
```
only.

Looks like I have to guess valid names/values…
The `exif:` prefix (in caseless compare) has been seen in the code, but not the prop names :(

**Comment by jn0** [comment]
This is roughly what I do
```golang
// ...
imagick.Initialize(); defer imagick.Terminate()
mw := imagick.NewMagickWand(); defer mw.Destroy()
var e error
if e = mw.ReadImage("some.jpeg"); e != nil { fmt.Fatalf("ReadImage: %v", e); }
// ...
e = mw.SetImageProperty("exif:comment", "this is a sample user comment")
// or e = mw.SetImageArtifact("exif:comment", "this is a sample user comment")
if e != nil { return fmt.Fatalf("SetImageXXX: %v", e); }
// ...
```

**Comment by jn0** [comment]
Heh...
```golang
	var propNames = []string{
		"exif:UserComment",
		"exif:Photo.UserComment",
		"exif:37510",
		"exif:0x9286",
		"UserComment",
		"37510",
		"0x9286",
	}
	const propValue string = "this is a sample user comment"
	for _, pn := range propNames {
		if e := mw.SetImageArtifact(pn, propValue);
			e != nil { fmt.Printf("SetImageArtifact: %v", e); }
		if e := mw.SetImageProperty(pn, propValue);
			e != nil { fmt.Printf("SetImageProperty: %v", e); }
	}
```
does nothing.

Names and IDs from:
- https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/usercomment.html
- https://www.exiv2.org/tags.html
- https://sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html

**Comment by jn0** [comment]
And 3rd party tool verification proves it:
```
jno@jno-intra:~/src/go-basler-pylon$ exiv2 pr /tmp/go-basler-pylon-test/5957d50c6a5ab.jpg
File name       : /tmp/go-basler-pylon-test/5957d50c6a5ab.jpg
File size       : 148933 Bytes
MIME type       : image/jpeg
Image size      : 2448 x 2048
/tmp/go-basler-pylon-test/5957d50c6a5ab.jpg: No Exif data found in the file
jno@jno-intra:~/src/go-basler-pylon$ 
```

**Comment by jn0** [comment]
Hm… In [property.c:4290](https://imagemagick.org/api/MagickCore/property_8c_source.html#l04290) EXIF section is "commented out" for `SetImageProperty`…
What is "percent's escape" here?

**Comment by justinfx** [comment]
These links (albeit quite old) imply that ImageMagick has limited support for exif, only writing "known" properties:
https://imagemagick.org/discourse-server/viewtopic.php?t=7136
https://www.imagemagick.org/discourse-server/viewtopic.php?t=14234

The suggestions have been to either use `exiftool` externally, or try reading and writing the "exif" profile blob (GetImageProfile/SetImageProfile) with an exif library like:
https://github.com/dsoprea/go-exif

**Comment by jn0** [comment]
Looks like you're right…
Went to dig `go-exif`, thanks!
