### ISSUE TITLE
Some help with converting PDF to PNG

### ISSUE THREAD

**Issue by gennaios** [gographics/imagick#218]
Hello,

I'm trying to make a PNG thumbnail of the first page of a PDF, the cover. Reading issues and some examples, I've come up with this so far:

```
imagick.Initialize()
defer imagick.Terminate()

mw := imagick.NewMagickWand()
defer mw.Destroy()

err = mw.ReadImage(pdfFilePath)
err = mw.SetResolution(72, 72) // density
err = mw.SetGravity(imagick.GRAVITY_CENTER)
err = mw.SetCompressionQuality(90)
mw.SetIteratorIndex(0)

err = mw.SetImageFormat("png")
err = mw.WriteImage(coverPath)
```

What I was trying to reproduce was `convert -thumbnail 80x80 -background none -gravity center -extent 80x80 -quality 90`. I was trying to get a transparent background which may not be background none. Maintaining aspect ratio I think is correct. On macOS, I think I have the needed dependences, and tried reinstalling ghostscript via homebrew as mentioned in one issue. The error I get is:

`ERROR_WAND: wand contains no images 'MagickWand-0' @ error/magick-image.c/MagickWriteImage/13084`

Help would be great. Thank you.

**Comment by justinfx** [comment]
Unfortunately I don't have a mac to test this against. But it does look related to the lack of ghostscript being available to ImageMagick. Maybe you need to also reinstall ImageMagick once ghostscript is available? The brew recipe may be looking for it when it configured ImageMagick.

**Comment by gennaios** [comment]
I tried I believe every suggestion I saw elsewhere: reinstalling ghostscript and un- & re-installing imagemagick, options such as `--with-ghostscript` (which might have been removed), and so forth. Eventually I was able to edit the formula before installing from source: `brew edit ghostscript`, changing it to `--with-gslib`. It then works. There's a closed related Homebrew issue from not too long ago. Maybe things have changed since then; I'll post a comment there. There's no recent talk about it anywhere. Perhaps the formula has changed and no one has recently asked about it.

As for what I'm trying to reproduce with the API, it is something like `convert -resize 80x80 -background transparent -colorspace srgb -depth 8 -gravity center -extent 80x80 -strip -quality 90 …` It is much effort sorting thru the docs and figure out the differences between various commands. I have most of it working except trying to gravity center the resulting image with a transparent background. Haven't figured that part out with all the commands I've tried, and trying them in a different order. `SetImageExtent` allows me to resize while keeping aspect ratio without needing to calculate dimensions though perhaps that's part of the issue. If you have tried such and offhand could offer suggestions, that'd be appreciated. Otherwise, feel free to close the issue.

**Comment by gennaios** [comment]
btw, I've seen various issues with people trying to make an image out of the first page of a PDF. Rather than reading the PDF and setting the page to the first, like on the command-line it's possible to specify file name as `file.pdf[0]` and it's much quicker.

**Comment by gennaios** [comment]
One option that may simplify use:

https://imagemagick.org/api/mogrify.php

I don’t know much about any disadvantages over specifying all operations separately though it is an option. Seems unimplemented?

**Comment by justinfx** [comment]
`MagickCommandGenesis` looks to be available in im-6 and im-7, and we do already lightly expose the `ImageInfo` struct. However I don't see that we are currently allowing for a using to create a new `ImageInfo` that can be passed to this call. So someone would need to do the work of exposing that and then adding the call to `MagickCommandGenesis`

**Comment by justinfx** [comment]
I don't know if this is helpful to your situation, but I have just exposed `ConvertImageCommand()` and released in v3.3.0

**Comment by gennaios** [comment]
Thanks for the mention. I had noticed. Might give it a try sometime.

**Comment by justinfx** [comment]
All good. ImageMagick has a pretty confusing API, I think. It's just a matter of getting a response from the community. All we can do on this project is expose the API calls from C
