### ISSUE TITLE
delegates.xml error in AWS Lambda

### ISSUE THREAD

**Issue by Andrea-Arguello** [gographics/imagick#221]
I am using ImageMagick v3 as a layer for a Lambda Function in Golang, using the library. I've compiled ImageMagick 7.0.9-8 from source inside an EC2 t3 micro instance running Amazon Linux, and zipped the binaries, shared, etc, and libs to deploy my layer. However, it throws this error:
```WARNING_CONFIGURE: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/699```

I have tried the following:
- Add the directories /opt/Imagick/bin and /opt/Imagick/lib to the environment.
- Check if the directories /opt/Imagick/bin, /opt/Imagick/etc/ImageMagick-7/delegates.xml, and /opt/Imagick/share/ImageMagick-7/delegates.xml exist with [code]os.Stat[/code] and [code]os.IsNotExist[/code], which haven't printed any error. 
- Do prints after every if in this code https://golangcode.com/convert-pdf-to-jpg to check where it is failing

We noticed the happens right after invoking imagick.NewMagickWand, and have no idea how to move on from this problem

**Comment by justinfx** [comment]
That sounds more like an ImageMagick problem as opposed to an issue with the Go bindings. All signs point to some issue with the packaging of the ImageMagick installation. It also implies that trying to run a `magick in.file out.file` would likely produce the same output. I've seen suggestions of doing `magick -debug configure in.file out.file` to see more information about why it cannot access the configuration file.
You can also see the debug logging output for your Go application by setting this environment variable before starting:

```
export MAGICK_DEBUG=configure
```

**Comment by justinfx** [comment]
Closing for now. If you find this is a problem with the imagick binding, we can revisit
