### ISSUE TITLE
Do you support dissolve about composite?

### ISSUE THREAD

**Issue by Zstro** [gographics/imagick#223]
like this https://imagemagick.org/Usage/annotating/#wmark_image

**Comment by justinfx** [comment]
Yes, the [MagickWand.CompositeImage](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.CompositeImage) and [MagickWand.CompositeLayers](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.CompositeLayers) methods are exposed, and you can use the [COMPOSITE_OP_DISSOLVE](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#CompositeOperator)  operator

**Comment by Zstro** [comment]
Thanks for replying,but how do I adjust the proportion of dissolve

**Comment by justinfx** [comment]
Sorry for the delayed response. A "dissolve" via the command line is sugar for multipling your watermark image alpha channel by a certain amount, and then performing an "over" composite. This should do what you want:

```go
package main

import (
	"os"

	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	const x, y = 512, 512

	// Generate a background image
	bg := imagick.NewMagickWand()
	bg.SetSize(x, y)
	if err := bg.ReadImage("logo:"); err != nil {
		panic(err)
	}

	// Generate a watermark image
	wm := imagick.NewMagickWand()
	wm.SetSize(x/2, y/2)
	if err := wm.ReadImage("pattern:checkerboard"); err != nil {
		panic(err)
	}

	// Reset/enable alpha channel to 1 (opaque)
	wm.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_SET)

	// Set the current image mask to operate on alpha channel
	prev := wm.SetImageChannelMask(imagick.CHANNEL_ALPHA)

	// equivalent of 50% dissolve
	wm.EvaluateImage(imagick.EVAL_OP_MULTIPLY, 0.5)
	bg.CompositeImageGravity(wm, imagick.COMPOSITE_OP_OVER, imagick.GRAVITY_CENTER)

	wm.SetImageChannelMask(prev)

	if err := bg.DisplayImage(os.Getenv("DISPLAY")); err != nil {
		panic(err)
	}
}
```

**Comment by Zstro** [comment]
Thanks for your help，it's help me!
