### ISSUE TITLE
Some questions of crop PNG

### ISSUE THREAD

**Issue by Zstro** [gographics/imagick#224]
With the same manipulation of the image, the PNG results exceeded expectations:
I rotated a picture fitst and save it.Then,I cropped it.
There are my code:
```
func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	pw := imagick.NewPixelWand()
	err := mw.ReadImage("/root/imagick/image.jpg")
	if  err != nil {
		panic(err)
	}

	pw.SetColor("black")

	fmt.Println(mw.GetImageWidth(), mw.GetImageHeight())
	err = mw.RotateImage(pw, 45)
	if err != nil {
		panic(err)
	}

	err = mw.WriteImage("/root/imagick/imageRotate.png")
	if err != nil {
		panic(err)
	}
}
```
and then cropped it:
```
func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	err := mw.ReadImage("/root/imagick/image.png")
	if  err != nil {
		panic(err)
	}

	fmt.Println(mw.GetImageWidth(), mw.GetImageHeight())

	err = mw.CropImage(1500, 1500, 0, 0)

	err = mw.WriteImage("/root/imagick/imageCrop.png")
	if err != nil {
		panic(err)
	}
}
```
This is the rotation varsion of it
![image](https://user-images.githubusercontent.com/49179307/72663570-121d3780-3a2f-11ea-8b07-b9fdd44c5577.png)
And result of crop 
![imageCrop](https://user-images.githubusercontent.com/49179307/72663617-a6879a00-3a2f-11ea-8475-2b458273c02e.png)
And the same operation to JPG,it's ok
![imageCrop](https://user-images.githubusercontent.com/49179307/72663640-d898fc00-3a2f-11ea-9a1a-fdcbafb2a161.jpg)

I don't know why.

**Comment by justinfx** [comment]
Png stores an image page offset that it will read again later when displaying it. So when you transform the image, you need to do the equivalent of "+repage" from the command line approach

See:
https://www.imagemagick.org/discourse-server/viewtopic.php?t=23149

http://www.imagemagick.org/discourse-server/viewtopic.php?t=31828

https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.ResetImagePage

**Comment by Zstro** [comment]
Thanks for the reply,, It works to me. Thank you!
