### ISSUE TITLE
PSD is resized to JPG, the resized image is still large

### ISSUE THREAD

**Issue by taomin597715379** [gographics/imagick#227]
I am using V2
```go
package main

import (
	"gopkg.in/gographics/imagick.v2/imagick"
	"io/ioutil"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error
	mw := imagick.NewMagickWand()
	err = mw.ReadImage("/tmp/test.psd")
	if err != nil {
		panic(err)
	}
	mw = mw.CoalesceImages()
	mw.TransformImageColorspace(imagick.COLORSPACE_SRGB)
	mw.SetImageFormat("JPEG")
	if err = mw.ResizeImage(width, heigh, imagick.FILTER_LANCZOS, 0.85); err != nil {
		panic(err)
	}
	rb = mw.GetImagesBlob()
	err = ioutil.WriteFile("/tmp/test_1920.jpg", rb, 0666)
	if err != nil {
		panic(err)
	}
}
```
test.psd size is 75M, the resized image is very large, test_1920.jpg size is 50M, Why the resized image is so large, I need help.

**Comment by justinfx** [comment]
What is the final resolution of your jpeg? Also have you tried adjusting the compression quality?
```
mw.SetImageCompressionQuality(60)
```

**Comment by justinfx** [comment]
I've tried testing this out locally with 43M source psd and it converts down to under 350k as a 1920x1080 jpeg. And it gets even smaller when I decrease the compression quality. So I am not sure what other factors are present in your psd file and what actual output resolution you are using.

**Comment by taomin597715379** [comment]
mw.StripImage()，this function seems to solve my problemcan. It effectively reduce the resized image size.

**Comment by taomin597715379** [comment]
I find that some PSD are resized to JPG, the data in the location of JPG image storage APP (0-n) becomes extremely large.  Stripimage() function can effectively reduce the redundant information in JPG's meta.

**Comment by justinfx** [comment]
Nice find. I didn't have the right source images to reproduce the problem.
