### ISSUE TITLE
After the white picture is watermarked, the watermark picture becomes black and white

### ISSUE THREAD

**Issue by jackDiscovery** [gographics/imagick#228]
Hi：
   After upgrading the imagemagick version to 7.0.9-8, after adding a watermark to a white picture, the watermark picture becomes black and white

```
srcImg= imagick.NewMagickWand()
defer srcImg.Destroy()
err := srcImg.ReadImageBlob(srcmageContent)
if err != nil {
	return NewInternalError()
}
waterImg = imagick.NewMagickWand()
defer waterImg.Destroy()
err = waterImg.ReadImageBlob(waterImgContent)
if err != nil {
	return NewInternalError()
}
startX, startY := wm.getStartPos(srcImg, int(wmImageWidth), int(wmImageHeight))
srcImg.CompositeImage(waterImg, imagick.COMPOSITE_OP_OVER, true, int(startX), int(startY))
```
![aferConvert](https://user-images.githubusercontent.com/33868757/75628186-95769f00-5c11-11ea-90cb-e8be5686b7ae.jpg)
![src](https://user-images.githubusercontent.com/33868757/75628189-990a2600-5c11-11ea-83b4-0b503bd501c3.jpg)
![watermark](https://user-images.githubusercontent.com/33868757/75628190-9a3b5300-5c11-11ea-8b80-a12005cbc09f.jpg)

**Comment by jackDiscovery** [comment]
The convert command converts no problem:
`convert mix_cut_white.jpg e9b00a70-e56a-45c6-8d51-312bf94fb7f0.jpg -gravity center -geometry + 5 + 10 -composite base.jpg`

**Comment by justinfx** [comment]
I tested this complete code, using your sample images, and Imagemagick 7.0.9-10. No issues.

```go
package main

import (
	"io/ioutil"

	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	src, _ := ioutil.ReadFile(`white.jpg`)
	water, _ := ioutil.ReadFile(`bike.jpg`)

	srcImg := imagick.NewMagickWand()
	defer srcImg.Destroy()
	err := srcImg.ReadImageBlob(src)
	if err != nil {
		panic(err)
	}
	waterImg := imagick.NewMagickWand()
	defer waterImg.Destroy()
	err = waterImg.ReadImageBlob(water)
	if err != nil {
		panic(err)
	}
	srcImg.CompositeImage(waterImg, imagick.COMPOSITE_OP_OVER, true, 0, 0)
	srcImg.DisplayImage(":0")
}
```

Could be your plugin delegate versions? ie libjpeg?
