### ISSUE TITLE
eps resized to jps, but there are obvious color differences

### ISSUE THREAD

**Issue by taomin597715379** [gographics/imagick#230]
After the vector image(eps) is resized to JPG format image, there are obvious color differences. How can we effectively solve this kind of problem?

I am using V2
```
package main

import (
	"gopkg.in/gographics/imagick.v2/imagick"
	"io/ioutil"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error
	mw := imagick.NewMagickWand()
	err = mw.ReadImage("/tmp/test.eps")
	if err != nil {
		panic(err)
	}
	mw = mw.CoalesceImages()
	mw.TransformImageColorspace(imagick.COLORSPACE_SRGB)
	mw.SetImageFormat("JPEG")
	if err = mw.ResizeImage(width, heigh, imagick.FILTER_LANCZOS, 0.85); err != nil {
		panic(err)
	}
	rb = mw.GetImagesBlob()
	err = ioutil.WriteFile("/tmp/test_1920.jpg", rb, 0666)
	if err != nil {
		panic(err)
	}
}
```
![Lark20200326-211344](https://user-images.githubusercontent.com/16162179/77654561-2e4bd080-6fac-11ea-8cfb-cf735e84fee1.png)

**Comment by taomin597715379** [comment]
![Lark20200326-211426](https://user-images.githubusercontent.com/16162179/77650704-d494d780-6fa6-11ea-90ab-15ddcc5cf030.png)

**Comment by justinfx** [comment]
Is this helpful at all?
https://imagemagick.org/discourse-server/viewtopic.php?t=22565

Does it make a difference of you use `mw.SetColorspace` before reading the image instead of using TransformColorspace?

**Comment by taomin597715379** [comment]
After taking your advice, the situation seems much better than before, I need more tests.

**Comment by taomin597715379** [comment]
The situation is much better than before, the color difference still exists, but it is not so obvious. How can we achieve no color difference?

**Comment by justinfx** [comment]
It can depend on the input image file colorspace / color profile. Going between two colorspaces may or may not produce a shift depending on whether the colors fall within the available gamut of the target colorspace.
Here is another link:
https://www.imagemagick.org/discourse-server/viewtopic.php?t=16464

**Comment by taomin597715379** [comment]
Thanks a lot.
