### ISSUE TITLE
unable to read font `fixed' @ error/annotate.c/RenderFreetype/1315

### ISSUE THREAD

**Issue by luojc0517** [gographics/imagick#232]
trying to convert .wmf to .png
![image](https://user-images.githubusercontent.com/13957771/79529894-58bb1600-80a0-11ea-84d0-f12314a8fd96.png)

**Comment by justinfx** [comment]
Please provide more information about the version of Imagick, the version of ImageMagick, and the platform/distro you are running. This seems like something is wrong with your ImageMagick installation and the availability of ghostscript or fontconfig

**Comment by luojc0517** [comment]
ImageMagick 6.9.4

**Comment by luojc0517** [comment]
It seems that font "fixed" not recognized by ImageMagick , but I do installed "bitmap-fixed-fonts" via yum

**Comment by luojc0517** [comment]
![image](https://user-images.githubusercontent.com/13957771/79546153-81ed9d80-80c4-11ea-874c-c620ed5bbd81.png)

**Comment by justinfx** [comment]
Well that 6.9.4 build is close to 4 years old and it comes from your VM package manager. So it may not have been built with all of the delegates (plugins). Sometimes you need to build it from source. Also it seems long ago others were also having problems with ImageMagick not finding certain fonts:
https://www.imagemagick.org/discourse-server/viewtopic.php?t=20529

**Comment by luojc0517** [comment]
> Well that 6.9.4 build is close to 4 years old and it comes from your VM package manager. So it may not have been built with all of the delegates (plugins). Sometimes you need to build it from source. Also it seems long ago others were also having problems with ImageMagick not finding certain fonts:
> https://www.imagemagick.org/discourse-server/viewtopic.php?t=20529

I copied all windows system fonts to linux, convert in terminal success,

but I got this error when I tried run my main.go:
```
no encode delegate for this image format `WMF' @ error/constitute.c/WriteImage/1167 
```

**Comment by justinfx** [comment]
That error means your ImageMagick install doesn't see wmf encoding support.

Run this: `identify -list format`

Does it list wmf? Do you have libwmf installed? You may have to build ImageMagick with libwmf if all else fails.

**Comment by luojc0517** [comment]
solved
