### ISSUE TITLE
Centos7 development environment configuration

### ISSUE THREAD

**Issue by hailiangchen** [gographics/imagick#235]
I compiled and installed imagemagick-7.0.10-10 to /usr/local/ImageMagick, and 
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/local/ImageMagick/lib"
export PKG_CONFIG_PATH=/usr/local/ImageMagick/lib/pkgconfig/
  
# go run main.go
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: not found -lMagickWand-7.Q16HDRI
collect2: error：ld return 1

![err](https://user-images.githubusercontent.com/12914054/81029906-5be43d80-8eb9-11ea-9899-7a2cb1a5f2a1.png)

![lib](https://user-images.githubusercontent.com/12914054/81029959-95b54400-8eb9-11ea-94c7-ee9c039b7d61.png)

Why did this error occur? What else do I need to do

**Comment by justinfx** [comment]
What is the output of:
```
pkg-config --cflags --libs MagickWand
```

Also can you run this and check the actual link flags Go is using
```
go run -v -x main.go 
```
Maybe it is missing a `-L<path>` and really can't find the location of the Imagemagick libs

**Comment by hailiangchen** [comment]
[root@bogon ~]# pkg-config --cflags --libs MagickWand
-fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/ImageMagick/include/ImageMagick-7  -L/usr/local/ImageMagick/lib -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI

**Comment by justinfx** [comment]
Can you please provide the output from building with `-v - x`? We can check the compiler flags and see exactly where it is looking for your ImageMagick libraries. Maybe they aren't there, or in a non standard location and you need to set LD_LIBRARY_PATH

**Comment by renay1998** [comment]
I have met the same issue as ailiangchen's , Can you please give some advice to fix it? @justinfx 

OS:Centos7
GO:1.11.4

[  ]$ pkg-config --cflags --libs MagickWand
-I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -lMagickWand-7.Q16HDRI -L/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/lib -lMagickCore-7.Q16HDRI  



the attached file is go-build information

**Comment by justinfx** [comment]
Just like I requested in my previous reply, please show me the verbose output from the build. It is going to tell toy. A bunch of paths and then you can confirm that they all exist. Also you may need to ensure that your `LD_LIBRARY_PATH` is set to include the library path containing the ImageMagick libs

**Comment by renay1998** [comment]
[   ]$ echo $LD_LIBRARY_PATH 
/opt/cross-gcc-4.9.3-n64-loongson-rc6.1/usr/x86_64-unknown-linux-gnu/mips64el-loongson-linux/lib/:/opt/cross-gcc-4.9.3-n64-loongson-rc6.1/usr/lib:/opt/arm-ca53-linux-gnueabihf-6.4/lib/:/home06/226922/go/src/github.com/ImageMagick/ImageMagick/lib

**Comment by renay1998** [comment]
sorry failed to attach verbos output file，I’ll add two comment to display it

[       ]$ go build -v -x gopkg.in/gographics/imagick.v3/imagick/
WORK=/tmp/go-build118783216
runtime/cgo
mkdir -p $WORK/b027/
cd /opt/go1.11.4/src/runtime/cgo
CGO_LDFLAGS='"-Wl,-Bstatic" "-lMagickWand-7.Q16HDRI" "-L/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/lib" "-lMagickCore-7.Q16HDRI" "-ljbig" "-ltiff" "-ljpeg" "-lwebp" "-llzma" "-lfftw3" "-lbz2" "-lgomp" "-Wl,-Bdynamic" "-llcms2" "-llqr-1" "-lglib-2.0" "-lpng12" "-lxml2" "-lz" "-lm" "-ldl" "-lpthread"' /opt/go1.11.4/pkg/tool/linux_amd64/cgo -objdir $WORK/b027/ -importpath runtime/cgo -import_runtime_cgo=false -import_syscall=false -- -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror ./cgo.go
cd $WORK
gcc -fno-caret-diagnostics -c -x c - || true
gcc -Qunused-arguments -c -x c - || true
gcc -fdebug-prefix-map=a=b -c -x c - || true
gcc -gno-record-gcc-switches -c -x c - || true
cd $WORK/b027
TERM='dumb' gcc -I /opt/go1.11.4/src/runtime/cgo -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I ./ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o ./_x001.o -c _cgo_export.c
TERM='dumb' gcc -I /opt/go1.11.4/src/runtime/cgo -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I ./ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o ./_x002.o -c cgo.cgo2.c
cd /opt/go1.11.4/src/runtime/cgo

**Comment by renay1998** [comment]
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x003.o -c gcc_context.c
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x004.o -c gcc_fatalf.c
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x005.o -c gcc_libinit.c
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x006.o -c gcc_linux_amd64.c
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x007.o -c gcc_mmap.c
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x008.o -c gcc_setenv.c
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x009.o -c gcc_sigaction.c
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/

**Comment by renay1998** [comment]
-I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x011.o -c gcc_util.c
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I $WORK/b027/ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o $WORK/b027/_x012.o -c gcc_amd64.S
cd $WORK/b027
TERM='dumb' gcc -I /opt/go1.11.4/src/runtime/cgo -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -I ./ -I/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Wall -Werror -o ./_cgo_main.o -c _cgo_main.c
cd /opt/go1.11.4/src/runtime/cgo
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b027=/tmp/go-build -o $WORK/b027/_cgo_.o $WORK/b027/_cgo_main.o $WORK/b027/_x001.o $WORK/b027/_x002.o $WORK/b027/_x003.o $WORK/b027/_x004.o $WORK/b027/_x005.o $WORK/b027/_x006.o $WORK/b027/_x007.o $WORK/b027/_x008.o $WORK/b027/_x009.o $WORK/b027/_x010.o $WORK/b027/_x011.o $WORK/b027/_x012.o -Wl,-Bstatic -lMagickWand-7.Q16HDRI -L/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/lib -lMagickCore-7.Q16HDRI -ljbig -ltiff -ljpeg -lwebp -llzma -lfftw3 -lbz2 -lgomp -Wl,-Bdynamic -llcms2 -llqr-1 -lglib-2.0 -lpng12 -lxml2 -lz -lm -ldl -lpthread
# runtime/cgo
/usr/bin/ld: cannot find -lMagickWand-7.Q16HDRI
collect2: ld returned 1 exit status

**Comment by justinfx** [comment]
```
-Wl,-Bstatic -lMagickWand-7.Q16HDRI
```

This looks like it is trying to statically link against ImageMagick. And if you didn't explicitely set any Go build flags to tell it to link static then it may be coming from the pkg-config of ImageMagick. Can you verify that you actually have static libs (ending in `.a`) in this location?

```
/opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/sysroot/home06/226922/go/src/github.com/ImageMagick/ImageMagick/lib
```
That seems like a strange installation path for ImageMagick, and that is what pkg-config apparently was giving you as the `-L<library path>`. When it is trying to static link, the `LD_LIBRARY_PATH` doesn't matter. So I am wondering if something is wrong with the ImageMagick installation and the pkg-config values that it is telling the Go build. 
If you can find the correct location of the ImageMagick libraries you can build it manually as per the README:

 ```
export CGO_CFLAGS="-i/path/to/includes"
export CGO_LDFLAGS="-L/path/to/libs -lMagickWand -lMagickCore"
go build -tags no_pkgconfig
```

**Comment by renay1998** [comment]
I used `pkg-config --libs MagickWand MagickCore` to set CGO_CFLAGS and CGO_LDFLAGS and did not use -tags no_pkgconfig  before

export CGO_CFLAGS="`pkg-config --cflags MagickWand MagickCore`"
export CGO_LDFLAGS="\
-Wl,-Bstatic \
    `pkg-config --libs MagickWand MagickCore` \
     -ljbig -ltiff -ljpeg -lwebp -llzma \
-Wl,-Bdynamic \
    -llcms2 -llqr-1 -lglib-2.0 -lpng12 -lz -lm -ldl \
"

But as you know, the path of 'pk-config --cflags MagickWand MagickCore' output make me confused, because the path did not exists. And I review the ImageMagick installation，there should be no wrong with it . here are some information about it:

[ ImageMagick]$ ll        					// ImageMagick is configure --prefix directory, ImageMagick-7.0.10-23 is the source code directory
total 13648
drwxr-xr-x  7 226922 domain users     4096 Jul 21 16:46 ImageMagick
drwxr-xr-x 18 226922 domain users     4096 Jul 21 16:42 ImageMagick-7.0.10-23
-rw-r--r--  1 226922 domain users 13965321 Jul 13 16:30 ImageMagick-7.0.10-23.tar.gz
[ ImageMagick]$ ll
total 13648
drwxr-xr-x  7 226922 domain users     4096 Jul 21 16:46 ImageMagick
drwxr-xr-x 18 226922 domain users     4096 Jul 21 16:42 ImageMagick-7.0.10-23
-rw-r--r--  1 226922 domain users 13965321 Jul 13 16:30 ImageMagick-7.0.10-23.tar.gz
[ ImageMagick]$ ll ImageMagick
total 20
drwxr-xr-x 2 226922 domain users 4096 Jul 21 16:46 bin
drwxr-xr-x 3 226922 domain users 4096 Jul 21 16:46 etc
drwxr-xr-x 3 226922 domain users 4096 Jul 21 16:46 include
drwxr-xr-x 4 226922 domain users 4096 Jul 21 16:46 lib
drwxr-xr-x 5 226922 domain users 4096 Jul 21 16:46 share
[ ImageMagick]$ ll ImageMagick/lib/
total 56316
drwxr-xr-x 3 226922 domain users     4096 Jul 21 16:46 ImageMagick-7.0.10
-rw-r--r-- 1 226922 domain users  7180884 Jul 21 16:46 libMagick++-7.Q16HDRI.a
-rwxr-xr-x 1 226922 domain users     1280 Jul 21 16:46 libMagick++-7.Q16HDRI.la
lrwxrwxrwx 1 226922 domain users       30 Jul 21 16:46 libMagick++-7.Q16HDRI.so -> libMagick++-7.Q16HDRI.so.4.0.0
lrwxrwxrwx 1 226922 domain users       30 Jul 21 16:46 libMagick++-7.Q16HDRI.so.4 -> libMagick++-7.Q16HDRI.so.4.0.0
-rwxr-xr-x 1 226922 domain users  3223359 Jul 21 16:46 libMagick++-7.Q16HDRI.so.4.0.0
-rw-r--r-- 1 226922 domain users 25875536 Jul 21 16:46 libMagickCore-7.Q16HDRI.a
-rwxr-xr-x 1 226922 domain users     1125 Jul 21 16:46 libMagickCore-7.Q16HDRI.la
lrwxrwxrwx 1 226922 domain users       32 Jul 21 16:46 libMagickCore-7.Q16HDRI.so -> libMagickCore-7.Q16HDRI.so.7.0.0
lrwxrwxrwx 1 226922 domain users       32 Jul 21 16:46 libMagickCore-7.Q16HDRI.so.7 -> libMagickCore-7.Q16HDRI.so.7.0.0
-rwxr-xr-x 1 226922 domain users 13259148 Jul 21 16:46 libMagickCore-7.Q16HDRI.so.7.0.0
-rw-r--r-- 1 226922 domain users  5190854 Jul 21 16:46 libMagickWand-7.Q16HDRI.a
-rwxr-xr-x 1 226922 domain users     1220 Jul 21 16:46 libMagickWand-7.Q16HDRI.la
lrwxrwxrwx 1 226922 domain users       32 Jul 21 16:46 libMagickWand-7.Q16HDRI.so -> libMagickWand-7.Q16HDRI.so.7.0.0
lrwxrwxrwx 1 226922 domain users       32 Jul 21 16:46 libMagickWand-7.Q16HDRI.so.7 -> libMagickWand-7.Q16HDRI.so.7.0.0
-rwxr-xr-x 1 226922 domain users  2902312 Jul 21 16:46 libMagickWand-7.Q16HDRI.so.7.0.0
drwxr-xr-x 2 226922 domain users     4096 Jul 21 16:46 pkgconfig

**Comment by renay1998** [comment]
After I saw you advice, I set CGO_CFLAGS and CGO_LDFLAGS like this:

[ ImageMagick]$ echo $CGO_CFLAGS
-I/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include

[ ImageMagick]$ echo $CGO_LDFLAGS
-L/home06/226922/go/src/github.com/ImageMagick/ImageMagick/lib -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI

[ ImageMagick]$ go build -tags no_pkgconfig -v -x /home06/226922/go/src/gopkg.in/gographics/imagick.v3/imagick/
WORK=/tmp/go-build475761366
gopkg.in/gographics/imagick.v3/imagick
mkdir -p $WORK/b001/
cd /home/226922/go/src/gopkg.in/gographics/imagick.v3/imagick
CGO_LDFLAGS='"-L/home06/226922/go/src/github.com/ImageMagick/ImageMagick/lib" "-lMagickWand-7.Q16HDRI" "-lMagickCore-7.Q16HDRI"' /opt/go1.11.4/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath gopkg.in/gographics/imagick.v3/imagick -- -I $WORK/b001/ -I/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include ./affine_matrix.go ./align_type.go ./alpha_channel_type.go ./channel_features.go ./channel_statistics.go ./channel_type.go ./clip_path_units.go ./colorspace_type.go ./composite_operator.go ./compression_type.go ./conversions.go ./decoration_type.go ./dispose_type.go ./distort_image_method.go ./dither_method.go ./draw_info.go ./drawing_wand.go ./drawing_wand_exception.go ./endian_type.go ./evaluate_operator.go ./exception_info.go ./exception_type.go ./fill_rule.go ./filter_type.go ./geometry_flags.go ./geometry_info.go ./gravity_type.go ./image.go ./image_info.go ./image_layer_method.go ./image_type.go ./imagick.go ./index_packet.go ./interlace_type.go ./interpolate_pixel_method.go ./kernel_info.go ./kernel_info_type.go ./kernel_normalize_type.go ./line_cap.go ./line_join.go ./magick_core_env.go ./magick_function.go ./magick_version.go ./magick_wand.go ./magick_wand_env.go ./magick_wand_exception.go ./magick_wand_image.go ./magick_wand_prop.go ./memory.go ./metric_type.go ./montage_mode.go ./morphology_method.go ./noise_type.go ./orientation_type.go ./paint_method.go ./pixel_info.go ./pixel_iterator.go ./pixel_iterator_exception.go ./pixel_packet.go ./pixel_wand.go ./pixel_wand_exception.go ./point_info.go ./preview_type.go ./quantum.go ./rectangle_info.go ./rendering_intent.go ./resolution_type.go ./resource_type.go ./sparse_color_method.go ./statistic_type.go ./storage_type.go ./stretch_type.go ./style_type.go ./virtual_pixel_method.go
# gopkg.in/gographics/imagick.v3/imagick
/home/226922/go/src/gopkg.in/gographics/imagick.v3/imagick/affine_matrix.go:8:35: error: MagickWand/MagickWand.h: No such file or directory

**Comment by renay1998** [comment]
Go build coms across wrong information with .h can not be found in CGO_CFLAGS , so I edited the CGO_CFLAGS=export CGO_CFLAGS="-I/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7"  , to make the MagcikWand/MagickWand.h can be found in this path， but After go build，I got another error：

[ ImageMagick]$ go build -tags no_pkgconfig -v -x /home06/226922/go/src/gopkg.in/gographics/imagick.v3/imagick/
WORK=/tmp/go-build465416090
cat /home/226922/.cache/go-build/f0/f04d210e370b94ceaed1dc33fcadda3dc4f13a787885806ed7591fa4fb238c78-d  # internal
# gopkg.in/gographics/imagick.v3/imagick
In file included from /home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickWand/MagickWand.h:29,
                 from /home/226922/go/src/gopkg.in/gographics/imagick.v3/imagick/affine_matrix.go:8:
/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/magick-config.h:63:3: warning: #warning "you should set MAGICKCORE_QUANTUM_DEPTH to sensible default set it to configure time default"
/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/magick-config.h:64:3: warning: #warning "this is an obsolete behavior please fix your makefile"
/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/magick-config.h:86:3: warning: #warning "you should set MAGICKCORE_HDRI_ENABLE to sensible default set it to configure time default"
/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/magick-config.h:87:3: warning: #warning "this is an obsolete behavior please fix yours makefile"
.
.
.
# gopkg.in/gographics/imagick.v3/imagick
In file included from /home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/MagickCore.h:29,
                 from /home/226922/go/src/gopkg.in/gographics/imagick.v3/imagick/channel_features.go:8:
/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/magick-config.h:63:3: warning: #warning "you should set MAGICKCORE_QUANTUM_DEPTH to sensible default set it to configure time default"
/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/magick-config.h:64:3: warning: #warning "this is an obsolete behavior please fix your makefile"
/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/magick-config.h:86:3: warning: #warning "you should set MAGICKCORE_HDRI_ENABLE to sensible default set it to configure time default"
/home06/226922/go/src/github.com/ImageMagick/ImageMagick/include/ImageMagick-7/MagickCore/magick-config.h:87:3: warning: #warning "this is an obsolete behavior please fix yours makefile"
.
.
.

**Comment by renay1998** [comment]
I am not familiar with C/C++,and failed to get enough from the Internet,  so thank you so much for more advice

**Comment by renay1998** [comment]
I find someone suggest to add compile options -DMAGICKCORE_QUANTUM_DEPTH= -DMAGICKCORE_HDRI_ENABLE= , but he use C++ to compile.When should I use these option , when ./configure or another step ?

**Comment by justinfx** [comment]
Can you confirm which branch you have checked out, for `/home/226922/go/src/gopkg.in/gographics/imagick.v3/imagick`? It should be the IM-7 branch and not master.

If you are building your own ImageMagick7 then yea those flags are passed as defines during the `configure`. So I can't really be sure what the state of your ImageMagick7 custom build is. But I think I have given enough for you to work with here, where you have to use the `-tags no_pkgconfig` OR you can set `PKG_CONFIG_PATH` to point and the `lib/pkg-config` location in your ImageMagick dist to automatically pick it up. It is possible that you were never pointing properly at your custom ImageMagic7 build?

**Comment by renay1998** [comment]
The imagick version is v3.2.0

**Comment by justinfx** [comment]
Is this still an issue? After re-reading this, I realized that you had said you were NOT using `-tags no_pkgconfig` but you do need to use that tag if you are going to set your own cgo flags. Otherwise it will keep trying to use its own default pkgconfig command.
