### ISSUE TITLE
EPS image resized, but it appears distortion

### ISSUE THREAD

**Issue by taomin597715379** [gographics/imagick#238]
I am using V2
```
func TestImageResizeEPS() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error
	mw := imagick.NewMagickWand()
	mw.SetResolution(200, 200)
	mw.SetColorspace(imagick.COLORSPACE_SRGB)
	err = mw.ReadImage("/tmp/abc.eps")
	if err != nil {
		panic(err)
	}
	mw = mw.CoalesceImages()
	mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_DEACTIVATE)
	err = mw.SetImageCompressionQuality(DefaultImageQuality)
	if err != nil {
		panic(err)
	}
	mw.StripImage()
	mw.TrimImage(0)

	// For EPS vector image, If the width and height of the picture are too small, it will be enlarged
	width, height := option.ScaleImageSize(mw.GetImageWidth(), mw.GetImageHeight())
	if width != mw.GetImageWidth() || height != mw.GetImageHeight() {
		err = mwm.ScaleImage(width, height)
	}

	err = mw.SetImageFormat("JPEG")
	if err != nil {
		panic(err)
	}
	originalHeight := mw.GetImageHeight()
	originalWidth := mw.GetImageWidth()

	// Calculated width and height of resize
	w, h := option.GetResizeByWidthHeight(int64(originalWidth), int64(originalHeight), "keepratio", maxCompressEdge, maxCompressEdge)

	if err = imw.ResizeImage(uint(w), uint(h), imagick.FILTER_LANCZOS, 0.85); err != nil {
		return
	}
	if err = mw.WriteImage("/tmp/abc.jpg"); err != nil {
		panic(err)
	}
}
```
After resized, the picture will be distorted

**Comment by taomin597715379** [comment]
![2U405l35DGADL3cYynpSU4hDJCFjkxbCGj6F1QlJf  转换](https://user-images.githubusercontent.com/16162179/82744999-0dd4a280-9db2-11ea-9dc5-5278d6319bd2.jpg)

**Comment by taomin597715379** [comment]
EPS original image cannot be uploaded here.

**Comment by justinfx** [comment]
Is it any EPS source image or a specific one where you see distortion? Also, can you update your example to be self contained instead of referencing helper functions that aren't defined? That way I can properly give it a try on an EPS file.

**Comment by taomin597715379** [comment]
Now some eps pictures will show this situation, others will not.

**Comment by taomin597715379** [comment]
OK, I update example code

**Comment by taomin597715379** [comment]
How can I send you an original picture of EPS in question? So you can more effectively solve the problem. email?

**Comment by taomin597715379** [comment]
```
func TestImageResizeEPS() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error
	mw := imagick.NewMagickWand()
	mw.SetResolution(200, 200)
	mw.SetColorspace(imagick.COLORSPACE_SRGB)
	err = mw.ReadImage("/tmp/abc.eps")
	if err != nil {
		panic(err)
	}
	mw = mw.CoalesceImages()
	mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_DEACTIVATE)
	err = mw.SetImageCompressionQuality(DefaultImageQuality)
	if err != nil {
		panic(err)
	}
	mw.StripImage()
	mw.TrimImage(0)

	// For EPS vector image, If the width and height of the picture are too small, it will be enlarged
	width, height := ScaleImageSize(mw.GetImageWidth(), mw.GetImageHeight())
	if width != mw.GetImageWidth() || height != mw.GetImageHeight() {
		err = mwm.ScaleImage(width, height)
	}

	err = mw.SetImageFormat("JPEG")
	if err != nil {
		panic(err)
	}
	originalHeight := mw.GetImageHeight()
	originalWidth := mw.GetImageWidth()

	// Calculated width and height of resize
	// 1280 means the longest side
	w, h := GetResizeByWidthHeight(int64(originalWidth), int64(originalHeight), "keepratio", 1280, 1280)

	if err = imw.ResizeImage(uint(w), uint(h), imagick.FILTER_LANCZOS, 0.85); err != nil {
		return
	}
	if err = mw.WriteImage("/tmp/abc.jpg"); err != nil {
		panic(err)
	}
}

func ScaleImageSize(originalWidth, originalHeight uint) (width, height uint) {
	width = originalWidth
	height = originalHeight
	if originalWidth < 1280 && originalHeight < 1280 {
		ratioWidth := utils.FormatFloat64(float64(2560)/float64(originalWidth), 3)
		ratioHeight := utils.FormatFloat64(float64(2560)/float64(originalHeight), 3)
		if ratioWidth < ratioHeight {
			width = 2560
			height = uint(ratioWidth * float64(originalHeight))
		} else {
			height = 2560
			width = uint(ratioHeight * float64(originalWidth))
		}
	}
	return
}

func GetResizeByWidthHeight(originalWidth, originalHeight int64, method string, maxWidth, maxHeight int64) (width, height int64) {
	var ratio, ratioWidth, ratioHeight float64
	width, height = originalWidth, originalHeight
	switch method {
	case "keepratio":
		ratioWidth = utils.FormatFloat64(float64(maxWidth)/float64(originalWidth), 3)
		ratioHeight = utils.FormatFloat64(float64(maxHeight)/float64(originalHeight), 3)
		if ratioHeight < ratioWidth {
			if ratioHeight < 1 {
				height = maxHeight
				width = int64(ratioHeight * float64(originalWidth))
			}
		} else {
			if ratioWidth < 1 {
				width = maxWidth
				height = int64(ratioWidth * float64(originalHeight))
			}
		}
		return
	}
	return
}
```

**Comment by justinfx** [comment]
How big is the source EPS image when it is zipped or tar.gz? Can you upload a compressed source image that is smaller than 25mb?

If the problem happens on some eps files and not others, then it is likely a problem either with your Ghostscript delegate library, or ImageMagick, and not the bindings.

**Comment by taomin597715379** [comment]
[abc.zip](https://github.com/gographics/imagick/files/4673168/abc.zip)

**Comment by taomin597715379** [comment]
You can try this eps picture.

**Comment by taomin597715379** [comment]
I used AI software to export this picture to JPG format, found that there was also a problem.

**Comment by justinfx** [comment]
Ok, well I asked for a completely standalone reproduction of your code. But your last example still contains custom functions, and missing and wrongly named variables.

> I used AI software to export this picture to JPG format, found that there was also a problem.
Are you saying that you found an issue with your source EPS file in other software?

**Comment by taomin597715379** [comment]
```
func TestImageResizeEPS() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error
	mw := imagick.NewMagickWand()
	mw.SetResolution(200, 200)
	mw.SetColorspace(imagick.COLORSPACE_SRGB)
	err = mw.ReadImage("/tmp/abc.eps")
	if err != nil {
		panic(err)
	}
	mw = mw.CoalesceImages()
	mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_DEACTIVATE)
	err = mw.SetImageCompressionQuality(DefaultImageQuality)
	if err != nil {
		panic(err)
	}
	mw.StripImage()
	mw.TrimImage(0)

	// For EPS vector image, If the width and height of the picture are too small, it will be enlarged
	width, height := ScaleImageSize(mw.GetImageWidth(), mw.GetImageHeight())
	if width != mw.GetImageWidth() || height != mw.GetImageHeight() {
		err = mw.ScaleImage(width, height)
	}

	err = mw.SetImageFormat("JPEG")
	if err != nil {
		panic(err)
	}
	originalHeight := mw.GetImageHeight()
	originalWidth := mw.GetImageWidth()

	// Calculated width and height of resize
	// 1280 means the longest side
	w, h := GetResizeByWidthHeight(int64(originalWidth), int64(originalHeight), "keepratio", 1280, 1280)

	if err = mw.ResizeImage(uint(w), uint(h), imagick.FILTER_LANCZOS, 0.85); err != nil {
		return
	}
	if err = mw.WriteImage("/tmp/abc.jpg"); err != nil {
		panic(err)
	}
}

func ScaleImageSize(originalWidth, originalHeight uint) (width, height uint) {
	width = originalWidth
	height = originalHeight
	if originalWidth < 1280 && originalHeight < 1280 {
		ratioWidth := FormatFloat64(float64(2560)/float64(originalWidth), 3)
		ratioHeight := FormatFloat64(float64(2560)/float64(originalHeight), 3)
		if ratioWidth < ratioHeight {
			width = 2560
			height = uint(ratioWidth * float64(originalHeight))
		} else {
			height = 2560
			width = uint(ratioHeight * float64(originalWidth))
		}
	}
	return
}

func GetResizeByWidthHeight(originalWidth, originalHeight int64, method string, maxWidth, maxHeight int64) (width, height int64) {
	var ratio, ratioWidth, ratioHeight float64
	width, height = originalWidth, originalHeight
	switch method {
	case "keepratio":
		ratioWidth = FormatFloat64(float64(maxWidth)/float64(originalWidth), 3)
		ratioHeight = FormatFloat64(float64(maxHeight)/float64(originalHeight), 3)
		if ratioHeight < ratioWidth {
			if ratioHeight < 1 {
				height = maxHeight
				width = int64(ratioHeight * float64(originalWidth))
			}
		} else {
			if ratioWidth < 1 {
				width = maxWidth
				height = int64(ratioWidth * float64(originalHeight))
			}
		}
		return
	}
	return
}

func FormatFloat64(f float64, precise int) float64 {
	fs := strconv.FormatFloat(f, 'f', precise, 64)
	fp, _ := strconv.ParseFloat(fs, 64)
	return fp
}
```
you can try again, I changed the code.

**Comment by taomin597715379** [comment]
I'm Sorry, there is no problem for AI tool to export EPS of small size to JPG image of a certain size. So it is not the problem of image, Or the code does not deal with EPS of small size perfectly

**Comment by justinfx** [comment]
The best thing you can do when you have an issue like this is to really reduce your code to the smallest example that still reproduces the problem. That way you can know exactly what the factors are that are contributed to the unwanted final image.

First we can see that this reduced version of your code does produce an image with unwanted black background components:

```go
package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()
	var err error
	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	mw.SetResolution(200, 200)
	mw.SetColorspace(imagick.COLORSPACE_SRGB)
	err = mw.ReadImage("/tmp/abc.eps")
	if err != nil {
		panic(err)
	}

	err = mw.ScaleImage(2356, 2560)
	if err != nil {
		panic(err)
	}

	if err = mw.ResizeImage(1178, 1280, imagick.FILTER_LANCZOS); err != nil {
		panic(err)
	}

	if err = mw.WriteImage("/tmp/abc.jpg"); err != nil {
		panic(err)
	}
}
```

We can also confirm that the same problem happens with the `convert` command line imagemagick tool:

```
convert -colorspace sRGB -density 200 /tmp/abc.eps -resize '512x512' /tmp/abc.jpg
display /tmp/abc.jpg
```

This proves that its an issue with the image conversion options and not a problem specific to this Go imagick binding layer. So that being said, some Googling on converting EPS to jpg shows that this issue is related to the transparency being automatically forced to black. Examples show that flattening the image after the resize resolves it, before writing it out to a jpg with does not support transparency:

```
convert -colorspace sRGB -density 200 /tmp/abc.eps -resize '512x512' -flatten /tmp/abc.jpg
display /tmp/abc.jpg
```

The equivalent change to your code is to flatten the layers just before writing out the jpeg:

```go
	mw2 := mw.MergeImageLayers(imagick.IMAGE_LAYER_FLATTEN)
	defer mw2.Destroy()

	if err = mw2.WriteImage("/tmp/abc.jpg"); err != nil {
		panic(err)
	}
```

**Comment by taomin597715379** [comment]
Thank you for your advice, I'll take it. I'm very confused. Isn't it possible to enlarge a vector map infinitely? Why does the image become blurred after enlargeing and then compress.

**Comment by taomin597715379** [comment]
It seems that ImageMagick can't handle the enlargement of vector map.

**Comment by justinfx** [comment]
I can't speak to the quality of the resizing and rasterizing. That would require more testing, and your original question only said "distortion" so I focused on the alpha artifacts. Maybe there are other ways to fix the resize quality. But it would just be a matter of searching how to do it with ImageMagick as opposed to being an issue with the bindings.

**Comment by taomin597715379** [comment]
The biggest problem in our project at present is the small EPS image is compressed into JPG image, the JPG image will be blurred，we have tried the common parameters of vector image compression, but we still can't solve this problem. Could you give me some advice?

**Comment by justinfx** [comment]
As far as I understand it, because imagemagick uses a delegate plugin system, ghostscript is responsible for reading in the image into an in-memory format, using your load-time options. Once its loaded I believe it is rasterized at that point.   So your main control over source quality is to set a higher density before reading it in:

```go
// blurry when resizing larger
mw.SetResolution(200, 200)
// retains a lot of detail in the grass
mw.SetResolution(3000, 3000)
```

Aside from that, the various resize filters that you choose will have different effects depending on whether you are scaling up or scaling down, and the type of image.

**Comment by taomin597715379** [comment]
I have a bad case here. This EPS image will be blurred after being compressed into jpg. Could you help me?
[bad_case.zip](https://github.com/gographics/imagick/files/4716989/bad_case.zip)

**Comment by justinfx** [comment]
Look, I am not sure what to really tell you beyond my previous suggestions to increase the density before loading and experiment with resize filters to balance between quality/sharpness. 
I'm not an expert in vector graphics, but I looked at this bad_case eps in 3 different apps on linux aside from the imagemagick conversion:
* gv
* evince
* gimp
All of these apps produced aliased and blocky graphics when the size was increased. Then I looked at the actual source of the eps file, and I see that it has embedded jpg graphic blob data. Are you 100% certain that this eps file is all vector graphics? Just because it was created in Adobe Illustrator doesn't mean the author used only vector graphics. They have likely embedded jpeg graphs that are already rasterized. So there is nothing you can do about that when you try to scale it up beyond its original resolution. You are either going to get aliasing or blurring depending on the resize filter.
Does this explain why the bad_case looks poor in your tests?

**Comment by taomin597715379** [comment]
I got it. Thank you for your advice and help
