### ISSUE TITLE
no WriteImageBlob? 

### ISSUE THREAD

**Issue by jojo921** [gographics/imagick#239]

**Comment by justinfx** [comment]
Is that part of the ImageMagick C API? Can you point me to the documentation?

We have these which let you read in an image from a blob of data:
https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.ReadImageBlob

Get an image blob of data from a wand:
https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.GetImageBlob

And write a wand out to a file:
https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.WriteImage

What kind of functionality is missing?

**Comment by jojo921** [comment]
thanks,  GetImageBlob, got it!
