### ISSUE TITLE
win10 exit status 3221225785

### ISSUE THREAD

**Issue by tengge1** [gographics/imagick#240]
os: win10

gcc version: gcc (Rev3, Built by MSYS2 project) 10.1.0

pacman version:  Pacman v5.2.1 - libalpm v12.0.1

imagemagick version:  mingw-w64-x86_64-imagemagick-7.0.10.11-2

```golang
package main

import (
	imagick "gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
}
```

When I run this code with vscode, I got:

```
exit status 3221225785
Process exiting with code: 1
```

Win I debug this code, I got

```
API server listening at: 127.0.0.1:29979
could not launch process: Process 1652 has exited with status 3221225785
could not remove d:\tegola\utils\imagick\__debug_bin: remove d:\tegola\utils\imagick\__debug_bin: Access is denied.
Process exiting with code: 1
```

**Comment by justinfx** [comment]
Does your test main application work from a command line go build? I don't know what is required to set up Vscode on Windows for a cgo project, so that it finds the C dependencies properly.

**Comment by tengge1** [comment]
It is OK when I use cmd on WIndows.

Run `go build .`, I can create `imagick.exe` successfully, and `imagick.exe`, works fine.

I think it is a problem of VSCode. Thank you very much.

**Comment by justinfx** [comment]
Thanks for confirming!
