### ISSUE TITLE
Masking images in v3 

### ISSUE THREAD

**Issue by abeMedia** [gographics/imagick#245]
Since `SetImageClipMask` is no longer available, how can we mask an image?

I have 2 images that are PNGs with transparent backgrounds and one of them needs to be masked before creating a composite of both. I've tried copying the approach in [examples/clipmask/main.go](https://github.com/gographics/imagick/blob/v3.3.0/examples/clipmask/main.go), however this doesn't work due to the transparent background (the transparent background ends up being black with the odd random white square). 

This is how I was doing it in v2:

```go
package main

import (
	"gopkg.in/gographics/imagick.v2/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	front := imagick.NewMagickWand()
	defer front.Destroy()

	back := imagick.NewMagickWand()
	defer back.Destroy()

	mask := imagick.NewMagickWand()
	defer mask.Destroy()

	if err := front.ReadImage("front.png"); err != nil {
		panic(err)
	}

	if err := back.ReadImage("back.png"); err != nil {
		panic(err)
	}

	if err := mask.ReadImage("mask.png"); err != nil {
		panic(err)
	}

	if err := front.SetImageClipMask(mask); err != nil {
		panic(err)
	}

	if err := front.CompositeImage(back, imagick.COMPOSITE_OP_OVER, 0, 0); err != nil {
		panic(err)
	}

	if err := front.WriteImage("result.png"); err != nil {
		panic(err)
	}
}
```

**Comment by justinfx** [comment]
I'm not sure what your source images are like, but if I just take the existing im-7 clipmask example and make the background tile_water have a random alpha channel, a few changes like the following seem to work for me:

```go
package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	bg := imagick.NewMagickWand()
	fg := imagick.NewMagickWand()
	mask := imagick.NewMagickWand()

	bg.SetSize(400, 400)
	fg.SetSize(400, 400)
	mask.SetSize(400, 400)
	
	// This version of the water bg has an alpha channel
	if err := bg.ReadImage("tile:/tmp/tile_water.png"); err != nil {
		panic(err)
	}
	if err := fg.ReadImage("tile:/tmp/tile_disks.jpg"); err != nil {
		panic(err)
	}
	if err := mask.ReadImage("tile:/tmp/mask_bite.png"); err != nil {
		panic(err)
	}

	// Fill in the background transparency with a solid color
	//color := imagick.NewMagickWand()
	//color.SetSize(400, 400)
	//if err := color.ReadImage("xc:red"); err != nil {panic(err)}
	//bg.CompositeImage(color, imagick.COMPOSITE_OP_DST_OVER, false, 0, 0)

	// Set the mask image as the alpha of our foreground element
	fg.CompositeImage(mask, imagick.COMPOSITE_OP_COPY_ALPHA, false, 0, 0)

	// foreground over background
	bg.CompositeImage(fg, imagick.COMPOSITE_OP_OVER, false, 0, 0)

	bg.WriteImage("/tmp/clip_out.jpg")
}
```

![clip_out](https://user-images.githubusercontent.com/282566/95004411-2483e380-0647-11eb-96d3-6660fbc13769.jpg)

**Comment by abeMedia** [comment]
In case anyone else stumbles across this I thought I'd share how I ended up solving it at the time. Copying the alpha didn't work as I wanted to preserve transparency in areas that might not be cut out by the mask.

Using a mask that was transparent in all the areas where I wanted to cut out the back image I multiplied the back image by it. This way the areas that already were transparent weren't affected as `n * 0 = 0`. 

```go
package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	front := imagick.NewMagickWand()
	defer front.Destroy()

	back := imagick.NewMagickWand()
	defer back.Destroy()

	mask := imagick.NewMagickWand()
	defer mask.Destroy()

	if err := front.ReadImage("front.png"); err != nil {
		panic(err)
	}

	if err := back.ReadImage("back.png"); err != nil {
		panic(err)
	}

	if err := mask.ReadImage("mask.png"); err != nil {
		panic(err)
	}
  
	if err := back.CompositeImage(mask, imagick.COMPOSITE_OP_MULTIPLY, false, 0, 0); err != nil {
		return nil, err
	}

	if err := back.CompositeImage(front, imagick.COMPOSITE_OP_OVER, false, 0, 0); err != nil {
		panic(err)
	}

	if err := back.WriteImage("result.png"); err != nil {
		panic(err)
	}
}
```

**Comment by pfitzner** [comment]
The C API defines 

`MagickBooleanType MagickSetImageMask(MagickWand *wand, const PixelMask type,const MagickWand *clip_mask)`

which, for some reason, never made it into the go bindings. Does anyone know why?

**Comment by justinfx** [comment]
Is it related to this SO post which I just stumble across? https://stackoverflow.com/questions/67141982/magickwand-7-api-how-to-port-magicksetimageclipmask-call

It is probably just an oversight that it wasn't defined in the v3 bindings. We don't have a nice automated approach to generating the API so its easy to miss things. Feel free to add it in a PR!

**Comment by pfitzner** [comment]
Hello Justin,

I'm really not a GitHub person at all, so such a pull request is beyond my humble abilities.

I was the one who posed this question, and the response led me to look in the C API rather than the go bindings.

If you get around to updating rev. 3, please consider adding this call.

Thanks,

Bob Schaaf

**Comment by justinfx** [comment]
@pfitzner alright well if you can't do a fix and having the API call will help you out, then I can try to add it tomorrow for you.

**Comment by pfitzner** [comment]
Bless you!

**Comment by pfitzner** [comment]
Justin,

I'd be more than happy to test this. What is the proper 'go get' syntax to retrieve the branch? The import statement?

I am not using modules, since my original package predates them. As you can see, you're dealing with a comparative neophyte.

Thanks,

Bob S.

**Comment by justinfx** [comment]
If you are not using modules then you need to change into the checkout location of Imagick in your GOPATH (assuming you already did a `go get gopkg.in/gographics/imagick.v3/imagick` and just checkout the im7_SetImageMask branch from the location in your GOPATH

**Comment by justinfx** [comment]
The missing declaration was added to the header in a new commit: https://github.com/ImageMagick/ImageMagick/pull/3566
But seeing as it will end up only available in some newly release patch, I will probably need to leave the declaration in our bindings.
