### ISSUE TITLE
gaussian blur reduce quality

### ISSUE THREAD

**Issue by batara666** [gographics/imagick#246]
i want to implement this command with this library : 

`convert -strip -interlace Plane -gaussian-blur 0.05 -quality 10% test.jpg out.jpg`

**Comment by justinfx** [comment]
Have you tried anything yet? Have you looked at the docs and tried to write some code? 
These can get you started, and you can look at the [examples directory](https://github.com/gographics/imagick/tree/im-7/examples).
https://pkg.go.dev/gopkg.in/gographics/imagick.v3@v3.3.0/imagick#MagickWand.GaussianBlurImage
https://pkg.go.dev/gopkg.in/gographics/imagick.v3@v3.3.0/imagick#MagickWand.SetCompressionQuality

**Comment by batara666** [comment]
yes i already use GaussianBlurImage and SetCompressionQuality, but the result are really different from the command, but nvm, ended with i do shell exec with that command

**Comment by justinfx** [comment]
Alright. Well if you need more help, please supply an example of the code so we can try and reproduce the problem and identify the issues.
