### ISSUE TITLE
Unable to get actual error with invalid pdf

### ISSUE THREAD

**Issue by tryffel** [gographics/imagick#248]
Hi, 

I'm trying to convert a pdf file to image, but it happens that some PDFs are invalid. Even when opening the pdf with Firefox, it logs 'Warning: XRef.parse - Invalid "Root" reference: "XRefEntryException: Bad (uncompressed) XRef entry: 1R".'.
When running imagick, following error is printed to stderr (whether run on cli or use this package to run same command): 
```
# convert -thumbnail x500 -background white -alpha remove my.pdf[0] my.png:
   **** Error: Unrecoverable error in xref!
               Output may be incorrect.
   **** Error: Something went wrong while checking for recursion in the Page tree. Giving up checking.
               This PDF file may not terminate, if there is a loop in the Pages tree.
   **** Error: Unrecoverable error in xref!
               Output may be incorrect.
Error: /rangecheck in resolveR
Operand stack:
   PageCount   1   28   1   (Identity)
Execution stack:
   %interp_exit   .runexec2   --nostringval--   runpdf   --nostringval--   2   %stopped_push   --nostringval--   runpdf   runpdf   false   1   %stopped_push   1990   1   3   %oparray_pop   1989   1   3   %oparray_pop   1977   1   3   %oparray_pop   1978   1   3   %oparray_pop   runpdf   runpdf   runpdf   runpdf   runpdf   runpdf   runpdf   runpdf   runpdf
Dictionary stack:
   --dict:739/1123(ro)(G)--   --dict:1/20(G)--   --dict:80/200(L)--   --dict:80/200(L)--   --dict:133/256(ro)(G)--   --dict:318/325(ro)(G)--   --dict:29/32(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.53.2: Unrecoverable error, exit code 1

```

From that error message, it is clear what went wrong. But, this package returns only error: 
```
 imagick: ERROR_OPTION (0): no images defined `my.png' @ error/convert.c/ConvertImageCommand/3285
```
and from this error message it is impossible to reason what went wrong. This is probably unintentional, but would it be possible to return the actual error, being 'invalid pdf', 'pdf may not terminate' etc, which would help handling the error case. Thanks!

**Comment by justinfx** [comment]
Do you have a sample program and pdf thag reproduce this error? Are you sure that you are checking every available error in code? 
It is possible that we aren't propagating some error properly, or that a manual check for an error isn't being made.
