### ISSUE TITLE
How to build in alpine

### ISSUE THREAD

**Issue by Desdemo** [gographics/imagick#252]
I tried a few but failed

**Comment by justinfx** [comment]
I've never invested any time in trying to figure that out. ImageMagick seemed to not run reliably on alpine. So the first question is whether ImageMagick C library works well on alpine. If the answer is yes, then binding against it with Go shouldn't be an issue.

**Comment by jilieryuyi** [comment]
FROM golang:1.15.6-alpine
ADD . /go/src/test
RUN apk update && apk add gcc musl-dev imagemagick imagemagick-dev dos2unix curl shadow bash openrc sudo vim wget iputils net-tools busybox-extras openssh-server mysql-client
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
RUN convert --version

**Comment by jmaitrehenry** [comment]
We use this Docker image for building and running our Go app with alpine:
```
FROM golang:1.15-alpine3.13 as build

RUN apk add --no-cache build-base imagemagick-dev imagemagick

COPY . /code
WORKDIR /code
ENV CGO_ENABLED=1
ENV CGO_CFLAGS_ALLOW=-Xpreprocessor
ENV GOPROXY=https://proxy.golang.org
RUN go mod download && \
    go test -cover ./... && \
    go build -a -installsuffix cgo -o app

FROM alpine:3.13
RUN apk add --no-cache tzdata ca-certificates imagemagick-dev imagemagick
COPY --from=build /code/app /app/app
COPY --from=build /code/api/docs /app/api/docs

WORKDIR /app
ENTRYPOINT [ "/app/app" ]
```
