### ISSUE TITLE
Problem in golang:1.14.3-alpine 

### ISSUE THREAD

**Issue by gabyzenack** [gographics/imagick#253]
I need to deploy docker and get this error:
Error loading shared library libMagickCore-7.Q16HDRI.so.7: No such file or directory

Versions:
go 1.14
gopkg.in/gographics/imagick.v3 v3.3.0

**Comment by justinfx** [comment]
That docker image likely only contains Go 1.14 tooling and alpine. Did you install libImageMagick in your build image first before having it build your program. Also it is worth pointing out that the history of issues on this project has proven libmusl on alpine to be an unstable solution for ImageMagick

**Comment by gabyzenack** [comment]
I already install libImageMagick in the image build but it is not working....
i'm going to try whit ubuntu 21.04

**Comment by justinfx** [comment]
If you are going to post an issue asking for docker support, which is a bit out of scope for the actual Go bindings, I recommend providing more information than your original post. An example of your Dockerfile and build process would be helpful so we aren't just guessing what you have tried.
The error message about libMagickCore missing could imply either that it installed ImageMagick6, or it installed ImageMagick7 to a non-default location not found in the LD_LIBRARY_PATH, or that you have an error in your Dockfile build step.

**Comment by justinfx** [comment]
Also I should point out that there is an existing example of using Docker with ubuntu:
https://github.com/gographics/imagick/blob/im-7/examples/docker/Dockerfile

I avoid alpine because I haven't seen proof that it is stable.

**Comment by gabyzenack** [comment]
Yes, you are right. Sorry. This is my Dockerfile 

FROM golang:1.14.3-alpine AS build
WORKDIR /src
RUN apk add pkgconfig
RUN apk --update add imagemagick imagemagick-dev && \
    rm -rf /var/cache/apk/*
RUN ldconfig /usr/lib
RUN apk add build-base
COPY . .
RUN go mod tidy
RUN go build -o /myProjectName.
FROM ubuntu
RUN apt-get update && \
    apt-get install -y wget build-essential pkg-config --no-install-recommends
# Install ImageMagick deps
RUN apt-get -q -y install libjpeg-dev libpng-dev libtiff-dev \
    libgif-dev libx11-dev --no-install-recommends
ENV IMAGEMAGICK_VERSION=7.0.10-53
RUN cd && \
    wget https://github.com/ImageMagick/ImageMagick/archive/${IMAGEMAGICK_VERSION}.tar.gz && \
    tar xvzf ${IMAGEMAGICK_VERSION}.tar.gz && \
    cd ImageMagick* && \
    ./configure \
        --without-magick-plus-plus \
        --without-perl \
        --disable-openmp \
        --with-gvc=no \
        --disable-docs && \
    make -j$(nproc) && make install && \
    ldconfig /usr/local/lib
WORKDIR /
COPY --from=build /myProjectName..
CMD /myProjectName.

**Comment by justinfx** [comment]
Thanks for providing your Dockerfile. 
So I can already say that I don't know what to expect if you are building with alpine which uses musl instead of libc, and then running it against ubuntu. Is there any reason your build stage can't use golang:1.14 instead of the alpine version? Then you can build using libc and run it with libc.
Also, I wasn't clear from your error whether it was failing during the build or during the run of the container.

**Comment by gabyzenack** [comment]
Thank you very much, we did everything you recommended and it worked. Cheers!

**Comment by justinfx** [comment]
Nice one. Good luck!
