### ISSUE TITLE
how to resize gif?

### ISSUE THREAD

**Issue by jilieryuyi** [gographics/imagick#254]
err := i.wand.ResizeImage(w, h, imagick.FILTER_LANCZOS)
	if err != nil {
		i.err.WriteString(err.Error())
		return i
	}
	i.wand.WriteImage("G:/kingsoft/image/images/9-magick-resize-1.gif")
	i.width = w
	i.height = h

       // blob content not chang  
	i.content = i.wand.GetImagesBlob()

need some help!!

**Comment by justinfx** [comment]
There was a previous issue where I gave an example of resizing all of the images in an animated gif:
https://github.com/gographics/imagick/issues/190#issuecomment-451057111
