### ISSUE TITLE
LockSemaphoreInfo: Assertion `semaphore_info != (SemaphoreInfo *) ((void *)0)' failed

### ISSUE THREAD

**Issue by Leon2012** [gographics/imagick#26]
gimg: magick/semaphore.c:339: LockSemaphoreInfo: Assertion `semaphore_info != (SemaphoreInfo *) ((void *)0)' failed.
SIGABRT: abort
PC=0x7f7fbb8e8425
signal arrived during cgo execution

goroutine 116 [syscall, locked to thread]:
runtime.cgocall_errno(0x418410, 0xc208161558, 0xc200000000)
    /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208161538 sp=0xc208161510
github.com/gographics/imagick/imagick._Cfunc_DestroyMagickWand(0x7f7fa0035ca0, 0x0)
    /root/go/src/github.com/gographics/imagick/imagick/:680 +0x44 fp=0xc208161558 sp=0xc208161538
github.com/gographics/imagick/imagick.(*MagickWand).Destroy(0xc208038060)
    /root/go/src/github.com/gographics/imagick/imagick/magick_wand.go:50 +0x3a fp=0xc208161570 sp=0xc208161558
github.com/Leon2012/gimg.(*ZSSDBStorage).InfoImage(0xc208038040, 0xc2080e3265, 0x20, 0xc2080e2900, 0x0, 0x0)
    /root/go/src/github.com/Leon2012/gimg/zstorage_ssdb.go:174 +0x446 fp=0xc208161688 sp=0xc208161570
github.com/Leon2012/gimg.(*ZHttpd).doGet(0xc208054400, 0xc2080e3265, 0x20)
    /root/go/src/github.com/Leon2012/gimg/zhttpd.go:175 +0x194 fp=0xc208161c48 sp=0xc208161688
github.com/Leon2012/gimg.(*ZHttpd).ServeHTTP(0xc208054400, 0x7f7fbca0a288, 0xc2080475e0, 0xc2080f8750)
    /root/go/src/github.com/Leon2012/gimg/zhttpd.go:71 +0x2fa fp=0xc208161cb0 sp=0xc208161c48
net/http.serverHandler.ServeHTTP(0xc2080453e0, 0x7f7fbca0a288, 0xc2080475e0, 0xc2080f8750)
    /usr/local/go/src/net/http/server.go:1703 +0x19a fp=0xc208161d08 sp=0xc208161cb0
net/http.(*conn).serve(0xc208046be0)
    /usr/local/go/src/net/http/server.go:1204 +0xb57 fp=0xc208161fd8 sp=0xc208161d08
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208161fe0 sp=0xc208161fd8
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by justinfx** [comment]
First off,  if I understand your usage of the library, you are calling initialize/terminate on ImageMagick, repeatedly for every operation. That could be the source of your problem. Only initialize once at the start of your app, and terminate once at the end. That might solve your problem. 
Otherwise, my next question would be what version of ImageMagick you are using.

**Comment by Leon2012** [comment]
OK, thanks.  
ImageMagick version is 6.8.5-10

**Comment by justinfx** [comment]
It's probably just the need to only initi/terminate once in your main()

**Comment by Leon2012** [comment]
close
