### ISSUE TITLE
Compilation fails after ImageMagick update

### ISSUE THREAD

**Issue by IdlePhysicist** [gographics/imagick#263]
I am attempting to compile an application (on macOS) which uses the `imagick` library. 

I have ImageMagick installed via HomeBrew. When I initially compiled my application ImageMagick was installed to `/usr/local/Cellar/imagemagick/7.1.0-7`, several days later HomeBrew updated ImageMagick and the new path is `/usr/local/Cellar/imagemagick/7.1.0-8`. Now my application will not compile (see output below).

`pkg-config --cflags --libs MagickWand` shows the correct (new) path. But when I run `go build` I get the following output:

```
# command-line-arguments
ld: warning: directory not found for option '-L/usr/local/Cellar/imagemagick/7.1.0-7/lib'
```

I have reinstalled `imagick`, run `go clean`.

What am I missing?

**Comment by justinfx** [comment]
What about the output for MagickCore as well?
```
pkg-config --cflags --libs MagickWand MagickCore
```
You don't happen to have custom CGO_CFLAGS or CGO_LDFLAGS env vars set, do you?

What happens if you try to build imagick separately?
```
go build gopkg.in/gographics/imagick.v3/imagick
```

**Comment by IdlePhysicist** [comment]
> What about the output for MagickCore as well?

```
$ pkg-config --cflags --libs MagickWand MagickCore 
-Xpreprocessor -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Xpreprocessor -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -Xpreprocessor -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.1.0-8/include/ImageMagick-7 -L/usr/local/Cellar/imagemagick/7.1.0-8/lib -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI
```
> You don't happen to have custom CGO_CFLAGS or CGO_LDFLAGS env vars set, do you?

In my Makefile I have the following rule for building the binary, other than that I have no custom flags.

```
build: clean
	env go build -ldflags $(ldflags) -o $(BUILD)/$(APP) $(SRC)/main.go
```

Where `ldflags ="-X $(package).version=$(version) -X $(package).date=$(date)"`, which just sets some build and version parameters. I should point out that the build was working previously with that line.

> What happens if you try to build imagick separately?

In the both the project directory, and `$GOPATH/pkg/mod/gopkg.in/gographics/imagick.v3@v3.4.0` the build command you provided succeeds with no output.

**Comment by justinfx** [comment]
I really don't know what is causing this for you. You could try the more aggressive approach of entirely clearing your build and module caches:
```
go clean -cache
go clean -modcache
```

**Comment by IdlePhysicist** [comment]
I took your advice and ran the following successfully.

```
$ go clean -cache
$ go clean -modcache
$ export CGO_CFLAGS_ALLOW='-Xpreprocessor'  # As per your README
$ make
```

I am not satisfied with having to clear my Go caches after a minor ImageMagick update. Needless to say I have pinned ImageMagick to its current version on my system.

**Comment by justinfx** [comment]
Well I am glad to hear the end result is that it is fixed. For whatever reason it would seem Go tooling thought Imagick was properly built and kept using the previous cached module. I don't know that this is specific to Imagick. It may have to do with a cgo binding library and it not knowing that the linked C library dependency has changed and doesn't trigger a rebuild.
