### ISSUE TITLE
Error undefined: imagick.Initialize while using imagick

### ISSUE THREAD

**Issue by anoop012345** [gographics/imagick#264]
I am using the gopkg.in/gographics/imagick.v2/imagick package but it shows the error while running the server : undefined: imagick.Initialize

import "gopkg.in/gographics/imagick.v2/imagick"
func ConvertPdfToJpg() {
    imagick.Initialize()
    defer imagick.Terminate()
    mw := imagick.NewMagickWand()
    defer mw.Destroy()
    mw.ReadImage("test.pdf")
    mw.SetIteratorIndex(0)
    mw.SetImageFormat("jpg")
    mw.WriteImage("test.jpg")
}

**Comment by justinfx** [comment]
Does it report this error when you compile using `go build`? 
Can you confirm your version of Go and ImageMagick dependency?

**Comment by anoop012345** [comment]
Yes , this error is occur while I am compile using go install and go build.
I am using go1.17 version of go and ImageMagick-6.9.10-11 .

**Comment by justinfx** [comment]
I'm not really sure why you would see this error. The Dockerfile in the main branch tests specifically against this version of ImageMagick. Are you using a 'go.mod' file or are you relying on GOPATH? I'm really just trying to randomly think of possible causes.
