### ISSUE TITLE
Possible memory leak on GetImageHistogram

### ISSUE THREAD

**Issue by dooman87** [gographics/imagick#265]
Hi there,

I'm running imagick in http server and every call to GetImageHistogram adds 20Mb to the memory that seems to be never freeing up. 

I attached a reproducable example [im_histogram.zip](https://github.com/gographics/imagick/files/7376880/im_histogram.zip):

* Run `main.go` 
* Open system monitor/top to see memory
* Open `localhost:8181` in the browser
* On each reload memory usage grows

I tried manually destory magick and pixel wands, but it didn't help.

I've also written simple C version and it doesn't look like there is a leak there. 

I checked the binding implementation and it looks fairly simple to me, so I'm at loss to understand what's going on here.

IM Version 7.1.0-6

**Comment by dooman87** [comment]
Thanks @gavbaa, I was trying to clean up PixelWands, but it doesn't seem to help. I updated the code from the example and attaching the archive here again. The cleanup I did:

```go
		numColors, colors := mw.GetImageHistogram()
		memstat()

		fmt.Printf("Read %d colors with len %d\n", numColors, len(colors))

		for _, c := range colors {
			c.Destroy()
		}
		mw.Destroy()

		imagick.Terminate()
```

I'm doing `imagick..Terminate` after each HTTP request, and it triggers GC(), so I thought it should give memory back....

[im_histogram_1.zip](https://github.com/gographics/imagick/files/7380007/im_histogram_1.zip)

**Comment by justinfx** [comment]
@dooman87  you might be able to do something with the ImageMagick resource limits in the policy.xml file?
https://imagemagick.org/script/resources.php
