### ISSUE TITLE
 Why compilation errors

### ISSUE THREAD

**Issue by jackey925** [gographics/imagick#266]
I had an error compiling with Mac 
routers/api/v1/ocr.go:77:2: undefined: imagick.Initialize
routers/api/v1/ocr.go:78:8: undefined: imagick.Terminate
routers/api/v1/ocr.go:80:8: undefined: imagick.NewMagickWand
routers/api/v1/ocr.go:103:36: undefined: imagick.ALPHA_CHANNEL_OFF

build instruction follow：
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  "-s -w" -o main

**Comment by justinfx** [comment]
You can't build this with cgo enabled. The bindings are literally cgo. If you try and disable it, then you have no linkage with the ImageMagick C api.

**Comment by jackey925** [comment]
thank's for your answer , How do I write this compilation instruction with cgo .

**Comment by jackey925** [comment]
> You can't build this with cgo **disabled**. The bindings are literally cgo. If you try and disable it, then you have no linkage with the ImageMagick C api.

thank's for your answer , How do I write this compilation instruction with cgo .

**Comment by justinfx** [comment]
I just realised a second issue. You said you are trying to cross compile for Linux, from your Mac? That requires you have Linux-compiled ImageMagick libraries and whatever else is needed for the Linux tool chain. We don't have any instructions on how to cross compile this cgo binding.
You are better off using docker which would let you natively compile the Linux binary from your Mac in a docker container.

**Comment by justinfx** [comment]
Here is an example
https://github.com/gographics/imagick/blob/im-7/Dockerfile

**Comment by jackey925** [comment]
Thank you for your suggestion. I'll try to use the Docker example you gave

**Comment by justinfx** [comment]
If you have issues with the Docker container, feel free to ping this ticket. For now, I will close this.
