### ISSUE TITLE
[Imageickv3] document_service.go:21:2: undefined: imagick.Initialize

### ISSUE THREAD

**Issue by artemii-morozov** [gographics/imagick#267]
### Issue
Can't compile GOARCH=amd64 GOOS=linux based executable file from docker on mac.
When docker executes: `GOARCH=amd64 GOOS=linux go build -ldflags '-s -w' -o ./main ./main.go` it fails with:
```
RUN --mount=type=ssh GOARCH=amd64 GOOS=linux go build -ldflags '-s -w' -o ./main ./main.go:
#23 6.654 # github.com/org/repo/app/service
#23 7.354 app/service/document_service.go:21:2: undefined: imagick.Initialize
#23 7.354 app/service/document_service.go:22:8: undefined: imagick.Terminate
#23 7.354 app/service/document_service.go:23:8: undefined: imagick.NewMagickWand
#23 7.354 app/service/document_service.go:33:2: undefined: imagick.Initialize
#23 7.354 app/service/document_service.go:34:8: undefined: imagick.Terminate
#23 7.354 app/service/document_service.go:35:8: undefined: imagick.NewMagickWand
------
executor failed running [/bin/sh -c GOARCH=amd64 GOOS=linux go build -ldflags '-s -w' -o ./main ./main.go]: exit code: 2
```
when build with `go build -ldflags '-s -w' -o ./main ./main.go` it is successfully built, however, when I zip it and deploy it to localstack like:
```
aws --endpoint-url=http://localhost:4566 lambda create-function \
    --region us-east-1 \
    --function-name ${LAMBDA_NAME} \
    --runtime go1.x \
    --handler main \
    --memory-size 256 \
    --timeout 600 \
    --zip-file fileb://deps.zip \
    --role arn:aws:iam::000000000000:role/irrelevant \
    --environment \
        "{\"Variables\":
            {
                \"AWS_REGION\": \"us-east-1\",
                \"AWS_ENDPOINT\": \"http://awsservices:4566\",
                \"S3_BUCKET\": \"${S3_BUCKET}\"
            }
        }"
```
localstack fails to start lambda with error like:
```
awsservices  | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: {"errorType":"exitError","errorMessage":"RequestId: 1fcf9391-e9b1-17f5-6940-b12c6f8adf0f Error: fork/exec /var/task/main: no such file or directory"}. Output:
```
Although, ssh into freshly span lambda container shows that file exists.

Which seems like wrong execution file is used and it expects version explicitly compiled for `GOARCH=amd64 GOOS=linux`

macOS: 11.6 (20G165)
go version go1.17.5 darwin/arm64

### Details
My docker file is like based on dockerfile from this project:
```
FROM golang:1.17

# Ignore APT warnings about not having a TTY
ENV DEBIAN_FRONTEND noninteractive

# install build essentials
RUN apt-get update && \
    apt-get install -y wget build-essential pkg-config libmagickcore-dev --no-install-recommends

# Install ImageMagick deps
RUN apt-get -q -y install libjpeg-dev libpng-dev libtiff-dev \
    libgif-dev libx11-dev --no-install-recommends libmagickwand-dev

ENV IMAGEMAGICK_VERSION=7.0.8-45

RUN cd && \
	wget https://github.com/ImageMagick/ImageMagick/archive/${IMAGEMAGICK_VERSION}.tar.gz && \
	tar xvzf ${IMAGEMAGICK_VERSION}.tar.gz && \
	cd ImageMagick* && \
	./configure \
	    --without-magick-plus-plus \
	    --without-perl \
	    --disable-openmp \
	    --with-gvc=no \
	    --disable-docs && \
	make -j$(nproc) && make install && \
	ldconfig /usr/local/lib

RUN go env -w GOPROXY=direct
RUN go env -w GO111MODULE=on
RUN go env -w GOSUMDB=off

#RUN mkdir -m 700 /root/.ssh && \
#    echo "Host *\n\tStrictHostKeyChecking no" >> /root/.ssh/config && \
#    chmod 400 /root/.ssh/config

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN git config --global --add url."git@github.com:".insteadOf "https://github.com/"

WORKDIR /go/projects/resizer
COPY . .

RUN export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

RUN pkg-config --cflags --libs MagickWand
RUN export CGO_CFLAGS="$(pkg-config --cflags MagickWand)"
RUN export CGO_LDFLAGS="$(pkg-config --libs MagickWand)"

RUN --mount=type=ssh go mod vendor -v
RUN --mount=type=ssh go get gopkg.in/gographics/imagick.v3/imagick
RUN export CGO_CFLAGS_ALLOW='-Xpreprocessor'
# RUN GOARCH=amd64 GOOS=linux CGO_ENABLED=1 go build -o ./main .
# RUN go build -tags no_pkgconfig .
RUN go build -ldflags '-s -w' -o ./main ./main.go
# RUN go install
ENV _LAMBDA_SERVER_PORT 6002
CMD /go/projects/resizer/main
```

Am I doing cross compilation with CGO wrong? I tried to compile it on my m1 mac but gave up after discovering closed issues in this project.
My goal is to run lambda locally in localstack with ImageMagick. I had already prepared uber zip with ImageMagick dependencies for lambda runtime, but I cannot compile the actual lambda code written in go for linux platform.

**Comment by justinfx** [comment]
I've not tried to build for aws lambda before, but there are a couple things you could try.

- Get rid of the `apt` `libmagickwand-dev`, because you are building your own specific Imagemagick from source
- Switch to an Amazon Linux 2 docker image for building, to ensure the linux runtime matches: 
  - https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html
  - https://hub.docker.com/_/amazonlinux?tab=tags
- You may have to investigate static linking your binary. Because if you build your app in your docker container as you are now, it is dynamically linking against ImageMagick. Then you zip up, I assume, only the binary and send it to aws, which would be missing the ImageMagick library when it runs in their AMI. Or are you actually also zipping up the ImageMagick distribution?

**Comment by artemii-morozov** [comment]
Thank you for quick reply.
1. I'll remove `libmagickwand-dev` and give it a try, but it didn't work before I added anyway.
2. Makes sense to me. I'll try amazon linux 1 as it's container used to spin lambda containers by localstack https://github.com/lambci/docker-lambda/blob/master/base/Dockerfile#L1
3. I build uber labmda zip which includes layer of ImageMagick, but the problem isn't there yet. I just cannot compile runnable file

**Comment by justinfx** [comment]
I see now where you said you are producing a zip that also contains the linux ImageMagick dependencies that you compiled from source.

```
RUN --mount=type=ssh GOARCH=amd64 GOOS=linux go build -ldflags '-s -w' -o ./main ./main.go:
#23 6.654 # github.com/org/repo/app/service
#23 7.354 app/service/document_service.go:21:2: undefined: imagick.Initialize
#23 7.354 app/service/document_service.go:22:8: undefined: imagick.Terminate
#23 7.354 app/service/document_service.go:23:8: undefined: imagick.NewMagickWand
#23 7.354 app/service/document_service.go:33:2: undefined: imagick.Initialize
#23 7.354 app/service/document_service.go:34:8: undefined: imagick.Terminate
#23 7.354 app/service/document_service.go:35:8: undefined: imagick.NewMagickWand
```

This acts like you don't have `imagick` imported in your `document_service.go`?

I can't see why you would have to specifically use GOARCH and GOOS within a docker image that is already amd64 linux, or to include stuff like `CGO_CFLAGS_ALLOW='-Xpreprocessor'` (mac), or be concerned about your host mac go version. It shouldn't really be considered cross-compiling if you are building it from within a linux container.

**Comment by artemii-morozov** [comment]
> I see now where you said you are producing a zip that also contains the linux ImageMagick dependencies that you compiled from source.
> 
> ```
> RUN --mount=type=ssh GOARCH=amd64 GOOS=linux go build -ldflags '-s -w' -o ./main ./main.go:
> #23 6.654 # github.com/org/repo/app/service
> #23 7.354 app/service/document_service.go:21:2: undefined: imagick.Initialize
> #23 7.354 app/service/document_service.go:22:8: undefined: imagick.Terminate
> #23 7.354 app/service/document_service.go:23:8: undefined: imagick.NewMagickWand
> #23 7.354 app/service/document_service.go:33:2: undefined: imagick.Initialize
> #23 7.354 app/service/document_service.go:34:8: undefined: imagick.Terminate
> #23 7.354 app/service/document_service.go:35:8: undefined: imagick.NewMagickWand
> ```
> 
> This acts like you don't have `imagick` imported in your `document_service.go`?
> 
> I can't see why you would have to specifically use GOARCH and GOOS within a docker image that is already amd64 linux, or to include stuff like `CGO_CFLAGS_ALLOW='-Xpreprocessor'` (mac), or be concerned about your host mac go version. It shouldn't really be considered cross-compiling if you are building it from within a linux container.

it's imported like this:
```
package service

import (
	"context"
	"fmt"
	"github.com/wkda/go-libs/log"
	"gopkg.in/gographics/imagick.v3/imagick"
)

type DocumentService struct {

}

func NewDocumentService() DocumentService {
	return DocumentService{}
}

func (r *DocumentService) getThumbnail(image []byte, ctx context.Context, objectKey string) ([]byte, error) {
	log.Get(ctx).Debug(fmt.Sprintf("Generating thumbnail for [%v]", objectKey))

	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	err := mw.ReadImageBlob(image)

	err = mw.ThumbnailImage(200, 200)

	return mw.GetImagesBlob(), err
}
...
```


Yeah, without flags (`go build -o ./main ./main.go`) it compiles with no errors inside container. Then I copy it from container to my host FS from which I pack it into zip and deploy to localstack. But it's not launchable from localstack for some reason, saying no file found, though it is in place. I tried to google possible root cause and found that it should be compiled for linux x64 - https://stackoverflow.com/questions/58133166/getting-error-fork-exec-var-task-main-no-such-file-or-directory-while-execut

**Comment by justinfx** [comment]
Well that link you provided shows an example of someone trying to compile the binary directly on Windows, and then needing to actually cross-compile it for amd64 linux with env vars. In your case you are using a linux docker image, so it isn't cross compiling anymore. 

I don't have enough knowledge of localstack to comment, so I can only try my best to help with the compilation step. In your linux container, you could add some sanity checks right after you compile the binary:

```
RUN file ./main && ldd ./main
```

That would confirm the architecture of the file and print the dynamic links against the binary.

Completely unrelated side note:

```go
func (r *DocumentService) getThumbnail(...) {
	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	err := mw.ReadImageBlob(image)
````

Seems like not a great idea to initialize and teardown the entire ImageMagick library on each image conversion. Common mistake.

**Comment by artemii-morozov** [comment]
> Completely unrelated side note:
yeah, I've seen this comment from you in another ticker. I'll get back and refactor entire solution, but need to have ut runnable locally first.

Thanks a lot for your help and patience

**Comment by justinfx** [comment]
Right on. Hope you get it working! Sounds like a compatibility issues with the aws stack.

**Comment by artemii-morozov** [comment]
one more issue come up switching to another docker image (amazon linux 1 based go image):
```
#29 44.41       fatal: unable to access 'https://gopkg.in/gographics/imagick.v3/': SSL certificate problem: certificate has expired
```
executing `RUN --mount=type=ssh go mod vendor -v` or `--mount=type=ssh go get gopkg.in/gographics/imagick.v3/imagick`

I used verndor -e flag to ignore the error

**Comment by justinfx** [comment]
The site doesn't seem to be complaining about SSL certs: https://gopkg.in/gographics/imagick.v3/imagick
Maybe that Amazon Linux 1 image has old CA certs. They do recommend Linux 2 in the aws lambda Go docs.

**Comment by artemii-morozov** [comment]
> 

yep, it might. I use it as it is used by localstack for local development. Will give it a try with another image

**Comment by artemii-morozov** [comment]
> ldd ./main && file ./main
        linux-vdso.so.1 (0x0000ffffa9bee000)
        libMagickWand-7.Q16HDRI.so.6 => /usr/local/lib/libMagickWand-7.Q16HDRI.so.6 (0x0000ffffa9a94000)
        libMagickCore-7.Q16HDRI.so.6 => /usr/local/lib/libMagickCore-7.Q16HDRI.so.6 (0x0000ffffa9638000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffa9607000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffa9491000)
        libX11.so.6 => /usr/lib/aarch64-linux-gnu/libX11.so.6 (0x0000ffffa9344000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffffa9299000)
        libjbig.so.0 => /usr/lib/aarch64-linux-gnu/libjbig.so.0 (0x0000ffffa927c000)
        libtiff.so.5 => /usr/lib/aarch64-linux-gnu/libtiff.so.5 (0x0000ffffa91ed000)
        libjpeg.so.62 => /usr/lib/aarch64-linux-gnu/libjpeg.so.62 (0x0000ffffa919d000)
        libpng16.so.16 => /usr/lib/aarch64-linux-gnu/libpng16.so.16 (0x0000ffffa9156000)
        liblzma.so.5 => /lib/aarch64-linux-gnu/liblzma.so.5 (0x0000ffffa9120000)
        libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000ffffa90f6000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffa9bbe000)
        libxcb.so.1 => /usr/lib/aarch64-linux-gnu/libxcb.so.1 (0x0000ffffa90be000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffffa90aa000)
        libwebp.so.6 => /usr/lib/aarch64-linux-gnu/libwebp.so.6 (0x0000ffffa9048000)
        libzstd.so.1 => /usr/lib/aarch64-linux-gnu/libzstd.so.1 (0x0000ffffa8f7c000)
        libdeflate.so.0 => /usr/lib/aarch64-linux-gnu/libdeflate.so.0 (0x0000ffffa8f58000)
        libXau.so.6 => /usr/lib/aarch64-linux-gnu/libXau.so.6 (0x0000ffffa8f44000)
        libXdmcp.so.6 => /usr/lib/aarch64-linux-gnu/libXdmcp.so.6 (0x0000ffffa8f2e000)
        libbsd.so.0 => /usr/lib/aarch64-linux-gnu/libbsd.so.0 (0x0000ffffa8f09000)
        libmd.so.0 => /usr/lib/aarch64-linux-gnu/libmd.so.0 (0x0000ffffa8eed000)
./main: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=09433555c20f08326e360b9607f2556dfbe4ef47, for GNU/Linux 3.7.0, not stripped

does it mean ARM64 instead of amd64? I think that might be a problem

**Comment by justinfx** [comment]
> does it mean ARM64 instead of amd64? I think that might be a problem

Yea. So you can see its `GOARCH=arm64`, as well as all the dependencies. The binary, and all of the dynamic libraries that you zip up would need to match the expected arch where they are going to run. I don't know if localstack runs natively on your host or under a container? Either way, you have to match that to whatever localstack does and also aws lambda.

**Comment by artemii-morozov** [comment]
just confirmed that lambda container bootstraped by localstack is x86_64 arch
Architecture:          x86_64

while my execution file is `./main: ELF 64-bit LSB executable, ARM aarch64` and was built on:
Architecture:                    aarch64

tried to build executable like: `GOARCH=amd64 go build -o ./main ./main.go`, but it fails with:
```
 => ERROR [18/19] RUN GOARCH=amd64 go build -o ./main ./main.go                                                                                                                                      6.8s
------
 > [18/19] RUN GOARCH=amd64 go build -o ./main ./main.go:
#22 6.685 # github.com/wkda/retail-inventory-document-thumbnail-lambda/app/service
#22 6.685 app/service/document_service.go:21:2: undefined: imagick.Initialize
#22 6.685 app/service/document_service.go:22:8: undefined: imagick.Terminate
#22 6.685 app/service/document_service.go:23:8: undefined: imagick.NewMagickWand
#22 6.685 app/service/document_service.go:33:2: undefined: imagick.Initialize
#22 6.685 app/service/document_service.go:34:8: undefined: imagick.Terminate
#22 6.685 app/service/document_service.go:35:8: undefined: imagick.NewMagickWand
------
executor failed running [/bin/sh -c GOARCH=amd64 go build -o ./main ./main.go]: exit code: 2
```

I'll try tomorrow to spin container with x86_64 arch to build executable file on top of it.

Thank you once again @justinfx
