### ISSUE TITLE
Problem deleting exif:* property

### ISSUE THREAD

**Issue by vanng822** [gographics/imagick#27]
I run this

	props := img.GetImageProperties("")
	fmt.Println(props)
	for _, prop := range props {
		fmt.Println(prop, img.GetImageProperty(prop), img.DeleteImageProperty(prop))
	}
	
	for _, prop := range props {
		fmt.Println(prop, img.GetImageProperty(prop))
	}

Where img is an *MagickWand which the image source is an jpg and contains exif meta data (https://raw.githubusercontent.com/vanng822/imgscale/master/data/kth.jpg) , such as GPS*

The code could delete other properties, such as comment, date:*, jpg:* but not exif:*

I use mac (version 10.10.1) and:
Version: ImageMagick 6.8.9-8 Q16 x86_64 2014-10-23 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules
Delegates: bzlib freetype jng jpeg ltdl lzma png zlib

I guess this is an issue in ImageMagick?
StripImage removed everything as it should.

**Comment by justinfx** [comment]
This may be specific to ImageMagick, as the wrapper method in the Go lib are extremely thin. They literally just convert string vars back and forth and delegate to ImageMagick. Have you tried asking around the ImageMagick community?

I did see a post regarding the use of `GetImageProfiles` and `RemoveImageProfile` but I don't think that is producing the desired results either.

**Comment by vanng822** [comment]
I was thinking doing it but thought that maybe you guys know better channels to ask. I just tried out something so not urgent. It maybe fix itself on next upgrade.

I close this ticket. If you have to time and know where to ask, would be nice to know the answer.
