### ISSUE TITLE
SetImageCompressionQuality not working for HEIC files

### ISSUE THREAD

**Issue by haorlin** [gographics/imagick#271]
Changing the compression quality for JPEGs, WebP, other image types work, but when the image format is set to HEIC, then the compression quality is not changing the image size at all. 

Running `convert image.jpeg -quality 50 image.heic` on the command line works as expected.

**Comment by justinfx** [comment]
What was the fix?

**Comment by haorlin** [comment]
Using `SetCompressionQuality` instead of `SetImageCompressionQuality` seems to work.

**Comment by justinfx** [comment]
Ah yes. It's the same as #204 and #216.
