### ISSUE TITLE
Resizing .webp animated images

### ISSUE THREAD

**Issue by dragonDScript** [gographics/imagick#272]
I'm trying to resize an animated webp image but don't know how to do it. Any help? Any help is appreciated.

**Comment by justinfx** [comment]
First I would start here and confirm that your ImageMagick library is built with the "webp" delegate:
https://github.com/gographics/imagick/issues/199

And then you could reference this issue about resizing an animated gif. It may be a similar approach?
https://github.com/gographics/imagick/issues/190#issuecomment-451057111

**Comment by justinfx** [comment]
Well I am not saying that it isn't possible. It is just that, I haven't gone and worked up a test and exact code to give you. Are you new to Go in general? Or just new to using this project? 
If you are looking for a complete end-to-end example of resizing webp, myself or someone else would have to find a moment to test it. But either way, you are still going to want to confirm that the ImageMagick library on your own machine is built with support for the "webp" delegate plugin.

Start by running this, and confirming the list of delegates:
```
convert -version
```

**Comment by dragonDScript** [comment]
> Well I am not saying that it isn't possible. It is just that, I haven't gone and worked up a test and exact code to give you. Are you new to Go in general? Or just new to using this project? If you are looking for a complete end-to-end example of resizing webp, myself or someone else would have to find a moment to test it. But either way, you are still going to want to confirm that the ImageMagick library on your own machine is built with support for the "webp" delegate plugin.
> 
> Start by running this, and confirming the list of delegates:
> 
> ```
> convert -version
> ```

I am just new to this lib, and I'm a bit lost xD. webp delegate is installed
```
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
```

**Comment by justinfx** [comment]
I tried to test this out. The "webp" ImageMagick delegate relies on the `dwebp` tool that is meant to come with the webp library package. ImageMagick `convert` and other tools fail on a source animated webp. Then I found this:

```
dwebp -pam test.webp -o out.file
Error! Decoding of an animated WebP file is not supported.
       Use webpmux to extract the individual frames or
       vwebp to view this image.
Decoding of test.webp failed.
Status: 4(UNSUPPORTED_FEATURE)
```

So it seems source animated webp images are not supported. You can convert from animated gif to animated webp apparently. But for the workflow you want, you would have to first manually extract the animated webp to an image sequence. You could then bring that sequence of images into ImageMagick, resize, and hopefully write out a new webp.

**Comment by dragonDScript** [comment]
Okay, thanks for the help!

**Comment by justinfx** [comment]
>  this issue is not mine, it's from someone else. It's a bounty. But I don't have time to do it. Do you want to do it?

@dragonDScript , not really. But thanks for the offer!
