### ISSUE TITLE
Building with Apple Silicon

### ISSUE THREAD

**Issue by stebunting** [gographics/imagick#273]
I am trying to install Imagick v3 under OS X 12.2.1 with Apple M1. I keep getting the following error:

`ld: warning: ignoring file /opt/homebrew/Cellar/imagemagick/7.1.0-27/lib/libMagickWand-7.Q16HDRI.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64`

This is followed by a raft of messages similar to:
```
"_SetMagickPrecision", referenced from:
      __cgo_a387bb336bd8_Cfunc_SetMagickPrecision in _x043.o
     (maybe you meant: __cgo_a387bb336bd8_Cfunc_SetMagickPrecision)
```

ImageMagick v7.1.0-27 was installed with Homebrew and appears to be working correctly.

I am trying to install Imagick with the following command:

`CGO_CFLAGS_ALLOW=-Xpreprocessor go get gopkg.in/gographics/imagick.v3/imagick`

I am not sure how to proceed with this, could someone help me please?

**Comment by justinfx** [comment]
I don't have an M1 Mac to test any of this, so I can only guess. Seems like your Go tool is trying to compile for amd64 while your ImageMagick library from brew is arm64.
Can you confirm your default go tool env?

```
go env
```

And also try to build with arm64?

```
GOARCH=arm64 GOOS=darwin go ...
```

If that doesn't work, maybe you either have an old install of Go from a previous non-m1 Mac?

**Comment by stebunting** [comment]
Thanks a lot, that certainly worked, for some reason `GOARCH` was set to `amd64`.

However, now I am getting different errors:
```
images/images.go:33:19: undefined: imagick.MagickWand
images/images.go:64:18: undefined: imagick.NewMagickWand
images/images.go:173:8: undefined: imagick.NewMagickWand
images/images.go:220:6: undefined: imagick.FILTER_UNDEFINED
images/images.go:234:47: undefined: imagick.FILTER_UNDEFINED
images/images.go:247:5: undefined: imagick.FILTER_UNDEFINED
images/images.go:260:4: undefined: imagick.FILTER_UNDEFINED
images/images.go:277:22: undefined: imagick.COMPOSITE_OP_OVER
images/images.go:369:8: undefined: imagick.NewMagickWand
```

**Comment by justinfx** [comment]
Cool. Did your go installation come from brew or from the Go dl site? If it was from brew then brew picked an amd64 configuration.

**Comment by stebunting** [comment]
It came from the Go site.
