### ISSUE TITLE
GetImageBlob not getting correct format

### ISSUE THREAD

**Issue by lynkas** [gographics/imagick#274]
Hello. I'm using imagick to convert images' format. 
Here is an example about what I did.

I'm using ImageMagick 7.0.6-9 and v3.4.0 of imagick.

```
package main

import (
	"fmt"

	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	err := mw.ReadImage(".develop/a.png")
	if err != nil {
		panic(err)
	}
	defer mw.Destroy()

	err = mw.SetImageCompressionQuality(80)
	if err != nil {
		fmt.Printf("set compress quality failed: %v", err)
	}

	err = mw.SetImageFormat("webp")
	if err != nil {
		fmt.Printf("set format failed: %v", err)
	}

	bytes := mw.GetImageBlob()
	fmt.Println(len(bytes))
	err = mw.WriteImage("./.develop/b.webp")
	if err != nil {
		panic(err)
	}

}
```

The problem is that the "bytes" is in png format but not webp. As a result, it's size is close to the original file size, while b.webp has a smaller size and formatted correctly.

This cannot be produced on a windows system, but always happen in docker environment with debian. 
My Dockerfile can be seen here https://github.com/snowoby/street/blob/master/Dockerfile

*btw, in the repo, cmd/test is this example. 

May this be a webp related problem?

Additionally, I want to know if this is the correct usage of GetImageBlob method. Thanks.

**Comment by lynkas** [comment]
Ok solved, a really newbie problem. If you want to support webp in docker, don't just copy the dockerfile example. You have to add libwebp-dev in dependency and --with-webp=yes in ./configure.

**Comment by justinfx** [comment]
Good find. The misleading detail was that you had suggested using `WriteImage` was writing a proper webp format? That implied that ImageMagick was built with the webp delegate.
