### ISSUE TITLE
tiff convert leak memory

### ISSUE THREAD

**Issue by yfanswer** [gographics/imagick#275]
convert tiff to jpg use lots of memory, and not free.
following is code:

```go
func (y *YImageMagic) GenReduceImage(outPath string, width, height, quality uint, resize bool) error {
	if y.mw == nil {
		return perrors.New("magic wand nil")
	}

	if err := y.mw.StripImage(); err != nil {
		return perrors.WithStack(err)
	}

	if resize {
		// FILTER_BOX fastest
		if err := y.mw.ResizeImage(width, height, imagick.FILTER_BOX); err != nil {
			return perrors.WithStack(err)
		}
	} else {
		if err := y.mw.ResizeImage(y.mw.GetImageWidth(), y.mw.GetImageHeight(), imagick.FILTER_BOX); err != nil {
			return perrors.WithStack(err)
		}
	}

		if err := y.mw.AutoOrientImage(); err != nil {
			return perrors.WithStack(err)
		}

		if err := y.mw.SetImageCompressionQuality(quality); err != nil {
			return perrors.WithStack(err)
		}

		if err := y.mw.WriteImage(outPath); err != nil {
			return perrors.WithStack(err)
		}
	return nil
}
```

**Comment by justinfx** [comment]
Hi. This is very much related to the detailed discussion in #136 . I would recommend giving that a read. But to give you a quick summary, I can reproduce the growing memory in a self-contained program. Some of the points to note about the memory is that:

- I don't think it is so much a "leak" as it is a problem with the way Go maps OS thread and how that impacts calling into ImageMagick C library with thread-local storage
- Make sure to free a wand as soon as you are done with it
- Using `LockOsThread/UnlockOSThread` can create a more predictable memory usage if you have bounded image worker goroutines
- The total memory usage is related to the total number of concurrent goroutines doing ImageMagick calls

Consider this program:

```go
package main

import (
	"fmt"
	"os"
	"runtime"
	"sync"
	"time"

	"gopkg.in/gographics/imagick.v3/imagick"
)

const NumConcurrent = 1

func main() {
	infile := os.Args[1]
	outfile := os.Args[2]

	imagick.Initialize()
	defer imagick.Terminate()

	var wg sync.WaitGroup
	wg.Add(NumConcurrent)

	for i := 0; i < NumConcurrent; i++ {
		go func(i int) {
			defer wg.Done()
			outfile := fmt.Sprintf("%d_%s", i, outfile)
			// Make sure ImageMagick sees a consistent OS thread for the life of
			// the worker and has more predictable memory caching
			runtime.LockOSThread()
			defer runtime.UnlockOSThread()
			for j := 1; j <= 50; j++ {
				convert(infile, outfile)
			}
		}(i)
	}

	wg.Wait()

	fmt.Println("Done. Sleeping.")
	time.Sleep(60 * time.Second)
}

func convert(infile string, outfile string) {
	var err error

	mw := imagick.NewMagickWand()
	// Make sure we free the wand as soon as we are done, instead of waiting
	// for gc finalizer to run
	defer mw.Destroy()

	fmt.Println("Read:", infile)
	err = mw.ReadImage(infile)
	if err != nil {
		panic(err)
	}

	if err = mw.StripImage(); err != nil {
		panic(err)
	}

	if err := mw.ResizeImage(mw.GetImageWidth()/4, mw.GetImageHeight()/4, imagick.FILTER_BOX); err != nil {
		panic(err)
	}

	if err := mw.AutoOrientImage(); err != nil {
		panic(err)
	}

	if err := mw.SetImageCompressionQuality(92); err != nil {
		panic(err)
	}

	if err := mw.WriteImage(outfile); err != nil {
		panic(err)
	}

	fmt.Println("Wrote:", outfile)
}
```

If you run this as `go run infile.tiff outfile.jpg` and you watch the memory usage of the process, you will see that it peaks to a certain amount and then settles back down.  Then try increasing `NumConcurrent=2` and note that the peak memory usage roughly doubles and settles back down. Now comment out the `LockOSThread/UnlockOSThread` and see the different in memory usage if the OS threads are not kept consistent in the goroutines when calling into ImageMagick.

My understanding of using the Go binding with ImageMagick is that it works best when you have a bounded number of worker goroutines and you control the number of concurrent threads going through ImageMagick.
