### ISSUE TITLE
blind watermark is supported?

### ISSUE THREAD

**Issue by wsx958191** [gographics/imagick#277]
hello:
        I have a question, this job how to make blind watermark this function? thanks

**Comment by justinfx** [comment]
There is a composite feature called "stegano". Is this what you are after?
https://legacy.imagemagick.org/Usage/transform/#stegano

Looking through the C source code to understand how it is exposed in the API, I see they kind of minimally expose it. They offer this [CompositeImageCommand()](https://github.com/ImageMagick/ImageMagick/blob/7ba113a0d26b6d2b008ce0fcf428050a84e5a0ac/MagickWand/composite.c#L90) which we don't expose yet. But it is very similar to this [ConvertImageCommand()](https://github.com/gographics/imagick/blob/020a86d5c9cbe13e63db46a925479a9a54cbff0e/imagick/image.go#L42) that we do expose. Does that look like it would be useful to do arbitrary composite operations?
