### ISSUE TITLE
runtime SIGFPE signal 

### ISSUE THREAD

**Issue by ben-swit** [gographics/imagick#278]
i use imagick with go in  kubernetes 
when i check pod  then restart count up  so i check the log 

```
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x1 addr=0x7f658880f39d pc=0x7f658880f39d]

runtime stack:
runtime.throw({0x14715e5, 0x0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 15666 [syscall]:
runtime.cgocall(0x10d3640, 0xc0014ff708)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0014ff6e0 sp=0xc0014ff6a8 pc=0x419e5c
gopkg.in/gographics/imagick.v3/imagick._Cfunc_MagickThumbnailImage(0x7f64e4003e80, 0x200, 0x0)
	_cgo_gotypes.go:8219 +0x4c fp=0xc0014ff708 sp=0xc0014ff6e0 pc=0x103ed4c
gopkg.in/gographics/imagick.v3/imagick.(*MagickWand).ThumbnailImage.func1(0x7f64e4003e80, 0xc0014ff770, 0x105999e)
	/go/pkg/mod/gopkg.in/gographics/imagick.v3@v3.4.0/imagick/magick_wand_image.go:2741 +0x65 fp=0xc0014ff750 sp=0xc0014ff708 pc=0x1065985
gopkg.in/gographics/imagick.v3/imagick.(*MagickWand).ThumbnailImage(0xc0023a8ab0, 0x4032000000000000, 0x40d3ddc000000000)
	/go/pkg/mod/gopkg.in/gographics/imagick.v3@v3.4.0/imagick/magick_wand_image.go:2741 +0x1e fp=0xc0014ff780 sp=0xc0014ff750 pc=0x10658be
bb/internal/pkg/thumbnail.ConvertThumbnail({0xc001c60000, 0x6b42, 0xa000}, {0x1426345, 0x3}, 0x200, 0x200)
	/go/src/server/internal/pkg/thumbnail/thumbnail.go:153 +0x1da5 fp=0xc0014ffe48 sp=0xc0014ff780 pc=0x107a2e5
/app/upload.Router.CreateAsset.func1()
	/go/src/server/app/upload/upload.go:163 +0x37c fp=0xc0014fff78 sp=0xc0014ffe48 pc=0x108329c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67 fp=0xc0014fffe0 sp=0xc0014fff78 pc=0xf213e7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0014fffe8 sp=0xc0014fffe0 pc=0x480901
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

is there any solution? 
i don't know why rise up signal in pod

**Comment by justinfx** [comment]
Does it only happen in kubernetes? Can you replicate it on a local machine? The `ThumbnailImage` wrapper is quite simple:
https://github.com/gographics/imagick/blob/v3.4.0/imagick/magick_wand_image.go#L2740

So that implies that a division-by-zero likely happened within the C ImageMagick code. Are you able to confirm the values of `cols` and `rows` parameters? Also can you confirm the version of ImageMagick7 that you are using? Maybe they have an actual bug report/fix about this related to `MagickThumbnailImage`

**Comment by justinfx** [comment]
I can see where a division error is possible:
https://github.com/ImageMagick/ImageMagick/blob/09ab692eeafa266bca06b62f0e366709bb42d56e/MagickCore/resize.c#L4559

Its very easy to reproduce this by passing either a row or col value of 0. That is technically a bug in the application calling `ThumbnailImage` with bad values. But we could do better and prevent the SIGFPE by checking for 0 on the Go side and returning an error.

**Comment by justinfx** [comment]
Commit [88a9b60](https://github.com/gographics/imagick/commit/88a9b606931d0cafa070aed9d75f53dd137765fb) should fix the issue in the im-7 branch. I can release a new patch.
