### ISSUE TITLE
Free string constant

### ISSUE THREAD

**Issue by vanng822** [gographics/imagick#28]
Not sure if it happens in older versions but in this version ImageMagick 6.8.9-8 have problem free memory. According to document the returned result is a string constant. I think there are more than this method.

imagick.test(99771,0x7fff7d11a300) malloc: *** error for object 0x44eddb5: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff94201282
signal arrived during cgo execution

The code is simply:

import (
	"github.com/gographics/imagick/imagick"
	"testing"
)
func TestGetVersion(t *testing.T) {
	imagick.GetVersion()
}

**Comment by justinfx** [comment]
Yea that looks to be a bug for sure. You are correct that it should not be freeing that string. I think I have fixed a similar bug like this before, and there could be others.

**Comment by phacops** [comment]
Same problem as https://github.com/gographics/imagick/pull/20.

**Comment by vanng822** [comment]
Same for GetCopyright, GetPackageName, GetReleaseDate
