### ISSUE TITLE
How do I use it in redhat?

### ISSUE THREAD

**Issue by Zz-Quan** [gographics/imagick#281]
Hi, I just want to use it in redhat ,not in ubuntu/debian. What should I do?

**Comment by justinfx** [comment]
Did you try googling how to install ImageMagick on redhat? A quick google search will turn up instructions like:

```
$ yum update
$ yum install ImageMagick-devel
```

Or you can manually download a specific ImageMagick version (6 vs 7) and use `rpm` to install it.

**Comment by Zz-Quan** [comment]
I did, but it gave me an error:
```
../go/pkg/mod/gopkg.in/gographics/imagick.v2@v2.6.1/imgick/filter_type.go:8:34: fatal error: wand/MagickWand.h: No such file or directory.
#include <MagicWand/MagickWand.h>
```

**Comment by justinfx** [comment]
Which version did yum end up installed? If its ImageMagick7 then you need the v3 branch of imagick

**Comment by Zz-Quan** [comment]
Its ImageMagick6.7.8.9-15.Do I have to configure something?

**Comment by justinfx** [comment]
From the README:

```
We support two compatibility branches:

  master (tag v2.x.x): 6.9.1-7 <= ImageMagick <= 6.9.9-35
  im-7   (tag v3.x.x): 7.x     <= ImageMagick <= 7.x
  legacy (tag v1.x.x): 6.7.x   <= ImageMagick <= 6.8.9-10

They map, respectively, through gopkg.in:
  
  gopkg.in/gographics/imagick.v2/imagick
  gopkg.in/gographics/imagick.v3/imagick
  gopkg.in/gographics/imagick.v1/imagick
```

That ImageMagick your redhat is picking up is very very old and means you would need to use: `gopkg.in/gographics/imagick.v1/imagick`

You may need to check your version of redhad and see if you can get a newer version from the yum repository. Otherwise you have to build a newer version from source or download a newer one via rpm.

**Comment by Zz-Quan** [comment]
Thanks a lot! It solved my problem perfectly! 🐂🍺

**Comment by justinfx** [comment]
Awesome!
