### ISSUE TITLE
When PDF converted to PNGs, white margin is lost

### ISSUE THREAD

**Issue by agarwalanirudh** [gographics/imagick#290]
Upon converting PDF to PNG, it is losing white margins. Although the issue gets fixed upon trying JPG. Is there a way to retain white margins in PNG?
<img width="1781" alt="image" src="https://user-images.githubusercontent.com/29160366/223727715-0f2a28a2-5bd7-415f-ab55-7cda60ace77c.png">

**Comment by justinfx** [comment]
Seems like a question better suited for the ImageMagick forum. Did you try reading about how to control the page and crop sizes? 
https://www.imagemagick.org/Usage/crop/#crop_repage

Possibly:
https://pkg.go.dev/gopkg.in/gographics/imagick.v3/imagick?utm_source=godoc#MagickWand.SetImagePage
or
https://pkg.go.dev/gopkg.in/gographics/imagick.v3/imagick?utm_source=godoc#MagickWand.ResetImagePage
