### ISSUE TITLE
ERROR_MISSING_DELEGATE: no decode delegate for this image format `WEBP' @ error/blob.c/BlobToImage/353

### ISSUE THREAD

**Issue by susanhuhu** [gographics/imagick#293]
I have a golang program and refer to  "gopkg.in/gographics/imagick.v2/imagick"
I have below code

        imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	err := mw.ReadImageBlob(data)
	if err != nil {
		return nil, NewMalformedInputError(
			fmt.Sprintf("Error when trying to parse image: %v", err))
	}

When running for a webp image, I got error "no decode delegate for this image format `WEBP' @ error/blob.c/BlobToImage/353"
I saw another answer says I need to install libwebp-dev and rebuild imagick,   but my code is refering to imagick,  how shall I work around this error please?

**Comment by justinfx** [comment]
The Go imagick library is a binding for the C lib ImageMagick. So it is the C library that does all of the real work, including interfacing with all of the file format delegate plugins. This error means that the C ImageMagick you are linking against is missing support for webp.  You would need to recompile your C ImageMagick with support for webp, and then your Go code should start working correctly.

**Comment by susanhuhu** [comment]
thanks, I just figured out the same thing.   If I install v7  of ImageMagick and refer to gopkg.in/gographics/imagick.v3/imagick, it will work.  However, there is no easy way to install v7 of libmagickwand-dev and I need to follow quite amount of manual step to install v7 ImageMagick [steps](https://linuxopsys.com/topics/install-latest-imagemagick-on-ubuntu-20-04) . This will make my Dockerfile look very complex.

**Comment by justinfx** [comment]
We build ImageMagick from source in our own Dockerfile to allow the tests to run against specific versions of ImageMagick 6 and 7
https://github.com/gographics/imagick/blob/v3.4.2/Dockerfile

Depending on the verison of the Ubuntu image you are using, ImageMagick 6 or 7 maybe be available directly from apt. Otherwise you have to find another apt repo to add to pick up the version you want.
