### ISSUE TITLE
Missing MagickAutoThresholdImage

### ISSUE THREAD

**Issue by albertmonzo** [gographics/imagick#295]
https://imagemagick.org/api/magick-image.php#MagickAutoThresholdImage

**Comment by justinfx** [comment]
Looks like it was added in ImageMagick 7.0.8-41 : https://github.com/ImageMagick/ImageMagick/commit/d88d0f52048e8fcc0c8b54563d7c079e3b71a436

And we are testing up to 7.0.8-11. So we will need to check and add the handful of methods from that commit.

**Comment by justinfx** [comment]
@albertmonzo I have added the AutoThresholdImage method via the [295_MagickAutoThresholdImage](https://github.com/gographics/imagick/tree/295_MagickAutoThresholdImage) branch: https://github.com/gographics/imagick/commit/cb104acee998faec64ef9710a9dbd0a11bea8f37

Was that all you needed to be added?

I can release as a new minor, which would bump the minimum ImageMagick7 version to 7.0.8-41

**Comment by justinfx** [comment]
Tagged v3.5.0
