### ISSUE TITLE
GetImageBlob() doesn't convert the blob type

### ISSUE THREAD

**Issue by Lioncat2002** [gographics/imagick#298]
I am trying to convert a pdf file into images,

Here's my code:
```go
package main

import (
	"fmt"
	"os"

	"gopkg.in/gographics/imagick.v2/imagick"
)

func main() {
	// Initialize ImageMagick
	imagick.Initialize()
	defer imagick.Terminate()

	// Create a new Imagick object
	mw := imagick.NewMagickWand()
	defer mw.Destroy()

	// Read the PDF file into the MagickWand
	if err := mw.ReadImage("week6.pdf"); err != nil {
		fmt.Println("Error reading PDF:", err)
		return
	}

	// Get the total number of pages in the PDF
	numPages := mw.GetNumberImages()
	fmt.Println(numPages)
	var i uint
	// Iterate through the pages of the PDF and convert each page to PNG
	for i = 0; i < numPages; i += 1 {
		ok := mw.SetIteratorIndex(int(i))
		if !ok {
			fmt.Println("Error setting iterator index:")
			return
		}
		mw.SetImageFormat("png")
		pageNumber := i + 1
		pageFileName := fmt.Sprintf("page%d.png", pageNumber)

		err := mw.WriteImage(pageFileName)
		if err != nil {
			fmt.Printf("Error saving page %d to file: %v\n", pageNumber, err)
		}
		imgBlob := mw.GetImageBlob()
		os.WriteFile("test.png", imgBlob, os.ModeType)
	}
	// Clean up
	mw.Clear()

	fmt.Println("PDF pages converted to PNG and saved to files.")
}
```

This works fine when I do the `err := mw.WriteImage(pageFileName)` which writes images to disk in the proper png format
However if I do
```go
imgBlob := mw.GetImageBlob()
os.WriteFile("test.png", imgBlob, os.ModeType)
```
The resulting file outputted is in a pdf format?
Like the test.png cannot be opened normally, making it test.pdf, and it opens.

**Comment by justinfx** [comment]
As far as the ImageMagick docs are concerned, you seem to be doing the right thing. `SetImageFormat` is calling `MagickSetImageFormat`, and `GetImageBlob` calls `MagickGetImageBlob`, which is supposed to be influenced by the image format.

What version of Imagemagick6 are you using? Have you tried a newer version?
Have you tried ImageMagick7? This could be a bug that has been fixed.

**Comment by Lioncat2002** [comment]
@justinfx 
I am using 6.9.9-35,
I will try it out with 7 once

**Comment by Lioncat2002** [comment]
Ahhh it worked with ImageMagick 7
Thank you!
Sorry for the trouble!

**Comment by justinfx** [comment]
It was no trouble at all. I'm glad to hear that it was apparently a bug that was fixed in more recent releases.
