### ISSUE TITLE
Pango font

### ISSUE THREAD

**Issue by BrandSnob** [gographics/imagick#300]
Hello,
I have been having a difficult time trying to get `mw.ReadImage("PANGO:Hello")` work, actually it works, but the text is not printed with the font i did set via `mw.SetFont("Custom-Light")`
I have used [imagick_type_gen.pl](https://www.imagemagick.org/Usage/scripts/imagick_type_gen) script to make Imagemagick know the font.
`magick -list font` outputs:
```
Font: Custom-Light
    family: Custom
    style: Normal
    stretch: Normal
    weight: 300
    glyphs: /root/.fonts/Custom-Light.ttf
```
The font file is also available at `/root/.fonts/Custom-Light.ttf` with 0644 permission.
However, `mw.SetPointsize(...)` works just fine.
I have also read https://imagemagick.org/script/resources.php and correctly set `MAGICK_CONFIGURE_PATH` and `MAGICK_FONT_PATH` to `/usr/local/etc/ImageMagick-7` which the type.xml and other xml configuration files are available. (however, anyway, `magick -list font` output as expected)

So so, I am stuck for two days trying to figure it out, but failing.
The last thing i can think about is that there is an issue in `Imagick` package.

**Comment by justinfx** [comment]
> The last thing i can think about is that there is an issue in Imagick package.

I would like to point out, as with many other issues related to 3rd party delegate plugins, that Imagick is a pretty thin wrapper around the ImageMagick C library. It basically does nothing specific with delegate plugins and mostly just performs the type conversions before calling into C.

That being said, I have not investigated your specific issue.
