### ISSUE TITLE
Build error with the latest IM version

### ISSUE THREAD

**Issue by dooman87** [gographics/imagick#303]
Hi, I'm getting the following error when trying to build go application with IM 7.1.1-27:

```
43.25 # gopkg.in/gographics/imagick.v3/imagick
43.25 cgo: /go/pkg/mod/gopkg.in/gographics/imagick.v3@v3.4.2/imagick/channel_statistics.go:16:6: unexpected: 16-byte float type - long double
```

I have a feeling it could be related to [these changes to IM](https://github.com/ImageMagick/ImageMagick/commit/1f241fd314bd03acdfe58bab13f85e3c757feeb9#diff-34afc29457c545cfa0be186458e8c0632568d21a8b22af179aaf0f7434543eff), but I'm not sure what would be the way to fix this

**Comment by justinfx** [comment]
Duplicates #301
Fixed in v3.5.1

**Comment by dooman87** [comment]
Sorry, for no trying a new version. This problem is fixed now. The interesting thing though behaviour seemed to got changed and on the latest version of IM (7.1.1-27) I'm getting this error when doing `mw.ReadImageBlob`:

`EXCEPTION_ERROR: time limit exceeded `' @ error/cache.c/GetImagePixelCache/1703`

That didn't happen before and I didn't change my code. I'm still investigating to make sure the problem is not on my side :)

**Comment by dooman87** [comment]
Seems to be complete unrelated, so please ignore me :)

I opened a discussion thread in IM project: https://github.com/ImageMagick/ImageMagick/discussions/7091

**Comment by dooman87** [comment]
It's all fixed now! Dirk pushed some changes and everything is back to normal.
