### ISSUE TITLE
panic occurs in the GetImageBlob function

### ISSUE THREAD

**Issue by SpacemanZoey** [gographics/imagick#308]
I'm using gopkg.in/gographics/imagick.v2 v2.6.3 to convert pdf to jpg. In line "ret := C.GoBytes(unsafe.Pointer(csblob), C.int(clen))", it reports a panic. Is there anything to check csblob or clen is valid, or how to fix it
<img width="687" alt="image" src="https://github.com/gographics/imagick/assets/47808423/067fd4f6-1b7a-4bd0-b339-5158bc4e77af">

**Comment by justinfx** [comment]
Do you happen to have a reproduction that you could provide?

It may be the case that we need to check Getlasterror before we try and use the results.

You could also set the env var `MAGICK_DEBUG` to either `Trace` or `Blob` to see if it reports the underlying problem.

https://imagemagick.org/script/command-line-options.php#debug

**Comment by justinfx** [comment]
I was able to fix it by adding a check for C API ImageMagick errors, before calling our conversions.

**Comment by justinfx** [comment]
Tagged v2.6.4 and v3.5.3
