### ISSUE TITLE
Go Imagick installation on windows

### ISSUE THREAD

**Issue by oisee** [gographics/imagick#31]
Can you describe more precise how to install **Go Imagick** on windows? (Windows 8.1 x64, ImageMagick-6.9.0-Q16 x86/x64 both installed.)

All i can get is:
`PS E:\users\user\dev\golang> go get github.com/gographics/imagick/imagick`
`# pkg-config --cflags MagickWand MagickCore`
`pkg-config: exec: "pkg-config": executable file not found in %PATH%`

And, after, somehow, i've got pkg-config-lite (for windows): an output became even more hopeless:

`PS E:\users\user\dev\golang> go get github.com/gographics/imagick/imagick`
`# pkg-config --cflags MagickWand MagickCore`
`pkg-config: exec: "pkg-config": executable file not found in %PATH%`
`PS E:\users\user\dev\golang> go get github.com/gographics/imagick/imagick`
`# pkg-config --cflags MagickWand MagickCore`
`Package MagickWand was not found in the pkg-config search path.`
`Perhaps you should add the directory containing 'MagickWand.pc'`
`to the PKG_CONFIG_PATH environment variable`
`No package 'MagickWand' found`
`Package MagickCore was not found in the pkg-config search path.`
`Perhaps you should add the directory containing 'MagickCore.pc'`
`to the PKG_CONFIG_PATH environment variable`
`No package 'MagickCore' found`

Where can i get 'MagickWand.pc'? What kind of compiler (msvc/mingw) should i use? (Hope, it is a relevant question). 
Can i install **Go Imagick** without pkg-config?

It may sound like a stupid question, but: "Is it even possible to install **Go Imagick** on windows?" 
(BTW, it installs like a charm on mac/linux =)

**Comment by hgfischer** [comment]
It should be possible to do it, however I don't have access to a Windows machine to try it and definitely we need volunteers to do it.

Looks like you need to finish the setup of pkg-config-lite, and include it in your PATH before proceeding.

Inside your "imagick" dir in your GOPATH, you can play with the `go build` flags that set the path for your includes and libraries, for example:

`go build -ccflags '-I ~/path/to/magickwand/includes' -gccgoflags '-I
~/path/to/magickwand/includes' -gcflags '-I ~/path/to/magickwand/includes' -ldflags '-L
~/path/to/magickwand/libs'

**Comment by oisee** [comment]
Herbert, thank you very much for your help.

pkg-config-lite is in PATH, and surely it is called on 'go build' command. Unfortunately, it's complaining that 'MagickWand.pc'/'MagickCore.pc' is not found. I wish i could specify PATH to those files, but I cannot locate those files myself (looks like there are no such files in /ImageMagick directory at all, and I didn't find files on my mac as well).

On command:
`go build -tags no_pkgconfig -ccflags '-I C:\lib\imagemagick64\include' -gccgoflags '-I C:\lib\imagemagick64\include' -gcflags '-I C:\lib\imagemagick64\include' -ldflags '-L C:\lib\imagemagick64\lib'`

i get this:
`# github.com/gographics/imagick/imagick
.\affine_matrix.go:8:29: fatal error: wand/MagickWand.h: No such file or directory
compilation terminated.`

And that's strange, looks like compiler didn't find 'C:\lib\imagemagick64\include' where the headers are located. But those guys are there:
`PS C:\lib\imagemagick64\include> ls
Directory C:\lib\imagemagick64\include
magick
Magick++
wand
Magick++.h`

Thats all, i'm stuck here. Even moving headers to src\github.com\gographics\imagick\imagick didn't help a bit. I'm still getting this:
`# github.com/gographics/imagick/imagick
.\affine_matrix.go:8:29: fatal error: wand/MagickWand.h: No such file or directory`

And should I specify all those flags: "-ccflags -gccgoflags -gcflags", or "-gccgoflags" is enough?

**Comment by hgfischer** [comment]
Do you have the file `MagickWand.h` located somewhere in you computer?

**Comment by oisee** [comment]
Yes, it is here: **C:\lib\imagemagick64\include\wand**, and here: **golang\src\github.com\gographics\imagick\imagick\wand** (i moved entire C:\lib\imagemagick64\include\ into golang\src\github.com\gographics\imagick\imagick\ ).

**Comment by hgfischer** [comment]
I wouldn't move the include files inside the imagick project.

I would try installing the ImageMagick 6.8.5 (same version we used in this binding) from source in some other directory then playing with the `go build` flags to try building the project.

**Comment by oisee** [comment]
Thank you, i'll try that.

Which compiler should i use? MS/MinGW? (Is there any difference for binding?)

**Comment by hgfischer** [comment]
Quoting [1]:

> In order to use cgo on Windows, you'll also need to first install a gcc compiler (for instance, mingw-w64) > and have gcc.exe (etc.) in your PATH environment variable before compiling with cgo will work.

[1] https://code.google.com/p/go-wiki/wiki/cgo

**Comment by oisee** [comment]
Little progress, though no luck with building ImageMagick with mingw, but i've hacked a bit pkg-config: providing it a MagicWand.pc/MagickCore.pc files from mac installation of ImageMagic, so command:

`pkg-config --cflags --libs MagickWand` 
produce this output:
`-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -IC:/l
ib/imagemagick64/include/ImageMagick-6 -LC:/lib/imagemagick32/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16` 

So, now these files/folders: magick Magick++ wand Magick++.h are here: C:/l
ib/imagemagick64/include/ImageMagick-6

and the command 
`go build` 
goes a little bit further:
`# github.com/gographics/imagick/imagick
could not determine kind of name for C.IsMagickInstantiated`

Looks like headers are ok now, but go compiler cannot locate suitable libs.

I'm not sure what output `pkg-config --libs MagickWand` should produce, because **C:\lib\imagemagick64\lib** folder contains only these files: 

`CORE_RL_Magick++_.lib`
`CORE_RL_magick_.lib`
`CORE_RL_wand_.lib`
`X11.lib`

Nothing like "MagickWand-6.Q16" or "MagickCore-6.Q16". I've tried to change MagicWand.pc/MagickCore.pc files, making `pkg-config --libs MagickWand` producing:
`-LC:/lib/imagemagick32/lib -lCORE_RL_magick_.lib -lCORE_RL_wand_.lib`
But still got same answer to 
`go build` 
`# github.com/gographics/imagick/imagick
could not determine kind of name for C.IsMagickInstantiated`

**Comment by hgfischer** [comment]
I would check if someone else has similar issues with another cgo binding. 

Don't know if this can help, but my Linux machine gives the following output for `pkg-config --libs MagickWand`:

`-lMagickWand -lMagickCore`  

cheers

**Comment by oisee** [comment]
Finally, with this ` -lCORE_RL_wand_ -lCORE_RL_magick_` (no .lib extension) pkg-config output (and some dirty hacks due to C.MagickRadialBlurImage is deprecated) **imagick** is compiled.

But when i'm trying to build examples( i get this:
`github.com\gographics\imagick\examples\landscape3d> go build`
`github.com/gographics/imagick/imagick(.text): fdopen: not defined`
`github.com/gographics/imagick/imagick(.text): undefined: fdopen`

Google says that it's, somehow, a mingw problem. 

Thank you for your support =)

**Comment by oisee** [comment]
After replacement **fdopen** with **_fdopen**, and rebuilding imagick, some examples compiles.
(Some of them are not working because of version difference: i have 6.9.x - didn't find old 6.8.5. distribution.)

**Comment by LeonB** [comment]
I'm having the same issue :( I can't get it to work.

**Comment by iincity** [comment]
I'm having the same issue too

**Comment by juanmachuca95** [comment]
I'm having the same issue too. They could provide the steps to solve this problem.

**Comment by justinfx** [comment]
@juanmachuca95 this is a very old ticket and since then there have been newer windows tickets which resulted in some added installation instructions. Are you saying that even with the updated instructions, you still have this original issue?
