### ISSUE TITLE
Channel statistics unexpected type

### ISSUE THREAD

**Issue by f01c33** [gographics/imagick#314]
Hi, i'm having this issues using imagick.v3 on my arch linux with imagemagick 7.1.1.32-1:
```
# gopkg.in/gographics/imagick.v3/imagick
cgo: vendor/gopkg.in/gographics/imagick.v3/imagick/channel_statistics.go:16:6: unexpected: 16-byte float type - long double
```
Example code at https://github.com/f01c33/buddy

**Comment by justinfx** [comment]
Are you using the latest v3 release? This looks like something we addressed 4 months ago:
https://github.com/gographics/imagick/issues/301

**Comment by justinfx** [comment]
Looks like you are not on the latest release:
https://github.com/f01c33/buddy/commit/b6cdd9aee0b48a5ca42e804a96a5a9c49ca462ab#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R8

Make sure to use the latest release, and check history, before bug reports. Cheers!

**Comment by f01c33** [comment]
thanks, that fixed it
