### ISSUE TITLE
Depreciation Warnings on Build

### ISSUE THREAD

**Issue by tmilewski** [gographics/imagick#32]
Not a huge deal for now as everything still works, but, I've found that this - for some reason - exponentially increases the build time:

```
# github.com/gographics/imagick/imagick
../../gographics/imagick/imagick/magick_core_env.go:54:23: warning: 'IsMagickInstantiated' is deprecated [-Wdeprecated-declarations]
/usr/local/Cellar/imagemagick/6.8.9-8/include/ImageMagick-6/magick/deprecate.h:203:3: note: 'IsMagickInstantiated' has been explicitly marked deprecated here
# github.com/gographics/imagick/imagick
../../gographics/imagick/imagick/magick_wand_image.go:3014:23: warning: 'MagickRadialBlurImage' is deprecated [-Wdeprecated-declarations]
/usr/local/Cellar/imagemagick/6.8.9-8/include/ImageMagick-6/wand/deprecate.h:109:3: note: 'MagickRadialBlurImage' has been explicitly marked deprecated here
../../gographics/imagick/imagick/magick_wand_image.go:3031:23: warning: 'MagickRadialBlurImageChannel' is deprecated [-Wdeprecated-declarations]
/usr/local/Cellar/imagemagick/6.8.9-8/include/ImageMagick-6/wand/deprecate.h:111:3: note: 'MagickRadialBlurImageChannel' has been explicitly marked deprecated here
```

Thanks!

**Comment by tmilewski** [comment]
Quick update:

A-OK: `6.8.8-9`
Depreciation Warnings: `6.8.9-8`

**Comment by justinfx** [comment]
@hgfischer , I've pushed a couple branches related to these deprecated warnings. `im-6.8.9` contains the fixes for these deprecation warnings, though I am not sure how you want to go about maintaining the master branch. We could merge it and make the master branch require `>= 6.8.9`, and I have a `im-6.8.8` branch for older ImageMagick installs. 

There are some notes in the README about keeping various functionality disabled, for 6.7/6.8.0 compat, so I got the sense that you were still holding out on the master branch?

**Comment by hgfischer** [comment]
I think that keeping the master with latest ImageMagick versions could lead to a complicated installation process.

I'm a Ubuntu LTS user (currently 14.04) and my ImageMagick version is 6.7. What about you?

**Comment by justinfx** [comment]
In my own case, on OSX, homebrew delivers 6.9.1. And in my production Linux
usage at work, we have multiple packages available, so I can build against
either.

I can see arguments both ways. It is convenient for it to be able to
automatically build against a system install, with no fuss. But to do that,
you have to keep it compatible to older versions.

I suppose we can just maintain the 6.9 branch and keep the master as
compatible.

**Comment by hgfischer** [comment]
Ok. That's a good approach.

**Comment by justinfx** [comment]
Ok. I've left only the `im-6.8.9` branch, which contains changes targeted at >= 6.8.9, and removed the other branch/tag

**Comment by MorganWu** [comment]
It seems there is a little issue with the mapping of branches and Imagemagick versions in the readme file.

**Comment by justinfx** [comment]
I've updated the README in both branches, and also uncommented the code in the 6.8.9 branch was that was previously disabled
