### ISSUE TITLE
mw.GetColorspace() seem to always return COLORSPACE_UNDEFINED

### ISSUE THREAD

**Issue by tophe** [gographics/imagick#323]
hi Justin,

can you try than code extract 
[imcolorspace.zip](https://github.com/user-attachments/files/15534811/imcolorspace.zip)

as you can see, calling mw.GetColorspace() don't return the expected colorspace but COLORSPACE_UNDEFINED. 
You can read the colorspace with identify img.jpg. (or identify -verbose ...)

**Comment by justinfx** [comment]
There are a whole bunch of problems in your example code.

* Reading the wrong cmyk file and not checking the error
* Using `GetColorspace` instead of `GetImageColorspace`
* Using `COLORSPACE_RGB` when the file is actually `COLORSPACE_SRGB`

Can you please confirm the following?

```go
func main() {
	mw := imagick.NewMagickWand()
	err := mw.ReadImage("t_srgb.jpg")
	if err != nil {
		log.Fatal(err)
	}

	colorspace := mw.GetImageColorspace()
	if colorspace != imagick.COLORSPACE_SRGB {
		fmt.Printf("GetImageColorspace: " +
			"colorspace (%v) != srgb (%v) !\n", colorspace, imagick.COLORSPACE_SRGB)
	}

	err = mw.ReadImage("b_cmyk.jpg")
	if err != nil {
		log.Fatal(err)
	}

	colorspace = mw.GetImageColorspace()
	if colorspace != imagick.COLORSPACE_CMYK {
		fmt.Printf("GetImageColorspace: colorspace (%v) != cmyk !\n", colorspace)
	}
}
```

**Comment by tophe** [comment]
hi justin, that's incredible, so many errors in such a little example.
thank you, for the help.

I close that non issue !

**Comment by justinfx** [comment]
All good! It's better that it's just a simple error instead of a hard-to-fix bug.
