### ISSUE TITLE
CGO Build failure on imagemagick 7.1.1-36

### ISSUE THREAD

**Issue by freakmaxi** [gographics/imagick#326]
Hello,

go build fails on Linux when the ImageMagick 7.1.1-36 release has been used. The error message is the following

`68.71 gopkg.in/gographics/imagick.v3/imagick: gcc: signal: illegal instruction`

I'll find out more underlying reasons when I have time. The same configuration creates no problem when the ImageMagicK 7.1.1-35 release has been used.

**Comment by coderkun** [comment]
For me the build works fine (even after running `go clean -cache`).

```
$ magick -version
Version: ImageMagick 7.1.1-36 Q16-HDRI x86_64 22352 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib zstd
Compiler: gcc (14.1)
```

**Comment by justinfx** [comment]
Thanks for confirming, @coderkun!

@freakmaxi maybe the specific details are key such as whether you are building through a docker container, or on your Linux host directly. And which version of gcc, etc, are involved. Lot of pieces when building ImageMagick from source as well.

**Comment by freakmaxi** [comment]
To be honest, I've also realized that it is built on an amd64 Linux machine both using native and docker. however, it is not building on docker with Apple Silicon targetted to Linux/amd64.

I'm using "golang:latest" image to build ImageMagick and Go software. it has gcc (Debian 12.2.0-14) 12.2.0.

Here are my configuration options

```
./configure \
	    --without-magick-plus-plus \
	    --without-perl \
	    --disable-openmp \
	    --with-gvc=no \
	    --disable-docs
```

It compiled and installed ImageMagick without any problem. The problem is happening when I run `go build` command.

I'm trying to understand what is changed between 7.1.1-35 and 7.1.1-36 that causing `illegal instruction` problem

**Comment by justinfx** [comment]
That is quite a specific build situation to repro the problem. Needs an Apple chip host machine running a Linux docker image. I wonder if the crash is actually specific to Go, or if some example C program would also crash when building against ImageMagick. Maybe try compiling the example code that comes with ImageMagick?

**Comment by GwynethLlewelyn** [comment]
For what's worth... compiling under Go version go1.22.5 linux/amd64 (Ubuntu 24.04 + ImageMagick 7.1.1-37ß/gcc 13.2) works flawlessly (bare metal, no virualisation/containerisation)  as well as under go1.22.5 darwin/amd64 (macOS 11.7.9 /Darwin Kernel Version 20.6.0 + ImageMagick 7.1.1-36/gcc 4.2), also bare metal and no virtualisation.

**Comment by freakmaxi** [comment]
We need someone who has ARM machine and trying to build the image for AMD64 machine on virtualisation or docker. 

- I've checked the build on my Intel Mac, it worked. 
- I've checked on my AMD Razor with linux, it worked. 
- I've try to build on my Apple Silicon M3 Mac for ARM arch, it worked

However when I use ARM machine to build for AMD64 arch, it fails. It fails both on docker and virtualisation (UTM). I'm checking gcc forums and issue boards but nobody report something like this. I don't know if it is because of gcc, or my Mac or Imagemagick 7.1.1-36. The fun part is 7.1.1-35 can be built successfully on all combinations.

**Comment by justinfx** [comment]
@freakmaxi I have an M1 laptop so I was able to run some tests. 

Using the Dockerfile that is part of this repro, for the CI pipeline, I locally updated to `FROM golang:1.22.5`:
https://github.com/gographics/imagick/blob/im-7/Dockerfile

```
export VER=7.1.1-36
docker build --build-arg IMAGEMAGICK_VERSION=${VER} --platform linux/amd64 -t gographics/imagick.v3:${VER} .
docker run -it --rm --platform linux/amd64 -v $(PWD):/go/projects/imagick  gographics/imagick.v3:${VER} go test -v ./imagick
```

The code build and the tests all passed. Can you please review the Dockerfile and provide more specific details about the build and run commands to repro the issue?

**Comment by justinfx** [comment]
@freakmaxi is this relevant to your repro?
https://www.reddit.com/r/golang/s/U1qH294eKE

**Comment by freakmaxi** [comment]
@justinfx yes it is relevant. I've also solved it with a pipeline running on amd64 for now. However, still on track and investigating to find out the underlying reason because it is weird to work one previous version but not the latest one.

**Comment by justinfx** [comment]
@freakmaxi i suppose it depends on what they changed between releases that conflicts with platform specific differences. Since this doesn't have anything to do with the bindings, I'm going to close this ticket.

**Comment by freakmaxi** [comment]
Hello,

I want to share the solution to the problem. 

This and similar problems started appearing on multiple projects including packages updates of Ubuntu on Docker build. After countless hours of searching in multiple, websites, issue trackers, and forums, I discovered that it was about the Docker using Rosetta for amd64 for virtualization.

After disabling the Rosetta from the Docker settings, everything started working as expected without any problem. I believe Apple changed something on Rosetta in Sonoma.

I hope this can be the solution for anyone struggling with the same thing.

**Comment by justinfx** [comment]
Does that settings fix work separately from using the platform flag when building? Because I didn't need to adjust docker settings on my M1. I only needed to set the platform flag to avoid seeing a crash.
Thanks for reporting back with that fix.

**Comment by freakmaxi** [comment]
Nope, still need to set the platform flags. This is happening mostly on M2 and M3 Apple Silicon (At least what I realized in different forums) on Docker with Rosetta. Maybe it is something related to the version of the Apple Silicon.
