### ISSUE TITLE
resize img , have a error

### ISSUE THREAD

**Issue by hhservice** [gographics/imagick#38]
resize img , occur a error
Memory allocation failed `No such file or directory' @ fatal/tiff.c/UnregisterTIFFImage/2262.

**Comment by justinfx** [comment]
Please give a reproduction for this problem.
What version of ImageMagick and how did you build it. Could possibly be
related to the tiff plugin.

**Comment by hhservice** [comment]
ImageMagick-6.8.9-10, build with src, 
//get img from ssdb
img, err := ssdb.Get(md5Str)
	if err != nil {
		log.Println(err)
		return
	}
	imgByte := []byte(img)

	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	defer mw.Destroy()

	err = mw.ReadImageBlob(imgByte)
	if err != nil {
		//panic(err)
		log.Println(err.Error())
	}

	width := mw.GetImageWidth()
	height := mw.GetImageHeight()

	// Calculate half the size
	hWidth := uint(width / 2)
	hHeight := uint(height / 2)

	err = mw.ResizeImage(hWidth, hHeight, imagick.FILTER_LANCZOS, 1)
	if err != nil {
		//panic(err)
		log.Println(err)
	}

	Set the compression quality to 95 (high quality = low compression)
	err = mw.SetImageCompressionQuality(95)
	if err != nil {
		panic(err)
	}

	err = mw.DisplayImage(os.Getenv("DISPLAY"))
	if err != nil {
		panic(err)
	}

	w.Write(mw.GetImageBlob())  
// this img return to web request , only return once, the second time visit this page occur a error.

**Comment by justinfx** [comment]
Don't use this in the body of a handler

imagick.Initialize()
defer imagick.Terminate()

That should be done once in your main (or once by some other means) . I
believe it is the Terminate that is causing the problem.

**Comment by hhservice** [comment]
in the web app, defer imagick.Terminate() can't execute,  thinks.
