### ISSUE TITLE
how install into windows

### ISSUE THREAD

**Issue by dtxlink** [gographics/imagick#42]
ths

**Comment by dtxlink** [comment]
LiteIDE
ERROR:

c:/go/bin/go.exe build -i [C:/GoPath/src/github.com/gographics/imagick/imagick]
# pkg-config --cflags MagickWand MagickCore
Package MagickWand was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickWand.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickWand' found
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickCore' found
pkg-config: exit status 1
错误: 进程退出代码 2.

**Comment by justinfx** [comment]
Do you have ImageMagick installed? Is it in a custom location?

**Comment by alexxbb** [comment]
Hi, please help with a problem. Can't find headers!
**Go version 1.5, windows 8.1x64, MinGW x64 5.1.0**
*go build -x -tags no_pkgconfig -gcflags "-I c:/Users/Alex/build/imagemagick_deploy/include" github.com/gographics/imagick/imagick*

Content of c:/Users/Alex/build/imagemagick_deploy/include:
magick/
Magick++/
wand/  <------- MagickWand.h here
Magick++.h

Result:
*...gographics\imagick\imagick\affine_matrix.go:8:29: fatal error: wand/MagickWand.h: No such file or directory*

Any ideas? Thanks!

**Comment by justinfx** [comment]
Hi

Make sure to read the README, because you aren't using correct flags.
Set CGO_CFLAGS environment variable to your "-I <include path>" and set
CGO_LDFLAGS environment variable to your "-L <library path> -l MagickCore
-l MagickWand" bit.

**Comment by justinfx** [comment]
Going to close this issue because it has had no replies in over 3 months, and I assume you managed to get a windows build working.
