### ISSUE TITLE
deprecated warning and more than 5 minutes to start ?

### ISSUE THREAD

**Issue by benyu** [gographics/imagick#45]
$convert --version
Version: ImageMagick 6.9.0-3 Q16 x86_64 2015-01-09 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png xml zlib

go run bin/main.go
>after 5 minutes show warning:
# github.com/gographics/imagick/imagick
../../../lib/src/github.com/gographics/imagick/imagick/magick_core_env.go:54:23: warning: 'IsMagickInstantiated' is deprecated [-Wdeprecated-declarations]
/usr/local/Cellar/imagemagick/6.9.0-3/include/ImageMagick-6/magick/deprecate.h:205:3: note: 'IsMagickInstantiated' has been explicitly marked deprecated here
# github.com/gographics/imagick/imagick
../../../lib/src/github.com/gographics/imagick/imagick/magick_wand_image.go:3014:23: warning: 'MagickRadialBlurImage' is deprecated [-Wdeprecated-declarations]
/usr/local/Cellar/imagemagick/6.9.0-3/include/ImageMagick-6/wand/deprecate.h:109:3: note: 'MagickRadialBlurImage' has been explicitly marked deprecated here
../../../lib/src/github.com/gographics/imagick/imagick/magick_wand_image.go:3031:23: warning: 'MagickRadialBlurImageChannel' is deprecated [-Wdeprecated-declarations]
/usr/local/Cellar/imagemagick/6.9.0-3/include/ImageMagick-6/wand/deprecate.h:111:3: note: 'MagickRadialBlurImageChannel' has been explicitly marked deprecated here

**Comment by justinfx** [comment]
Can you try switching to the `im-6.8.9` branch and installing? We have made the deprecation fixes in this branch, but have kept the master branch compatible to earlier versions of ImageMagick

**Comment by justinfx** [comment]
Closing, since this relates to the im-6.8.9 branch
