### ISSUE TITLE
MagickWand CoalesceImages memory leak?

### ISSUE THREAD

**Issue by yayaayay** [gographics/imagick#47]
Hi, sorry to bother you again. I was doing some testing since one of my applications' memory footprint seemed quite large and discovered that when using [MagickWand.CoalesceImages()](http://godoc.org/github.com/gographics/imagick/imagick#MagickWand.CoalesceImages) the memory is never cleared after the wand is destroyed.

I'm running Arch Linux.

## ImageMagick version
```
Version: ImageMagick 6.9.2-0 Q16 x86_64 2015-08-18 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma pangocairo png ps rsvg tiff webp wmf x xml zlib
```
## Memory Before and After
![Memory before](http://puu.sh/jUtST/9da722af44.png)
![Memory after](http://puu.sh/jUtRk/c60b928cae.png)
Also please bear in mind that this machine has about 16GB memory

## Code used to test
```go
package main

import (
  "fmt"
  "github.com/gographics/imagick/imagick"
  "net/http"
  _ "net/http/pprof"
)

func init() {
  imagick.Initialize()
  go func() {
    http.ListenAndServe(":6060", nil)
  }()
}

func main() {
  for i := 0; i < 500; i++ {
    mw := imagick.NewMagickWand()
    if err := mw.ReadImage("test.jpg"); err != nil {
      panic(err)
    }

    mw = mw.CoalesceImages()

    mw.Destroy()
  }
  fmt.Println("Complete")
  select {}
}
```
Am I doing something wrong or is this an issue?
Again, thanks for all the hard work! Sorry to bother you

**Comment by justinfx** [comment]
Actually if you check out the doc on that function, you will see that you are leaking MagickWands each time:

```
Composites a set of images while respecting any page offsets and disposal
methods. GIF, MIFF, and MNG animation sequences typically start with an
image background and each subsequent image varies in size and offset.
CoalesceImages() returns a new sequence where each image in the sequence
is the same size as the first and composited with the next image in the
sequence.
```

Each time you loop, you are replacing one instance of a wand with another:

```
mw = mw.CoalesceImages()
mw.Destroy()
```

So you leak the original. When I change it to return a completely new variable and make sure to destroy both the original and the new one, the memory stops leaking.

Let me know if that fixes it!

**Comment by yayaayay** [comment]
Perfect. Thank you very much! It's a little bit of a pain to have to create a new magickwand entirely though, is there any reason for this?

**Comment by justinfx** [comment]
It is probably because iMagick is following the C api as closely as
possible :

http://www.imagemagick.org/api/magick-image.php#MagickCoalesceImages
