### ISSUE TITLE
Using gopkg.in to support multiple version streams?

### ISSUE THREAD

**Issue by justinfx** [gographics/imagick#52]
Currently we have the master branch acting as the compatibility branch for < ImageMagick-6.8.9, and the `im-6.8.9` branch for >= 6.8.9. This makes it a bit more complicated since it isn't go-gettable with the 6.8.9 support. 

What do we think of possibly using http://labix.org/gopkg.in, with some kind of tagging convention so that people could do:

```
# < 6.8.9
$ go get gopkg.in/gographics/imagick.v1/imagick
# >= 6.8.9
$ go get gopkg.in/gographics/imagick.v2/imagick
```

Thoughts? Not sure the best way to map the branch/tag naming to this, since our compatibility issue sits within a minor version (6.8.x). We would probably just have to keep moving 1.x and 2.x tags on the master and im-6.8.9 branches.

**Comment by hgfischer** [comment]
I like the idea in general, but I find it counter-intuitive to relate v1 or v2 with the 6.8.x version of Image Magick. What about trying some version scheme more closely related to the version of Image Magick? Maybe something like v688.0.0, v689.0.0, etc, just to fit in gopkg.in. Just some thoughts...

**Comment by phacops** [comment]
I'd rather use v1/v2. We don't need to match the exact imagemagick version. Just a note in the README explaining what branche support which version. I think it's OK like that.

**Comment by hgfischer** [comment]
OK. I can accept it. No problem. I was just trying to avoid clutter in the instructions by using something more intuitive.

Despite the tag scheme, there is another issue in using this. Any program depending on our bindings will need to stick to one tag and restrict their own users, or will also need to manage different tags/branches for different Image Magick versions. I think this can be a pain for our users.

I don't know if you already tried it, but I think we could use Go's build tags instead of having different branches for different versions of ImageMagick. What do you think?

**Comment by justinfx** [comment]
I can see points both ways. For instance, if someone is using features only available in im >= 6.9.0, then they have to ensure people use v2 anyways. It just becomes a real dependency. As for tags, I maybe I don't fully understand all the possibilities, but I have found an issue where people have to know to use the right tag in their higher-level application, to ensure the dependency builds correctly. Lets say I have a main application that uses library A. Library A depends on iMagick w/ >= 6.9. With build tags, I would have to know this and build iMagick with the right tag. I would love to know how people successfully do this. 

At least with a v1/v2 scheme, you can have either/both installed, without knowing tags. And all that matters is that you actually have ImageMagick installed.

**Comment by justinfx** [comment]
#67  has been completed. As per the question in that issue, do we care to move forward with canonical import paths? That is, `master` would have the following in the package header:

```go
package imagick // import "gopkg.in/gographics/imagick.v2/imagick"
```

And `legacy` would have the following:

```go
package imagick // import "gopkg.in/gographics/imagick.v1/imagick"
```

This would require people to start using gopkg.in as their import paths.

**Comment by hgfischer** [comment]
:+1: from me

**Comment by justinfx** [comment]
This is done. Updated README and examples in both branches. Canonical import paths are now required.
