### ISSUE TITLE
fail to build on mac !

### ISSUE THREAD

**Issue by benyu** [gographics/imagick#53]
$ pkg-config --cflags --libs MagickWand
DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/6.9.0-3/include/ImageMagick-6 -L/usr/local/Cellar/imagemagick/6.9.0-3/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16

$go get github.com/gographics/imagick/imagick
> No output

$ GOOS=linux GOARCH=amd64 go build  -o APP bin/main.go
./xx.go:399: undefined: imagick.Initialize
./xx.go:401: undefined: imagick.Terminate
./xx.go:404: undefined: imagick.NewMagickWand
./xx.go:431: undefined: imagick.FILTER_LANCZOS

but, i can run directly!
$ go run bin/main.go

**Comment by justinfx** [comment]
Are you trying to cross compile an app for Linux, which needs this
cgo-based library? This isn't the same as using "go run", which will build
normally for your osx arch.

**Comment by justinfx** [comment]
Im going to close this issue, as it looks to be doing something strange like cross compiling CGO being compared to running on the same platform.
