### ISSUE TITLE
GraphicsMagick support?

### ISSUE THREAD

**Issue by JesusIslam** [gographics/imagick#54]
Does this package support graphicsmagick?

**Comment by justinfx** [comment]
Isn't GraphicsMagick a completely separate project? This project provides bindings to the ImageMagick C API.

**Comment by JesusIslam** [comment]
Oh, OK then, I just need to know this.

**Comment by justinfx** [comment]
Not a problem! With enough work, maybe it's possible to make it build against GraphicsMagick, using build tags to handle the difference header/linker flags and any variations between the two libraries.
