### ISSUE TITLE
Determine temporary directory path used by imagick

### ISSUE THREAD

**Issue by pkieltyka** [gographics/imagick#55]
I searched the code but I couldn't find a function that returns the temporary directory used by imagick for storing temporary resources. Although, I do see temp files in /tmp/ with a `magick-` prefix. Any suggestions? sometimes these files are not cleaned up properly and I'd like to add a sweep method myself.

**Comment by xealot** [comment]
I think this is defined at the OS level and image magick just reads that.

https://golang.org/pkg/os/#TempDir

**Comment by pkieltyka** [comment]
@xealot thanks. I think you're right. I searched gographics/imagick code for "temp" and "tmp" and came up with nothing. But searching ImageMagick code, I see it references TMPDIR environment variable, which is the same way `os.TempDir()` works in go stdlib. There is also `MAGICK_TMPDIR` env var for imagemagick directly.
