### ISSUE TITLE
How to use SetImageGravity

### ISSUE THREAD

**Issue by ismasan** [gographics/imagick#56]
Hi. First off thanks so much for this library.

This is a question and not really an issue/bug. How is `SetImageGravity` supposed to be used?

My current code looks like:

```golang
// Set gravity first
err = mw.SetImageGravity(imagick.GRAVITY_SOUTH)
if err != nil {
  return
}
// Now do the cropping
err = mw.CropImage(200, 200, 0, 0)
if err != nil {
  return
}
```

Gravity does not do anything, as I would expect from the command line version:

```
convert -resize "200x200^^" -gravity South -crop "200x200+0+0"
```

Am I doing it wrong?

Thank you in advance.

**Comment by justinfx** [comment]
I'm not overly familiar with the gravity stuff, and this question is probably related to just the ImageMagick API in general, as opposed to the Go specific bindings... But some related info:

http://stackoverflow.com/questions/5820754/imagick-setting-the-gravity-on-a-imagick-item

This suggests that gravity only works on DrawingWands?

You can see the included examples only using it on DrawingWands as well:
https://github.com/gographics/imagick/search?utf8=%E2%9C%93&q=SetGravity

To be honest, I don't even think you have to check the error of the SetGravity call. When I look at the source code, if it isn't completely throwing an exception, it always returns True:
http://www.imagemagick.org/api/MagickWand/magick-image_8c_source.html#l10488

**Comment by bitflingr** [comment]
Just my two cents but there is SetGravity and SetImageGravity.  The first referring to where you want to place text or some other image on top of the image.  I too am trying to accomplish the same thing but the api seems to ignore gravity or there is some step I am missing.  I am a total noob to Go but am coming from slapping together a image resizer with Ruby/Sinatra/Dragonfly.
