### ISSUE TITLE
How to set the transparency of image, and  the func SetImageOpacity(alpha float64) has no effect 

### ISSUE THREAD

**Issue by ChengHuaUESTC** [gographics/imagick#61]
I have done watermark, rotation, crop, blur ... with imagick using golang.
Now I want to realize the transparency, and I use the func SetImageOpacity, however, it does not work.
Is there someone have some solutions?

**Comment by justinfx** [comment]
Did you ever figure this out? in #90 I had added an example which makes use of `SetImageOpacity`. It does this to overlay a watermark on a source image at 30%

**Comment by justinfx** [comment]
Closing this question since there has not been a reply. Let me know if it is still an issue.
