### ISSUE TITLE
Unable to readImage() a TIF file

### ISSUE THREAD

**Issue by rogierlommers** [gographics/imagick#65]
I'm having troubles reading a TIF file. Please see my code below. The mw.ReadImage() function panics with the following error: "panic: WARNING_CODER: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/887". A quick search learned me that it could be OSX related, but unfortunately I'm also having troubles running on Ubuntu, with latest ImageMagick and libtiff installed (from official ubuntu repo). Any ideas?

#### Edit
It looks like it's only a warming, however imagick panics. When I use the command line util from ImageMagic, it displays the error, but the image operation succeeds fine. I suggest imagick should not panic, right?

#### Edit 2
Sorry, I just noticed this issue: https://github.com/gographics/imagick/issues/44

#### Use ImageMagick itself
convert 3348900871984.tif -resize 500 klein.png
convert: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/887.
convert: Unknown field with tag 306 (0x132) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/887.
convert: Incompatible type for "FileSource"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/887.
convert: Incompatible type for "SceneType"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/887.
convert: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/887.

#### Example panic code
	imagick.Initialize()
	defer imagick.Terminate()

	inputFile := "/Users/rlommers/Desktop/3348900871984.tif"
	outputFile := "../../target/tif-resized.jpg"
	fillColor := "white"
	targetWidth := uint(300)
	targetHeight := uint(90)
	align := "right"
	log.Printf("open file [%s] and resize to [%dx%d] with color [%s], saving rendition to [%s]", inputFile, targetWidth, targetHeight, fillColor, outputFile)

	mw := imagick.NewMagickWand()
	// Schedule cleanup
	defer mw.Destroy()

	pw := imagick.NewPixelWand()
	defer pw.Destroy()
	pw.SetColor(fillColor)

	// read image
	err := mw.ReadImage(inputFile)
	if err != nil {
		panic(err)
	}

**Comment by justinfx** [comment]
Can you confirm that this was fixed by #66?

**Comment by rogierlommers** [comment]
Will let you know in a few days... sorry for not being very responsive.

**Comment by rogierlommers** [comment]
Yes, hereby my confirmation. By using branch "im-6.8.9" I'm perfectly able to read TIF files (and do operations on it). When are you planning to merge with master?

**Comment by justinfx** [comment]
It was originally fixed in master, and picked into the 6.8.9 branch.
