### ISSUE TITLE
idea: master as >= ImageMagick 6.8.9 and make a legacy branch for < 

### ISSUE THREAD

**Issue by pkieltyka** [gographics/imagick#67]
This way we don't have to lock into im-6.8.9 branch for the newer version.

**Comment by justinfx** [comment]
I had asked about doing this same thing at one point when I had first created the extra branch. Originally it was going to be a <6.8.9 branch. But @hgfischer suggested it was still not the most compatible approach, as some linux distros have older defaults of ImageMagick?

Also I had this idea:
https://github.com/gographics/imagick/issues/52

We could switch to canonical and versioned paths as an option.

**Comment by pkieltyka** [comment]
its a good point if the default IM for many Linux distros is indeed <6.8.9 - is that really the majority though? 

Using import paths for versioning is interesting and I've seen it work for other pkgs in the past, but I've also seen gopkg.in servers fail quite often in the past, although it could be more stable now, and with vendoring its less of a problem.

**Comment by justinfx** [comment]
I haven't surveyed a number of distros or anything, but I took a quick glance at Ubuntu. >=6.8.9 didnt happent until 15.04. At my work, as an example, we aren't even fully migrated to 14.04. Now I don't know if that is a good enough reason. Maybe we should be focused on supporting the most common version range used in stable distro versions.

**Comment by pkieltyka** [comment]
I personally use a Dockerfile and build the most recent version of IM.. I tend to not like holding back a project because of other systems lingering. The best solution is prob something like gopkg.

**Comment by justinfx** [comment]
I tend to agree with you. Overall it would be easiest if we didn't even
have to maintain two streams. But I thought gopkg would at least make it
more clean, and easy to use the exact one you want from "go get"

**Comment by phacops** [comment]
I like the idea of master for >= 6.8.9 and a legacy branch with gopkg to help import one or the other.

**Comment by justinfx** [comment]
@hgfischer can have the final call

**Comment by hgfischer** [comment]
Happy new year!  :tada: 

Since we are a few months of the release of the next Ubuntu LTS, I think it is reasonable to use `>= 6.8.9` on `master` and have the `legacy` branch.

**Comment by justinfx** [comment]
Cool. What about additionally adding gopkg.in canonical import paths?

**Comment by justinfx** [comment]
I'm going to move forward on this. 
`master` branch will become the >=6.8.9 support
`legacy` branch will be the older support
I will set a v2.0.0 tag on `master`, which will be moved accordingly as new features are merged.
I will set a v1.0.0 tag on `legacy`

The result is that: 
`gopkg.in/gographics/imagick.v2/imagick` will map to master (>=6.8.9)
`gopkg.in/gographics/imagick.v1/imagick` will map to legacy (<6.8.9)

The only remaining question is whether we want to add canonical paths to each branch, ala:

```go
package imagick // import "gopkg.in/gographics/imagick.v2/imagick"
```

This would mean that users would need to start using the canonical versioned import paths to explicitly identify the ImageMagick support that they need.

**Comment by justinfx** [comment]
This has been completed. README has been updated. Closing this issue and we can follow up with my remaining question in #52
