### ISSUE TITLE
 error while loading shared libraries: libMagickWand-6.Q16.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Kroid** [gographics/imagick#69]
After compile and copy binary to sever: 
```
error while loading shared libraries: libMagickWand-6.Q16.so.1: cannot open shared object file: No such file or directory
```

Centos 6,
```
convert --version
Version: ImageMagick 6.9.3-0 Q16 x86_64 2016-01-16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib jng jpeg lcms ltdl openexr pangocairo png ps rsvg tiff webp wmf x xml zlib
```

```ldconfig /usr/local/lib``` not helped.

**Comment by justinfx** [comment]
Well that kind of makes sense to me, if you compiled it on one machine and
copies it to a machine that doesn't have ImageMagick installed in a common
system location or on the LD_LIBRARY_PATH

The binary is dynamically linked to ImageMagick unless you specifically go
about static linking

**Comment by Kroid** [comment]
How I can compile with static linking? I'm trying ```CGO_ENABLED=0 go build -a -installsuffix cgo```, but:
```
./main.go:32: undefined: imagick.Initialize
./main.go:33: undefined: imagick.Terminate
./main.go:87: undefined: imagick.NewMagickWand
./main.go:90: undefined: imagick.NewDrawingWand
./main.go:93: undefined: imagick.NewPixelWand

```

**Comment by justinfx** [comment]
You absolutely need cgo because it is what provides the library bindings to ImageMagick. 

Check out this older issue with an example of how I am doing it

https://github.com/gographics/imagick/issues/24

It's just a matter of using the build tag no_pkgconfig and then setting the cgo env to tell it to statically link ImagrMagick.

**Comment by Kroid** [comment]
Interesting. After exported CGO_CFLAGS and CGO_LDFLAGS:
```
$ go install -tags no_pkgconfig -v github.com/gographics/imagick/imagick
github.com/gographics/imagick/imagick
# github.com/gographics/imagick/imagick
gcc: error: /path/to/libtiff.a: No such file or directory
gcc: error: /path/to/libjpeg.a: No such file or directory

```

My home system fedora, I'm install libtiff and libjpeg packages, and *-tools, *-dev, etc.

**Comment by justinfx** [comment]
That is the pain of statically linking. You have to point it at all the
dependencies of ImageMagick. See how I was telling it where the static
libtiff and libjpeg are?

**Comment by Kroid** [comment]
Finally, after compile my main.go file on ubuntu machine and create soft symlink to libMagickWand-5 file on centos server, its work. Thanks a lot!
