### ISSUE TITLE
Could not determine kind of name for C.LanczosRadiusFilter

### ISSUE THREAD

**Issue by rogierlommers** [gographics/imagick#74]
I'm getting the error below while building my project, using the latest imagick. Any thoughts? The weird part is that I'm only getting these errors while building for Linux (AMD64). I'm not having them while running on OSX.

```
$ go version
go version go1.6 linux/amd64

$ go get gopkg.in/gographics/imagick.v2/imagick
# gopkg.in/gographics/imagick.v2/imagick
could not determine kind of name for C.LanczosRadiusFilter
```

**Comment by justinfx** [comment]
which version of ImageMagick are you using?

**Comment by rogierlommers** [comment]
Version 6.7.7.10

```
$ convert -version
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP
```

**Comment by rogierlommers** [comment]
Damn.... now I see the problem... I'm running an ancient version of ImageMagick.

**Comment by justinfx** [comment]
Yep I was just about to say that.  The symbol you are seeing was introduced
into 6.8.0-2

**Comment by justinfx** [comment]
And you should be using >= 6.8.9 for the v2 imagick,  otherwise v1 for slightly older

**Comment by rogierlommers** [comment]
Sorry to kick this issue, but I cannot figure out how to solve this. What I have is the following:

- operating system: RHEL 7.2
- ImageMagick version: 6.9.3-7
- I'm using version V2 from imagick (import "gopkg.in/gographics/imagick.v2/imagick")

I'm still getting the following error: could not determine kind of name for C.LanczosRadiusFilter and I can't figure out why? 

```
[root@1255782318f6 bin]# convert -version
Version: ImageMagick 6.9.3-7 Q16 x86_64 2016-03-14 http://www.imagemagick.org
```

**Comment by justinfx** [comment]
Can you check the output of building with "-x" to confirm which includes
and lib paths are really being used?
LanczosRadiusFilter is in the ImageMagick-6 branch. I would have to search
through the git history to find out what version in which the symbol was
introduced

**Comment by justinfx** [comment]
Oh sorry I read the history of this issues. The version you report using should have that symbol. You could probably even grep for it yourself in the ImageMagick headers

**Comment by rogierlommers** [comment]
Problem solved by kicking my head into the wall; strange vendoring issue prevented the v2 package to be included during build.

**Comment by justinfx** [comment]
Ah good. Because I didn't have a very good explanation for the cause ;-)

**Comment by jesselurie** [comment]
@rogierlommers what did you change specifically regarding vendor-ing to fix this? Running into the same issue.

**Comment by justinfx** [comment]
@jessielurie if you run your build with the `-x` flag does it show you which location the Imagick library is being found?

**Comment by rogierlommers** [comment]
In my case I deleted all docker layers (I'm building my binary inside a docker container).
