### ISSUE TITLE
ConstituteImage []interface{} issue

### ISSUE THREAD

**Issue by reaperhulk** [gographics/imagick#76]
The function declaration for ConstituteImage looks like this:

```go
func (mw *MagickWand) ConstituteImage(cols, rows uint, pmap string, stype StorageType, pixels []interface{}) error
```
Unfortunately this is problematic when passing `[]uint8` (e.g. an image.RGBA's `Pix`) since you'll get an error: `cannot use rgba.Pix (type []uint8) as type []interface {}`.

I'm not a go expert by any means so I'm not sure what the right solution is here. Maybe something like `ImportImagePixels`, which just takes `interface{}`?

**Comment by justinfx** [comment]
Yes, it should be updated to be more like what [`ImportImagePixels`](https://godoc.org/gopkg.in/gographics/imagick.v2/imagick#MagickWand.ImportImagePixels) does:

```go
func (mw *MagickWand) ImportImagePixels(x, y int, cols, rows uint, pmap string,
    stype StorageType, pixels interface{}) error
```

**Comment by reaperhulk** [comment]
I'm happy to put together this PR, but I'm not sure I know what's needed. Is it sufficient to just change it to `interface{}` or should I add a switch statement type check and have it error if the variable is not a slice of `byte`, `int16`, `int32`, etc?

**Comment by justinfx** [comment]
That would be cool if you want to put together the PR! It basically need to do the same type checks that are being done in `ImportImagePixels`. So maybe that logic needs to get pulled out into a function that returns an `unsafe.Pointer` and `error`:

```go
func (mw *MagickWand) pixelInterfaceToPtr(stype StorageType, pixels interface{}) (unsafe.Pointer, error) {
	var ptr unsafe.Pointer

	switch t := pixels.(type) {

	case []byte:
		v := &t[0]
		ptr = unsafe.Pointer(v)
		if stype == PIXEL_UNDEFINED {
			stype = PIXEL_CHAR
		}

	case []float64:
		v := &t[0]
		ptr = unsafe.Pointer(v)
		if stype == PIXEL_UNDEFINED {
			stype = PIXEL_DOUBLE
		}

	case []float32:
		v := &t[0]
		ptr = unsafe.Pointer(v)
		if stype == PIXEL_UNDEFINED {
			stype = PIXEL_FLOAT
		}

	case []int16:
		v := &t[0]
		ptr = unsafe.Pointer(v)
		if stype == PIXEL_UNDEFINED {
			stype = PIXEL_SHORT
		}

	case []int32:
		v := &t[0]
		ptr = unsafe.Pointer(v)
		if stype == PIXEL_UNDEFINED {
			stype = PIXEL_INTEGER
		}

	case []int64:
		v := &t[0]
		ptr = unsafe.Pointer(v)
		if stype == PIXEL_UNDEFINED {
			stype = PIXEL_LONG
		}

	default:
		return ptr, fmt.Errorf("Type %T is not valid for this operation", t)

	}

	return ptr, nil
}
```
