### ISSUE TITLE
couldn't build the library on windows 8 with TDM-GCC-64

### ISSUE THREAD

**Issue by iincity** [gographics/imagick#79]
couldn't build the library on windows 8 with TDM-GCC-64
OS:WINDOWS 8 
GCC:TDM-GCC-64, gcc version gcc version 5.1.0 (tdm64-1) ,mingw
imagick:ImageMagick-i686-pc-mingw32.tar.gz(ImageMagick.6.8.5)

E:\develop\Projects\src\gopkg.in\gographics\imagick.v2\imagick\draw_info.go:17:19: unexpected: 16-byte float type - long double

**Comment by justinfx** [comment]
This probably won't fix your issue, but note that you are using the wrong version of ImageMagick to pair with the v2 stream. Please see the README. V2 requires >= 6.8.9 

Aside from that, neither of the maintainers have windows boxes to test building imagick. Patches are welcome for anyone wanting to solidify windows support for this binding.

**Comment by justinfx** [comment]
Did the version mismatch actually fix the problem?

**Comment by iincity** [comment]
no
