### ISSUE TITLE
DestroyPixelWand assertion failure during GC

### ISSUE THREAD

**Issue by trebartha** [gographics/imagick#81]
Hi,

I've just today pulled your latest code and updated to imagick.v2. I'm now getting the below in the stacktrace:

> render-engine: ../../wand/pixel-wand.c:239: DestroyPixelWand: Assertion 'wand->signature == 0xabacadabUL' failed.
SIGABRT: abort
PC=0x7f394ad7d067
signal arrived during cgo execution
goroutine 19 [syscall]:
runtime.cgocall(0x41a9e0, 0x7f394bb48ea8)
	/usr/lib/go/src/pkg/runtime/cgocall.c:143 +0xe5 fp=0x7f394bb48e90 sp=0x7f394bb48e48
gopkg.in/gographics/imagick.v2/imagick._Cfunc_DestroyPixelWand(0x2be40b0, 0x4cea81)
	gopkg.in/gographics/imagick.v2/imagick/_obj/_cgo_defun.c:222 +0x31 fp=0x7f394bb48ea8 sp=0x7f394bb48e90
gopkg.in/gographics/imagick.v2/imagick.func·008()
	/media/sf_VirtualBox_Share/go/src/gopkg.in/gographics/imagick.v2/imagick/pixel_wand.go:55 +0x31 fp=0x7f394bb48ec8 sp=0x7f394bb48ea8
sync.(*Once).Do(0xc2081649e8, 0x7f394bb48ef8)
	/usr/lib/go/src/pkg/sync/once.go:40 +0x9f fp=0x7f394bb48ee0 sp=0x7f394bb48ec8
gopkg.in/gographics/imagick.v2/imagick.(*PixelWand).Destroy(0xc2081649e0)
	/media/sf_VirtualBox_Share/go/src/gopkg.in/gographics/imagick.v2/imagick/pixel_wand.go:60 +0x67 fp=0x7f394bb48f10 sp=0x7f394bb48ee0
gopkg.in/gographics/imagick.v2/imagick.Destroy(0x7f394bccdc80, 0xc2081649e0)
	/root/go/src/gopkg.in/gographics/imagick.v2/imagick/destroy.go:8 +0x2d fp=0x7f394bb48f20 sp=0x7f394bb48f10
runtime.call16(0x627f60, 0xc208130000, 0x1000000010)
	/usr/lib/go/src/pkg/runtime/asm_amd64.s:360 +0x32 fp=0x7f394bb48f38 sp=0x7f394bb48f20
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2682 +0x207 fp=0x7f394bb48fa8 sp=0x7f394bb48f38
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445 fp=0x7f394bb48fb0 sp=0x7f394bb48fa8
created by runtime.gc
	/usr/lib/go/src/pkg/runtime/mgc0.c:2268

The only change I made to my code was to change the imagick import to the new v2 path. The code explicitly destroy all imagick objects and has no memory leaks. So it looks like there may be a problem with the new GC destroyer logic. I ran it several times and the panics were consistent. If I turn-off GC my code runs without crashing.

Any ideas? Are we not supposed to destroy objects ourselves anymore? If so, this change is going to break a lot of existing code.

Cheers.

**Comment by justinfx** [comment]
How are you creating them? Are you using the "New" constructor?

**Comment by justinfx** [comment]
Actually, are you getting the pixel wand from a pixel iterator? Is it related to this? http://www.imagemagick.org/discourse-server/viewtopic.php?t=19433

If so, It looks like we have to make sure not to allow the automatic destroy to happen on pixel wands that are returned from the pixel iterator

**Comment by justinfx** [comment]
This is related to #62. I have a local patch for this and will commit it tomorrow. 
The problem is that the 3 methods of a `PixelIterator` that return a `[]*PixelWand` should not be using the finalizers for managing those `*PixelWand` objects.

**Comment by trebartha** [comment]
Ah yes, good find. I should have thought of that. I remember now finding the same post when I first started using pixel iterators and tried destroying the pixel wands myself.
Just to confirm, I've run a test bypassing the iterators and there's no crashing, so that's definitely the issue.
Thanks for the quick turnaround with the fix.
Cheers.

**Comment by justinfx** [comment]
No worries. It was an oversight with the new system of memory management.
Previously it was on you, the caller to destroy the right things. Now the
library has to also do the right thing and not manage these when  it
shouldn't
