### ISSUE TITLE
Fail to cross compile

### ISSUE THREAD

**Issue by sillydong** [gographics/imagick#84]
pkg-config info cflags:

> sillydong:include chenzhidong$ pkg-config --cflags MagickWand MagickCore
-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/6.9.2-4/include/ImageMagick-6

pkg-config info libs:

> sillydong:include chenzhidong$ pkg-config --libs MagickWand MagickCore
-L/usr/local/Cellar/imagemagick/6.9.2-4/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16

build command:

`GOOS=linux GOARCH=amd64 CGO_ENABLE=1 CGO_CFLAGS="-I/usr/local/Cellar/imagemagick/6.9.2-4/include/ImageMagick-6" CGO_LDFLAGS="-L/usr/local/Cellar/imagemagick/6.9.2-4/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16" go build`

result:

> lib/scale.go:44: undefined: imagick.MagickWand
lib/scale.go:47: undefined: imagick.ORIENTATION_TOP_LEFT
lib/scale.go:58: undefined: imagick.NewPixelWand
lib/thumber.go:22: undefined: imagick.NewMagickWand
lib/thumber.go:36: undefined: imagick.NewMagickWand
lib/thumber.go:61: undefined: imagick.NewMagickWand

Don't know how to compile it for linux, NEEDS HELP! Thanks!

**Comment by justinfx** [comment]
Is this even possible? You are trying to link a linux binary against OSX ImageMagick libs. I would think you would have to have a linux build of ImageMagick accessible by that machine, and even then I am not sure what cross-compilation does with a CGO library.

**Comment by justinfx** [comment]
I'm going to close this because it isn't really a problem with the Imagick library. It required that you have a Linux build of ImageMagick available so that you can cross compile against it. 
CGO is not the easiest thing to cross compile for this same reason.
