### ISSUE TITLE
docker compile termination

### ISSUE THREAD

**Issue by namsoila** [gographics/imagick#86]
# gopkg.in/gographics/imagick.v2/imagick
src/gopkg.in/gographics/imagick.v2/imagick/affine_matrix.go:8:29: fatal error: wand/MagickWand.h: No such file or directory
 #include <wand/MagickWand.h>
                             ^
compilation terminated.

Any suggestions?

**Comment by namsoila** [comment]
#include <wand/MagickWand.h>

That's part with the include

**Comment by namsoila** [comment]
I mean #include wand/MagicWand.h

**Comment by namsoila** [comment]
Docker files are from:

https://github.com/GoogleCloudPlatform/abelana/tree/master/ImageResizer

Got to compile with:

https://gist.github.com/namsoila/fcdbc8c8ee28b7250e59afc260a8a593

Error is with:

https://gist.github.com/namsoila/4a24d2ed32dccff09c6065ca8c7c2d12

**Comment by justinfx** [comment]
This indicates that the includes for ImageMagick can't be found when Go
compiles the Imagick package.

Are you able to run this from within your docker image?

pkg-config --cflags --libs MagickWand

Imagick expects to be able to ask pkg-config where the includes and
libraries are located.

**Comment by namsoila** [comment]
-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/include/ImageMagick-6 -L/usr/local/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16

**Comment by namsoila** [comment]
That's with the version that has ImageMagick-6.9.3-10

**Comment by justinfx** [comment]
Does /usr/local/include/ImageMagick-6 contain  "wand/MagickWand.h"?

I still don't really know why, but your build isn't seeing your include
location, if it exists.

**Comment by namsoila** [comment]
It does for ImageMagick-6.9.3-10.  I am building the ImageMagick-7.0.1-1 version and will update.

**Comment by justinfx** [comment]
I am not following. Which version are you trying to build against and
failing to do so?
I've not tested Imagemagick 7.x yet with the bindings.

**Comment by namsoila** [comment]
1. ImageMagick-6.9.3-10
Builds without issue and has the wand/MagickWand.h
Dockerfile used:
https://gist.github.com/namsoila/fcdbc8c8ee28b7250e59afc260a8a593

2. ImageMagick-7.0.1-1
Does not.
Dockerfile used:
https://gist.github.com/namsoila/4a24d2ed32dccff09c6065ca8c7c2d12

**Comment by namsoila** [comment]
Though the ImageMagick-7.0.1-1 gives that error, it does build the image.

Running pkg-config --cflags --libs MagickWand within that image gives:

-fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/include/ImageMagick-7 -L/usr/local/lib -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI

Checking /usr/local/include/ImageMagick-7 shows:

drwxr-sr-x 2 root staff 4096 May  7 07:22 Magick++
-rw-r--r-- 1 root staff  713 May  7 07:22 Magick++.h
drwxr-sr-x 2 root staff 4096 May  7 07:22 MagickCore
drwxr-sr-x 2 root staff 4096 May  7 07:22 MagickWand

So in comparison to /usr/local/include/ImageMagick-6:

drwxr-sr-x 2 root staff 4096 May  6 17:13 Magick++
-rw-r--r-- 1 root staff  713 May  6 17:13 Magick++.h
drwxr-sr-x 2 root staff 4096 May  6 17:13 magick
drwxr-sr-x 2 root staff 4096 May  6 17:13 wand

It seems that in ImageMagick-6.9.3-10 the file MagickWand.h is stored in /usr/local/include/ImageMagick-6/wand whereas in ImageMagick-7.0.1-1 it is stored in /usr/local/include/ImageMagick-7/MagickWand.

**Comment by justinfx** [comment]
It looks like they rearranged the location of header files in ImageMagick-7.x:

https://github.com/ImageMagick/ImageMagick/blob/master/MagickWand/MagickWand.h
https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/MagickCore.h

Assuming the bindings are still compatible with the newest ImageMagick, once the headers are found, you could try creating symlinks in your install location:

magick -> MagickCore
wand -> MagickWand

**Comment by namsoila** [comment]
Cool. Thanks.

**Comment by jackluo2012** [comment]
I have ln -s  ,but errors magick -> MagickCore
could not determine kind of name for C.DiscreteAlphaChannel
could not determine kind of name for C.OffAlphaChannel
could not determine kind of name for C.OnAlphaChannel
