### ISSUE TITLE
Crash in go caused by library

### ISSUE THREAD

**Issue by diegomontoya** [gographics/imagick#88]
Not sure what caused the following crash. Any pointers?

```go
magick/semaphore.c:346: LockSemaphoreInfo: Assertion `semaphore_info != (SemaphoreInfo *) ((void *)0)' failed.
SIGABRT: abort
PC=0x35c40325e5 m=16
signal arrived during cgo execution

goroutine 3525915 [syscall, locked to thread]:
runtime.cgocall(0xb3fb00, 0xc43d83adf8, 0xc400000000)
	/root/go/src/runtime/cgocall.go:130 +0x110 fp=0xc43d83adc8 sp=0xc43d83ad88
github.com/gographics/imagick/imagick._Cfunc_DestroyMagickWand(0x7f40f00203d0, 0x0)
	??:0 +0x4a fp=0xc43d83adf8 sp=0xc43d83adc8
github.com/gographics/imagick/imagick.(*MagickWand).Destroy.func1()
	/root/lbx/go/src/github.com/gographics/imagick/imagick/magick_wand.go:61 +0x7c fp=0xc43d83ae48 sp=0xc43d83adf8
sync.(*Once).Do(0xc43b0f1048, 0xc43d83ae90)
	/root/go/src/sync/once.go:44 +0xdb fp=0xc43d83ae80 sp=0xc43d83ae48
github.com/gographics/imagick/imagick.(*MagickWand).Destroy(0xc43b0f1040)
	/root/lbx/go/src/github.com/gographics/imagick/imagick/magick_wand.go:66 +0x52 fp=0xc43d83aeb0 sp=0xc43d83ae80
```

**Comment by justinfx** [comment]
Do you have a reproduction of the code that caused the crash?

**Comment by diegomontoya** [comment]
It may be caused by our incorrect use of 

```go
  imagick.Initialize()
  defer imagick.Terminate()
```
In our work pool doing work in go routines. We were calling imagick.Terminate() in 1 go routine while another might still be using imagick. 

I am assuming imagick.Initialize()/terminate() should only be called once per process correct?

**Comment by justinfx** [comment]
Correct. Its actually an ImageMagick C API thing as well. Call it once in your application to initialize, and once when your application tears down. Or at least ensure that when you call Terminate, you are really done doing processing and want to free up ImageMagick. We do have synchronisation in place, but you still need to not call Terminate while work is happening.

**Comment by diegomontoya** [comment]
@justinfx  Thanks for the clarification.

**Comment by justinfx** [comment]
No problem!
