### ISSUE TITLE
How to add a watermark?

### ISSUE THREAD

**Issue by skyleelove** [gographics/imagick#90]
Hi ,

How can I do to add watermark to a image?

**Comment by justinfx** [comment]
Sorry for the delay.

You can find general examples of this by looking up watermarking for ImageMagick:
http://www.imagemagick.org/Usage/annotating/#wmark_image

I've thrown together an example based on this

```go
package main

import "gopkg.in/gographics/imagick.v2/imagick"

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	dest := imagick.NewMagickWand()
	dest.ReadImage("logo:")

	w := dest.GetImageWidth()
	h := dest.GetImageHeight()

	watermark := imagick.NewMagickWand()
	watermark.SetSize(w, h)
	watermark.ReadImage("plasma:white-black")
	watermark.ModulateImage(100, 0, 100)
	watermark.SetImageOpacity(.33)

	dest.CompositeImage(watermark, imagick.COMPOSITE_OP_DISSOLVE, 0, 0)

	dest.WriteImage("out.jpg")
}
```

Is this what you are after?

**Comment by skyleelove** [comment]
Hi,
  Thanks for your help.When I add a watermark to a image, if the watermark's format is svg , it will work not better, when I use watermark.ModulateImage(100, 0, 100).What can I do?

**Comment by justinfx** [comment]
What exactly doesn't work? You you mean the `ModulateImage` has no effect in desaturating a color svg for the watermark?  Do you mean that the watermark absolute doesn't work?

Again, this is more just about a general ImageMagick problem than the iMagick bindings. You may find your answer by Googling, such as [here](http://www.imagemagick.org/discourse-server/viewtopic.php?t=23998), or asking the ImageMagick forum your own question about doing it via the API

**Comment by Nicksxs** [comment]
@justinfx thanks a lot for your code
