### ISSUE TITLE
Set a magick wand image instead of reading it

### ISSUE THREAD

**Issue by wigywizzle** [gographics/imagick#92]
I checked out the C API to try to find out how one would set the image of the magick wand instead of reading an image in, but I couldn't find anything.  Currently what I'm being forced to do is to write an image out to a file using ioutil, then I read the image file back in using imagick.  Surely I must be missing something, as having to Write and Read a file is a huge bottleneck.  Any ideas on how I can get around this? (I've attached my demo code below)

    /*
    Purpose:  To convert an uploaded PDF into PNG's using Imagick. 
    Currently I need to write the file out before I can read it into the magick wand.  
    I'd prefer to just set the magick wands images to my pdf. 
    That way I don't have to save it and can just pass it in.
    */
    // Write the (uploaded) pdf to a file, which takes a very long time...
    ioutil.WriteFile("tempWrite.pdf", pdf, 0644)

    //Start up Imagick
    imagick.Initialize()
    defer imagick.Terminate()
    mw := imagick.NewMagickWand()

    // Read the pdf into imagick
    mw.ReadImage("tempWrite.pdf")

    // Write the page images to a folder.
    os.MkdirAll("temp/", 0777)
    mw.WriteImages("temp/" + fileName + ".png", false)

**Comment by justinfx** [comment]
Looks like you want the `ReadImageBlob` method:

https://godoc.org/gopkg.in/gographics/imagick.v2/imagick#MagickWand.ReadImageBlob

**Comment by wigywizzle** [comment]
That is exactly what I was looking for.  I should have taken a second look at the docs. Thanks for the quick reply!
