### ISSUE TITLE
Adding circle over image and filling outside

### ISSUE THREAD

**Issue by amlwwalker** [gographics/imagick#94]
I want to get this:
![image](https://cloud.githubusercontent.com/assets/2920180/18731669/2dce943e-8055-11e6-8398-e8a1b0d68466.png)

(the circle colour is just set to red)
The command I am using in imagemagick to get that is:

```
convert start.png -resize 400x400  -stroke white  -fill None  -strokewidth 120 -draw 'translate 100,100  circle 100,100 350,50' -stroke 'red'  -fill None  -strokewidth 25 -draw 'translate 100,100  circle 100,100 275,50' -quality 100   end.jpg
```
I can currently get this:

![image](https://cloud.githubusercontent.com/assets/2920180/18731761/e5308a60-8055-11e6-90e8-50d465389703.png)

The command

* I set the image to the correct size (400x400)
* instantiate a DrawingWand and PixelWand
* Set Color to red
* Set FillColor to none
* Draw the circle with: `dw.Circle(200,200,275,50)` - I don't understand what the x perimeter and y perimeter variables are supposed to be, they don't seem to act as x and y radiuses? The outer edge of the circle should be touching the edge of the image

What I'm not sure how to do is fill **outside** the circle with a color (white)??

Thanks

**Comment by justinfx** [comment]
I haven't looked into this yet, but have you tried asking this question on the ImageMagick forums? This isn't really specific to iMagick. Its just a matter of using the ImageMagick API

**Comment by amlwwalker** [comment]
I know how to do it in straight up imagemagick - thats the command I posted above, and how I got the first image - I am trying to produce the same image however in Go with this library. I am able to generate the second image (which is almost, but not quite there) with gographics/imagemagick library like this:

```
	imagick.Initialize()
	defer imagick.Terminate()
	mw := imagick.NewMagickWand()
	data, _ := ioutil.ReadFile("in.png")
	mw.ReadImageBlob(data)
	
	mw.ResizeImage(400, 400, imagick.FILTER_LANCZOS,1)
	mw.SetImageCompressionQuality(95)
	dw := imagick.NewDrawingWand()
	cw := imagick.NewPixelWand()
	dw.SetStrokeOpacity(1)
	dw.PushDrawingWand()

	cw.SetColor("red")
	dw.SetStrokeColor(cw)
	dw.SetStrokeWidth(25)
	dw.SetStrokeAntialias(true)
	cw.SetColor("none")
	dw.SetFillColor(cw)
	dw.Circle(200,200,275,50)
	mw.DrawImage(dw)
	mw.WriteImage("out.jpg")
```

Im not sure how the imagemagick forums would help, because I am able to do it in vanilla imagemagick, and I am using Golang and this library...

**Comment by justinfx** [comment]
I think you misunderstood my comment. I realize you know how to do it with
the convert command line tool, which is provided by ImageMagick. What I
meant was that Go is just a thin wrapper on the ImageMagick C api

http://www.imagemagick.org/script/magick-wand.php

That means usage and support should basically be the same between the
official C api and how you would do it with Go bindings. So I suggested you
also get some responses from the ImageMagick community on how to generally
use ImageMagick api, when the issue is not directly related to issues with
the Go bindings.

I will try and have a play with your example tomorrow though.

**Comment by amlwwalker** [comment]
right.... ok i'll see what I can find there
Thanks for your help, I'll have a read there and come back if i work it out (or not...)

**Comment by amlwwalker** [comment]
I got it @justinfx thanks - in the end I just drew a second circle with a really thick stroke

Thanks!

**Comment by rogierlommers** [comment]
Can you please share your code for (possible) future use?

**Comment by justinfx** [comment]
Hah, I actually just tested it and came up with the same solution to your problem, then saw you just solved it :-) Nice job.
