### ISSUE TITLE
painc when I use ReadImageBlob()?

### ISSUE THREAD

**Issue by skyleelove** [gographics/imagick#97]
Hi,

  When I use ReadImageBlob(blob), it get a painc.

  panic: ERROR_MISSING_DELEGATE: no decode delegate for this image format `' @ error/blob.c/BlobToImage/355

How can i do for this?Thanks.

**Comment by justinfx** [comment]
Which format are you having trouble reading? It implies that your ImageMagick lib isn't built with plugin support for the given format. What do you get in the "Delegates" section when you run:

```
identify -version
```

**Comment by skyleelove** [comment]
Hi,
 Here are the information

Features: Cipher DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib

**Comment by skyleelove** [comment]
I set the format svg

**Comment by justinfx** [comment]
Here is another way to know all of the formats you can read:

```go
package main

import (
	"fmt"

	"gopkg.in/gographics/imagick.v2/imagick"
)

func main() {
	imagick.Initialize()
	mw := imagick.NewMagickWand()
	fmt.Println(mw.QueryFormats("*"))
}
```

In my own output, I see support for SVG

**Comment by skyleelove** [comment]
Hi, in my output, I also see support for SVG

**Comment by justinfx** [comment]
Are you able to successfully convert to and from svg with the `convert` command? Also what version of ImageMagick are you using?

**Comment by justinfx** [comment]
Also, the output from `identify -list configure` might be helpful as well

**Comment by skyleelove** [comment]
Hi,

 The version of ImageMagick is 6.9.4.

**Comment by justinfx** [comment]
What was the answer to the other question? Can you successfully convert to and from SVG with the `convert` command line tool? Because if you can, then either some how the delegates are missing from within Imagick bindings (not sure how), or maybe you have some malformed SVG data that you are trying to read in code.  If that is the case, you may need to post a sample of your code and also the data file you are trying to read.

**Comment by justinfx** [comment]
Are you by chance having this issue? http://stackoverflow.com/a/15614469/496445
That is an example of having malformed SVG data that ImageMagick can't read.

**Comment by skyleelove** [comment]
Hi, thanks for your help.

**Comment by justinfx** [comment]
Is your issue solved? What was it?

**Comment by skyleelove** [comment]
As you give,I find my svg miss the standalone,I set it 'no', it works.
$svg = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>'.$svg;
Thank you very much

**Comment by justinfx** [comment]
Very good. Thanks for letting me know it is resolved!
