### ISSUE TITLE
could not determine kind of name for C.FlattenAlphaChannel and C.ResetAlphaChannel

### ISSUE THREAD

**Issue by brunoqc** [gographics/imagick#98]
```
could not determine kind of name for C.FlattenAlphaChannel
could not determine kind of name for C.ResetAlphaChannel
```

ImageMagick-7.0.3-Q16
Win XP 32-bit
go version go1.7.1 windows/386
gcc (GCC) 5.3.0

**Comment by brunoqc** [comment]
I also have:

```
could not determine kind of name for C.Rec601LumaColorspace
could not determine kind of name for C.Rec709LumaColorspace
could not determine kind of name for C.CopyOpacityCompositeOp
could not determine kind of name for C.ConvertHSBToRGB
could not determine kind of name for C.ConvertRGBToHSB
```

**Comment by justinfx** [comment]
We don't yet have a build for ImageMagick 7.x

Patches welcome.

**Comment by justinfx** [comment]
I will update the readme to indicate that v2 supports only 6.x max. It was written before there was a 7.x that introduced incompatiblity

**Comment by skyleelove** [comment]
Hi,
  I change the imagemagick version to 6.9.6, it still get this error.
  # gopkg.in/gographics/imagick.v2/imagick
could not determine kind of name for C.FlattenAlphaChannel
could not determine kind of name for C.RemoveAlphaChannel

**Comment by justinfx** [comment]
I'm building 6.9.6 and a few other ImageMagick 6.x versions to test this

**Comment by justinfx** [comment]
Are you sure you are using the correct Imagick and correct ImageMagick? I've just build `ImageMagick 6.9.6-2` from source (https://github.com/ImageMagick/ImageMagick.git) and built and ran the go tests for it. Didn't have any issues. Imagick v2 looks to build find for 6.8.9-9 through 6.9.6-2

**Comment by skyleelove** [comment]
Hi,
 I will try,thank you very much.

**Comment by skyleelove** [comment]
Hi,

   I built ImageMagick 6.9.6-2 from source (https://github.com/ImageMagick/ImageMagick.git) and an the go tests for it.But I got this:
   /usr/local/include/ImageMagick-6/include/ImageMagick-6/magick/magick-config.h:52:3: warning：#warning "you should set MAGICKCORE_HDRI_ENABLE to sensible default set it to configure time default"

   /usr/local/include/ImageMagick-6/include/ImageMagick-6/magick/magick-config.h:53:3: warning：#warning "this is an obsolete behavior please fix yours makefile"

**Comment by justinfx** [comment]
That says they are warnings. Did it fail? Did you adjust your build command? What was your build command?

It helps to be very specific about your process, otherwise we have to wait for each other to go back and forth in the replies. 

As it stands, I was able to build and test without error, against this ImageMagick.

**Comment by skyleelove** [comment]
My Build command is:
 go run test.go
And I think that I built ImageMagick 6.9.6-2 is wrong.Can you show me how you do?
My system information is:
2016 x86_64 x86_64 x86_64 GNU/Linux

I test it got this error:

magick_core_env.cgo2.c:(.text+0x65): undefined reference to `IsMagickCoreInstantiated'
/tmp/go-build033430591/gopkg.in/gographics/imagick.v2/imagick/_obj/magick_wand_image.cgo2.o: In function `_cgo_5094f36c0b9a_Cfunc_MagickAutoOrientImage':
magick_wand_image.cgo2.c:(.text+0x7af): undefined reference to `MagickAutoOrientImage'
/tmp/go-build033430591/gopkg.in/gographics/imagick.v2/imagick/_obj/magick_wand_image.cgo2.o: In function `_cgo_5094f36c0b9a_Cfunc_MagickCompositeLayers':
magick_wand_image.cgo2.c:(.text+0x1288): undefined reference to `MagickCompositeLayers'
/tmp/go-build033430591/gopkg.in/gographics/imagick.v2/imagick/_obj/magick_wand_image.cgo2.o: In function `_cgo_5094f36c0b9a_Cfunc_MagickGetImageEndian':
magick_wand_image.cgo2.c:(.text+0x2d3c): undefined reference to `MagickGetImageEndian'
/tmp/go-build033430591/gopkg.in/gographics/imagick.v2/imagick/_obj/magick_wand_image.cgo2.o: In function `_cgo_5094f36c0b9a_Cfunc_MagickOptimizeImageTransparency':
magick_wand_image.cgo2.c:(.text+0x4614): undefined reference to `MagickOptimizeImageTransparency'
/tmp/go-build033430591/gopkg.in/gographics/imagick.v2/imagick/_obj/magick_wand_image.cgo2.o: In function `_cgo_5094f36c0b9a_Cfunc_MagickRotationalBlurImage':
magick_wand_image.cgo2.c:(.text+0x5042): undefined reference to `MagickRotationalBlurImage'
/tmp/go-build033430591/gopkg.in/gographics/imagick.v2/imagick/_obj/magick_wand_image.cgo2.o: In function `_cgo_5094f36c0b9a_Cfunc_MagickRotationalBlurImageChannel':
magick_wand_image.cgo2.c:(.text+0x50ae): undefined reference to `MagickRotationalBlurImageChannel'
/tmp/go-build033430591/gopkg.in/gographics/imagick.v2/imagick/_obj/magick_wand_image.cgo2.o: In function `_cgo_5094f36c0b9a_Cfunc_MagickSetImageEndian':
magick_wand_image.cgo2.c:(.text+0x5a5e): undefined reference to `MagickSetImageEndian'
/tmp/go-build033430591/gopkg.in/gographics/imagick.v2/imagick/_obj/magick_wand_image.cgo2.o: In function `_cgo_5094f36c0b9a_Cfunc_MagickStatisticImageChannel':
magick_wand_image.cgo2.c:(.text+0x6b17): undefined reference to `MagickStatisticImageChannel'

**Comment by justinfx** [comment]
This error output looks like your ImageMagick libraries can't be found. What is the output when you run this?

```
pkg-config --cflags --libs MagickWand
```

You should get output that points correctly to your ImageMagick installed location. Lets say my custom build of ImageMagick is installed to `/path/to/my/ImageMagick-6.9.6-2`. Within that location, I should have includes and libs. I can then tell pkg-config to use that location:

```
export PKG_CONFIG_PATH=/path/to/my/ImageMagick-6.9.6-2/libs/pkgconfig
cd gographics/imagick.v2/imagick
go test -v 
```

What I think you might be doing is just building ImageMagick, but maybe not helping Go to find it? The imagick bindings want to use pkg-config to figure out the ImageMagick location.

**Comment by skyleelove** [comment]
Thank you!I solve this problem by:
export PKG_CONFIG_PATH=/path/to/my/ImageMagick-6.9.6-2/libs/pkgconfig

**Comment by justinfx** [comment]
Closing this since it's not actually meant for ImageMagick 7.x, but rather a clarification that imagick v2 only supports up to im 6.9.6-2

ImageMagick 7.x support is being worked on.
