### ISSUE TITLE
draw_info.go:17:19: unexpected: 12-byte float type - long double

### ISSUE THREAD

**Issue by brunoqc** [gographics/imagick#99]
ImageMagick-7.0.3-Q16
Win XP 32-bit
go version go1.7.1 windows/386
gcc (GCC) 5.3.0

**Comment by justinfx** [comment]
Duplicate problem of #98

We don't yet have support for ImageMagick 7.x

**Comment by brunoqc** [comment]
ok

**Comment by justinfx** [comment]
Closed as dup of #98
